WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_2881ddc849d20420 = T_2881ddc849d20420 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_2881ddc849d20420__Menu", name_id = "bm_w_browning", inject_menu = "WACApplyMyMenuMenu", class = T_2881ddc849d20420}) 
T_33689a2190ae82a8 = T_33689a2190ae82a8 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_33689a2190ae82a8__FMenu", name_id = "Loc_bfa0262adfba264f", inject_menu = "T_2881ddc849d20420__Menu", class = T_33689a2190ae82a8}) 
function T_33689a2190ae82a8:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_b445fb22207357b1", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_78dd3d92f85dbf25", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["wpn_fps_sho_browning_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["wpn_fps_sho_browning_m_extended"] or false 
	self:Toggle({ name = "T_242882386e2a4cf0", text = "Loc_f0032979772e1c4f", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["wpn_fps_sho_browning_m_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["wpn_fps_sho_browning_m_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["wpn_fps_sho_browning_m_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["wpn_fps_sho_browning_m_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]) do if i ~= "wpn_fps_sho_browning_m_extended" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["wpn_fps_sho_browning_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["wpn_fps_sho_browning_m_long"] or false 
	self:Toggle({ name = "T_373d35fb5cf9bc70", text = "Loc_4e44293c2c418ec2", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["wpn_fps_sho_browning_m_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["wpn_fps_sho_browning_m_long"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["wpn_fps_sho_browning_m_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]["wpn_fps_sho_browning_m_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"]) do if i ~= "wpn_fps_sho_browning_m_long" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_standard"][i] = false end end end }) 
end 
T_5891a7e45da6fd1c = T_5891a7e45da6fd1c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_5891a7e45da6fd1c__FMenu", name_id = "Loc_9cd2ea12307b6b8c", inject_menu = "T_2881ddc849d20420__Menu", class = T_5891a7e45da6fd1c}) 
function T_5891a7e45da6fd1c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_5b326e37ba0e451f", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_f56a4921394e4c1d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["wpn_fps_sho_browning_b_reinforced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["wpn_fps_sho_browning_b_reinforced"] or false 
	self:Toggle({ name = "T_ef36630f9fbcad50", text = "Loc_85a2a4955cfb144d", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["wpn_fps_sho_browning_b_reinforced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["wpn_fps_sho_browning_b_reinforced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["wpn_fps_sho_browning_b_reinforced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]["wpn_fps_sho_browning_b_reinforced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"]) do if i ~= "wpn_fps_sho_browning_b_reinforced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_standard"][i] = false end end end }) 
end 
T_b606c40dc685bea4 = T_b606c40dc685bea4 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b606c40dc685bea4__FMenu", name_id = "Loc_cc19d2b9f3e6d428", inject_menu = "T_2881ddc849d20420__Menu", class = T_b606c40dc685bea4}) 
function T_b606c40dc685bea4:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_70a692175aa9ac85", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_3c0321a35d941753", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_body_standard"][i] = false end end end }) 
end 
T_49b1e4e6913211f4 = T_49b1e4e6913211f4 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_49b1e4e6913211f4__FMenu", name_id = "Loc_8d13733c44bd7817", inject_menu = "T_2881ddc849d20420__Menu", class = T_49b1e4e6913211f4}) 
function T_49b1e4e6913211f4:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_7d5010ab20cb0884", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_bd65f62f145e9356", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_dh_standard"][i] = false end end end }) 
end 
T_65ddc32239d2221e = T_65ddc32239d2221e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_65ddc32239d2221e__FMenu", name_id = "Loc_d0ec0b6d9d269115", inject_menu = "T_2881ddc849d20420__Menu", class = T_65ddc32239d2221e}) 
function T_65ddc32239d2221e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]["Invisible"] or false 
	self:Toggle({ name = "T_cd1b82be5e0d8263", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]["Forced"] or false 
	self:Toggle({ name = "T_e23c94a517616de5", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_lifter"][i] = false end end end }) 
end 
T_e0d19ad33f753fdb = T_e0d19ad33f753fdb or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_e0d19ad33f753fdb__FMenu", name_id = "Loc_3d46e8bbeb67f851", inject_menu = "T_2881ddc849d20420__Menu", class = T_e0d19ad33f753fdb}) 
function T_e0d19ad33f753fdb:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_436e4d60ed204e36", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["Forced"] or false 
	self:Toggle({ name = "T_02cacf9416f3aaf0", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["wpn_fps_sho_browning_s_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["wpn_fps_sho_browning_s_grip"] or false 
	self:Toggle({ name = "T_062421406a95e148", text = "Loc_ee980494d038377e", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["wpn_fps_sho_browning_s_grip"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["wpn_fps_sho_browning_s_grip"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["wpn_fps_sho_browning_s_grip"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]["wpn_fps_sho_browning_s_grip"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"]) do if i ~= "wpn_fps_sho_browning_s_grip" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_standard"][i] = false end end end }) 
end 
T_f9382f44890958c5 = T_f9382f44890958c5 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_f9382f44890958c5__FMenu", name_id = "Loc_d84dbad03463fd31", inject_menu = "T_2881ddc849d20420__Menu", class = T_f9382f44890958c5}) 
function T_f9382f44890958c5:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]["Invisible"] or false 
	self:Toggle({ name = "T_eefd4b0e6ad4a91a", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]["Forced"] or false 
	self:Toggle({ name = "T_ce293d163f6b6c92", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_slug"][i] = false end end end }) 
end 
T_b9a696af3a8e1060 = T_b9a696af3a8e1060 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b9a696af3a8e1060__FMenu", name_id = "Loc_f0032979772e1c4f", inject_menu = "T_2881ddc849d20420__Menu", class = T_b9a696af3a8e1060}) 
function T_b9a696af3a8e1060:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["Invisible"] or false 
	self:Toggle({ name = "T_8b4b1938b8c25ac4", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["Forced"] or false 
	self:Toggle({ name = "T_8a2885ce1b20c07a", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["wpn_fps_sho_browning_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["wpn_fps_sho_browning_m_standard"] or false 
	self:Toggle({ name = "T_eae2e9e75bd06a5e", text = "Loc_bfa0262adfba264f", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["wpn_fps_sho_browning_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["wpn_fps_sho_browning_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["wpn_fps_sho_browning_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["wpn_fps_sho_browning_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]) do if i ~= "wpn_fps_sho_browning_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["wpn_fps_sho_browning_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["wpn_fps_sho_browning_m_long"] or false 
	self:Toggle({ name = "T_8337286d58f3c8ff", text = "Loc_4e44293c2c418ec2", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["wpn_fps_sho_browning_m_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["wpn_fps_sho_browning_m_long"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["wpn_fps_sho_browning_m_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]["wpn_fps_sho_browning_m_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"]) do if i ~= "wpn_fps_sho_browning_m_long" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_extended"][i] = false end end end }) 
end 
T_f19de338820239e4 = T_f19de338820239e4 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_f19de338820239e4__FMenu", name_id = "Loc_4e44293c2c418ec2", inject_menu = "T_2881ddc849d20420__Menu", class = T_f19de338820239e4}) 
function T_f19de338820239e4:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["Invisible"] or false 
	self:Toggle({ name = "T_bfdd21b69430e775", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["Forced"] or false 
	self:Toggle({ name = "T_1b8c4acbf52116f2", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["wpn_fps_sho_browning_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["wpn_fps_sho_browning_m_standard"] or false 
	self:Toggle({ name = "T_67e834c88fa8a9b9", text = "Loc_bfa0262adfba264f", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["wpn_fps_sho_browning_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["wpn_fps_sho_browning_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["wpn_fps_sho_browning_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["wpn_fps_sho_browning_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]) do if i ~= "wpn_fps_sho_browning_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["wpn_fps_sho_browning_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["wpn_fps_sho_browning_m_extended"] or false 
	self:Toggle({ name = "T_ea7fa93a71fc85fa", text = "Loc_f0032979772e1c4f", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["wpn_fps_sho_browning_m_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["wpn_fps_sho_browning_m_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["wpn_fps_sho_browning_m_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]["wpn_fps_sho_browning_m_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"]) do if i ~= "wpn_fps_sho_browning_m_extended" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_m_long"][i] = false end end end }) 
end 
T_e7a4d3d036ce683c = T_e7a4d3d036ce683c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_e7a4d3d036ce683c__FMenu", name_id = "Loc_85a2a4955cfb144d", inject_menu = "T_2881ddc849d20420__Menu", class = T_e7a4d3d036ce683c}) 
function T_e7a4d3d036ce683c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["Invisible"] or false 
	self:Toggle({ name = "T_96e9f4b7d8da322e", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["Forced"] or false 
	self:Toggle({ name = "T_a679bb245fffe1db", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["wpn_fps_sho_browning_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["wpn_fps_sho_browning_b_standard"] or false 
	self:Toggle({ name = "T_04e924f0c28ae4e6", text = "Loc_9cd2ea12307b6b8c", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["wpn_fps_sho_browning_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["wpn_fps_sho_browning_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["wpn_fps_sho_browning_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]["wpn_fps_sho_browning_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"]) do if i ~= "wpn_fps_sho_browning_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_b_reinforced"][i] = false end end end }) 
end 
T_1e575584ca13fd78 = T_1e575584ca13fd78 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_1e575584ca13fd78__FMenu", name_id = "Loc_ee980494d038377e", inject_menu = "T_2881ddc849d20420__Menu", class = T_1e575584ca13fd78}) 
function T_1e575584ca13fd78:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["Invisible"] or false 
	self:Toggle({ name = "T_4070ca5ed963758d", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["Forced"] or false 
	self:Toggle({ name = "T_675072b8f467155b", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["wpn_fps_sho_browning_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["wpn_fps_sho_browning_s_standard"] or false 
	self:Toggle({ name = "T_1102d82bf32e14ca", text = "Loc_3d46e8bbeb67f851", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["wpn_fps_sho_browning_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["wpn_fps_sho_browning_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["wpn_fps_sho_browning_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]["wpn_fps_sho_browning_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"]) do if i ~= "wpn_fps_sho_browning_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_s_grip"][i] = false end end end }) 
end 
T_728115169208512c = T_728115169208512c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_728115169208512c__FMenu", name_id = "Loc_3c9053a3eac09f8d", inject_menu = "T_2881ddc849d20420__Menu", class = T_728115169208512c}) 
function T_728115169208512c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]["Invisible"] or false 
	self:Toggle({ name = "T_4475d1dcdaebc386", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]["Forced"] or false 
	self:Toggle({ name = "T_5d9808642ce2f75d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_browning_pad_big"][i] = false end end end }) 
end 
