WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_4a90a3c0561667c2 = T_4a90a3c0561667c2 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_4a90a3c0561667c2__Menu", name_id = "bm_w_c96", inject_menu = "WACApplyMyMenuMenu", class = T_4a90a3c0561667c2}) 
T_b769b00f81d4542a = T_b769b00f81d4542a or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b769b00f81d4542a__FMenu", name_id = "Loc_2a4b2289e91bc1ae", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_b769b00f81d4542a}) 
function T_b769b00f81d4542a:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_6dab46387a5eeecd", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_22653774172781f3", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["wpn_fps_pis_c96_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["wpn_fps_pis_c96_b_long"] or false 
	self:Toggle({ name = "T_2eacd3c79acb1c8c", text = "Loc_eb4a9aa995159585", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["wpn_fps_pis_c96_b_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["wpn_fps_pis_c96_b_long"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["wpn_fps_pis_c96_b_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["wpn_fps_pis_c96_b_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]) do if i ~= "wpn_fps_pis_c96_b_long" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["wpn_fps_pis_c96_b_long_finned"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["wpn_fps_pis_c96_b_long_finned"] or false 
	self:Toggle({ name = "T_1a524d37c90ea118", text = "Loc_3c1b2458c4b6e2c4", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["wpn_fps_pis_c96_b_long_finned"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["wpn_fps_pis_c96_b_long_finned"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["wpn_fps_pis_c96_b_long_finned"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]["wpn_fps_pis_c96_b_long_finned"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"]) do if i ~= "wpn_fps_pis_c96_b_long_finned" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_standard"][i] = false end end end }) 
end 
T_33c40a717327755c = T_33c40a717327755c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_33c40a717327755c__FMenu", name_id = "Loc_67e0272a6fc2f95f", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_33c40a717327755c}) 
function T_33c40a717327755c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_760449fec8d6847e", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_346fce6897e40ac3", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_body_standard"][i] = false end end end }) 
end 
T_aa9ab89d8ba4cea6 = T_aa9ab89d8ba4cea6 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_aa9ab89d8ba4cea6__FMenu", name_id = "Loc_68f58c86d0e406ff", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_aa9ab89d8ba4cea6}) 
function T_aa9ab89d8ba4cea6:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_8e3ca4e1d110b323", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]["Forced"] or false 
	self:Toggle({ name = "T_66ed961d742cc1ee", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_g_standard"][i] = false end end end }) 
end 
T_9521014d2da22839 = T_9521014d2da22839 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_9521014d2da22839__FMenu", name_id = "Loc_92bf1baf728dcab1", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_9521014d2da22839}) 
function T_9521014d2da22839:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_558b1499b899d2b7", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_2b5162a0245e10fa", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["wpn_fps_pis_c96_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["wpn_fps_pis_c96_m_long"] or false 
	self:Toggle({ name = "T_d58fe86176eac8a1", text = "Loc_aee70a95f6ad5d10", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["wpn_fps_pis_c96_m_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["wpn_fps_pis_c96_m_long"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["wpn_fps_pis_c96_m_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["wpn_fps_pis_c96_m_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]) do if i ~= "wpn_fps_pis_c96_m_long" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["wpn_fps_pis_c96_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["wpn_fps_pis_c96_m_extended"] or false 
	self:Toggle({ name = "T_b86861f2c9ba1d89", text = "Loc_f5e7f41a7f63f879", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["wpn_fps_pis_c96_m_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["wpn_fps_pis_c96_m_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["wpn_fps_pis_c96_m_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]["wpn_fps_pis_c96_m_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"]) do if i ~= "wpn_fps_pis_c96_m_extended" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_standard"][i] = false end end end }) 
end 
T_306e2db0a77f695f = T_306e2db0a77f695f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_306e2db0a77f695f__FMenu", name_id = "Loc_88c662f97875a4c3", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_306e2db0a77f695f}) 
function T_306e2db0a77f695f:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_c4f3c2ad44589b17", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]["Forced"] or false 
	self:Toggle({ name = "T_b54109423c144f37", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bullets_standard"][i] = false end end end }) 
end 
T_4c4e77fad4fa0d51 = T_4c4e77fad4fa0d51 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_4c4e77fad4fa0d51__FMenu", name_id = "Loc_86b12b3c6d8b84b8", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_4c4e77fad4fa0d51}) 
function T_4c4e77fad4fa0d51:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_6fd5223d8a11b86f", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]["Forced"] or false 
	self:Toggle({ name = "T_9a0e62b258f3a10b", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_strip_standard"][i] = false end end end }) 
end 
T_093d3a14a19d01da = T_093d3a14a19d01da or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_093d3a14a19d01da__FMenu", name_id = "Loc_5f57dfb8c20a0aa4", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_093d3a14a19d01da}) 
function T_093d3a14a19d01da:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_3da1e7e2d51c1e06", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]["Forced"] or false 
	self:Toggle({ name = "T_a40700105d590ad1", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_bolt_standard"][i] = false end end end }) 
end 
T_e547aa7479e7b14e = T_e547aa7479e7b14e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_e547aa7479e7b14e__FMenu", name_id = "Loc_0ba5a4350a8e7c2b", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_e547aa7479e7b14e}) 
function T_e547aa7479e7b14e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_44dc2310d9e1dbc9", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]["Forced"] or false 
	self:Toggle({ name = "T_beb078b89752503e", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_hammer_standard"][i] = false end end end }) 
end 
T_5428d974bf9e7808 = T_5428d974bf9e7808 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_5428d974bf9e7808__FMenu", name_id = "Loc_eb4a9aa995159585", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_5428d974bf9e7808}) 
function T_5428d974bf9e7808:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["Invisible"] or false 
	self:Toggle({ name = "T_51e08d7b3367d390", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["Forced"] or false 
	self:Toggle({ name = "T_eda3995a0cf90fbc", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["wpn_fps_pis_c96_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["wpn_fps_pis_c96_b_standard"] or false 
	self:Toggle({ name = "T_4a6121e2a1cd9524", text = "Loc_2a4b2289e91bc1ae", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["wpn_fps_pis_c96_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["wpn_fps_pis_c96_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["wpn_fps_pis_c96_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["wpn_fps_pis_c96_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]) do if i ~= "wpn_fps_pis_c96_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["wpn_fps_pis_c96_b_long_finned"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["wpn_fps_pis_c96_b_long_finned"] or false 
	self:Toggle({ name = "T_6a8c83862c3d1082", text = "Loc_3c1b2458c4b6e2c4", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["wpn_fps_pis_c96_b_long_finned"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["wpn_fps_pis_c96_b_long_finned"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["wpn_fps_pis_c96_b_long_finned"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]["wpn_fps_pis_c96_b_long_finned"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"]) do if i ~= "wpn_fps_pis_c96_b_long_finned" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long"][i] = false end end end }) 
end 
T_5c0c6599bb16d46e = T_5c0c6599bb16d46e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_5c0c6599bb16d46e__FMenu", name_id = "Loc_3c1b2458c4b6e2c4", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_5c0c6599bb16d46e}) 
function T_5c0c6599bb16d46e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["Invisible"] or false 
	self:Toggle({ name = "T_84260d1db3e36138", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["Forced"] or false 
	self:Toggle({ name = "T_c0ad05237023a854", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["wpn_fps_pis_c96_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["wpn_fps_pis_c96_b_standard"] or false 
	self:Toggle({ name = "T_2fa575bcfd95ecf4", text = "Loc_2a4b2289e91bc1ae", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["wpn_fps_pis_c96_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["wpn_fps_pis_c96_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["wpn_fps_pis_c96_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["wpn_fps_pis_c96_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]) do if i ~= "wpn_fps_pis_c96_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["wpn_fps_pis_c96_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["wpn_fps_pis_c96_b_long"] or false 
	self:Toggle({ name = "T_80d7782f979173bf", text = "Loc_eb4a9aa995159585", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["wpn_fps_pis_c96_b_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["wpn_fps_pis_c96_b_long"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["wpn_fps_pis_c96_b_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]["wpn_fps_pis_c96_b_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"]) do if i ~= "wpn_fps_pis_c96_b_long" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_b_long_finned"][i] = false end end end }) 
end 
T_81f0378dc8144c4c = T_81f0378dc8144c4c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_81f0378dc8144c4c__FMenu", name_id = "Loc_aee70a95f6ad5d10", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_81f0378dc8144c4c}) 
function T_81f0378dc8144c4c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["Invisible"] or false 
	self:Toggle({ name = "T_f9737ac32b0e6bec", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["Forced"] or false 
	self:Toggle({ name = "T_752310a8c069ad87", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["wpn_fps_pis_c96_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["wpn_fps_pis_c96_m_standard"] or false 
	self:Toggle({ name = "T_1697de949472e81d", text = "Loc_92bf1baf728dcab1", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["wpn_fps_pis_c96_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["wpn_fps_pis_c96_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["wpn_fps_pis_c96_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["wpn_fps_pis_c96_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]) do if i ~= "wpn_fps_pis_c96_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["wpn_fps_pis_c96_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["wpn_fps_pis_c96_m_extended"] or false 
	self:Toggle({ name = "T_b5cce40a98bd4069", text = "Loc_f5e7f41a7f63f879", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["wpn_fps_pis_c96_m_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["wpn_fps_pis_c96_m_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["wpn_fps_pis_c96_m_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]["wpn_fps_pis_c96_m_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"]) do if i ~= "wpn_fps_pis_c96_m_extended" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_long"][i] = false end end end }) 
end 
T_66608f386591f98c = T_66608f386591f98c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_66608f386591f98c__FMenu", name_id = "Loc_f5e7f41a7f63f879", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_66608f386591f98c}) 
function T_66608f386591f98c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["Invisible"] or false 
	self:Toggle({ name = "T_177ee718325a6599", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["Forced"] or false 
	self:Toggle({ name = "T_98e06ac902ab78e3", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["wpn_fps_pis_c96_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["wpn_fps_pis_c96_m_standard"] or false 
	self:Toggle({ name = "T_3c4fcd35d934a93b", text = "Loc_92bf1baf728dcab1", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["wpn_fps_pis_c96_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["wpn_fps_pis_c96_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["wpn_fps_pis_c96_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["wpn_fps_pis_c96_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]) do if i ~= "wpn_fps_pis_c96_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["wpn_fps_pis_c96_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["wpn_fps_pis_c96_m_long"] or false 
	self:Toggle({ name = "T_e9b5e254bb7074ca", text = "Loc_aee70a95f6ad5d10", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["wpn_fps_pis_c96_m_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["wpn_fps_pis_c96_m_long"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["wpn_fps_pis_c96_m_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]["wpn_fps_pis_c96_m_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"]) do if i ~= "wpn_fps_pis_c96_m_long" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_m_extended"][i] = false end end end }) 
end 
T_85b72807a36d78ee = T_85b72807a36d78ee or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_85b72807a36d78ee__FMenu", name_id = "Loc_f54f4d534e6ca343", inject_menu = "T_4a90a3c0561667c2__Menu", class = T_85b72807a36d78ee}) 
function T_85b72807a36d78ee:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]["Invisible"] or false 
	self:Toggle({ name = "T_4debf4bc5ece9105", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]["Forced"] or false 
	self:Toggle({ name = "T_6a9cb9fd39480e03", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_c96_s_wooden"][i] = false end end end }) 
end 
