WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_23206bc19e54f957 = T_23206bc19e54f957 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_23206bc19e54f957__Menu", name_id = "bm_w_dp28", inject_menu = "WACApplyMyMenuMenu", class = T_23206bc19e54f957}) 
T_4607a61d2c6502b8 = T_4607a61d2c6502b8 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_4607a61d2c6502b8__FMenu", name_id = "Loc_8f114cef244f19a5", inject_menu = "T_23206bc19e54f957__Menu", class = T_4607a61d2c6502b8}) 
function T_4607a61d2c6502b8:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_4dc0c11c6a9209f3", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_029e2c4533ca3d05", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["wpn_fps_lmg_dp28_b_coned"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["wpn_fps_lmg_dp28_b_coned"] or false 
	self:Toggle({ name = "T_0d4f228ec0231fd2", text = "Loc_64c51a697fe412b6", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["wpn_fps_lmg_dp28_b_coned"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["wpn_fps_lmg_dp28_b_coned"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["wpn_fps_lmg_dp28_b_coned"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]["wpn_fps_lmg_dp28_b_coned"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"]) do if i ~= "wpn_fps_lmg_dp28_b_coned" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_standard"][i] = false end end end }) 
end 
T_e1f436903beddaf0 = T_e1f436903beddaf0 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_e1f436903beddaf0__FMenu", name_id = "Loc_03bc4b5116aa2834", inject_menu = "T_23206bc19e54f957__Menu", class = T_e1f436903beddaf0}) 
function T_e1f436903beddaf0:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_b27103a8aed08800", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_4c292c20b0b97618", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_s_standard"] or false 
	self:Toggle({ name = "T_c746782cf9402e3a", text = "Loc_ea600ab696336f81", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]) do if i ~= "wpn_fps_lmg_dp28_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_g_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_g_standard"] or false 
	self:Toggle({ name = "T_d493a13a22d72601", text = "Loc_653fe185f6a7de32", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_g_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_g_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_g_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_g_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]) do if i ~= "wpn_fps_lmg_dp28_g_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_s_light"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_s_light"] or false 
	self:Toggle({ name = "T_e1197f17f089e75f", text = "Loc_41f9ad1d21a1e108", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_s_light"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_s_light"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_s_light"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]["wpn_fps_lmg_dp28_s_light"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"]) do if i ~= "wpn_fps_lmg_dp28_s_light" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_body_standard"][i] = false end end end }) 
end 
T_9f3f8e6ccf1dedd2 = T_9f3f8e6ccf1dedd2 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_9f3f8e6ccf1dedd2__FMenu", name_id = "Loc_195c48b24c6a6c47", inject_menu = "T_23206bc19e54f957__Menu", class = T_9f3f8e6ccf1dedd2}) 
function T_9f3f8e6ccf1dedd2:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_aac6eee3e9259608", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_8563f3ad8487f06d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_dh_standard"][i] = false end end end }) 
end 
T_e5cee7930154cc42 = T_e5cee7930154cc42 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_e5cee7930154cc42__FMenu", name_id = "Loc_b4b54b92aaf53f55", inject_menu = "T_23206bc19e54f957__Menu", class = T_e5cee7930154cc42}) 
function T_e5cee7930154cc42:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]["Invisible"] or false 
	self:Toggle({ name = "T_cf1cc88c16e528ae", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]["Forced"] or false 
	self:Toggle({ name = "T_dc8c5b1886cbafc9", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_strap"][i] = false end end end }) 
end 
T_009837821d457c78 = T_009837821d457c78 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_009837821d457c78__FMenu", name_id = "Loc_295a51285b3ee0a6", inject_menu = "T_23206bc19e54f957__Menu", class = T_009837821d457c78}) 
function T_009837821d457c78:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["Invisible"] or false 
	self:Toggle({ name = "T_82fc90de7ef5df70", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["Forced"] or false 
	self:Toggle({ name = "T_a3444b296a6a135f", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_standard"] or false 
	self:Toggle({ name = "T_ae62ee072625c627", text = "Loc_e9183e468a457978", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]) do if i ~= "wpn_fps_lmg_dp28_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_casing_ext"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_casing_ext"] or false 
	self:Toggle({ name = "T_db5a288108499e88", text = "Loc_d93a9f2b6b821b5a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_casing_ext"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_casing_ext"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_casing_ext"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_casing_ext"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]) do if i ~= "wpn_fps_lmg_dp28_m_casing_ext" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_extended"] or false 
	self:Toggle({ name = "T_b03ab8d45b2ad0cb", text = "Loc_c2a2b41d0fcc6d3e", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]["wpn_fps_lmg_dp28_m_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"]) do if i ~= "wpn_fps_lmg_dp28_m_extended" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing"][i] = false end end end }) 
end 
T_394f088788b0aec1 = T_394f088788b0aec1 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_394f088788b0aec1__FMenu", name_id = "Loc_e9183e468a457978", inject_menu = "T_23206bc19e54f957__Menu", class = T_394f088788b0aec1}) 
function T_394f088788b0aec1:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_aee1426394e91710", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_2c6a975467b46132", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_casing"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_casing"] or false 
	self:Toggle({ name = "T_29fe9de1087ea3db", text = "Loc_295a51285b3ee0a6", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_casing"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_casing"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_casing"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_casing"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]) do if i ~= "wpn_fps_lmg_dp28_m_casing" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_casing_ext"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_casing_ext"] or false 
	self:Toggle({ name = "T_2cfdaccf30d5a470", text = "Loc_d93a9f2b6b821b5a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_casing_ext"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_casing_ext"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_casing_ext"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_casing_ext"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]) do if i ~= "wpn_fps_lmg_dp28_m_casing_ext" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_extended"] or false 
	self:Toggle({ name = "T_3c42df3836f52af4", text = "Loc_c2a2b41d0fcc6d3e", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]["wpn_fps_lmg_dp28_m_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"]) do if i ~= "wpn_fps_lmg_dp28_m_extended" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_standard"][i] = false end end end }) 
end 
T_ab8f92328427f4d0 = T_ab8f92328427f4d0 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_ab8f92328427f4d0__FMenu", name_id = "Loc_93a03df6b6026764", inject_menu = "T_23206bc19e54f957__Menu", class = T_ab8f92328427f4d0}) 
function T_ab8f92328427f4d0:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_a8321df211f954ad", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["Forced"] or false 
	self:Toggle({ name = "T_cc94280683b3cfd4", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["wpn_fps_lmg_dp28_o_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["wpn_fps_lmg_dp28_o_extended"] or false 
	self:Toggle({ name = "T_7982356377638d69", text = "Loc_36ce916e71883f82", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["wpn_fps_lmg_dp28_o_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["wpn_fps_lmg_dp28_o_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["wpn_fps_lmg_dp28_o_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]["wpn_fps_lmg_dp28_o_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"]) do if i ~= "wpn_fps_lmg_dp28_o_extended" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_standard"][i] = false end end end }) 
end 
T_2b90e48991fbfa6b = T_2b90e48991fbfa6b or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_2b90e48991fbfa6b__FMenu", name_id = "Loc_ea600ab696336f81", inject_menu = "T_23206bc19e54f957__Menu", class = T_2b90e48991fbfa6b}) 
function T_2b90e48991fbfa6b:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_0cd843ce6224e908", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["Forced"] or false 
	self:Toggle({ name = "T_e1454533c4ed1eea", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_body_standard"] or false 
	self:Toggle({ name = "T_881344e95f3dbc56", text = "Loc_03bc4b5116aa2834", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]) do if i ~= "wpn_fps_lmg_dp28_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_g_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_g_standard"] or false 
	self:Toggle({ name = "T_57b4dc0f0a1e1d44", text = "Loc_653fe185f6a7de32", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_g_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_g_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_g_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_g_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]) do if i ~= "wpn_fps_lmg_dp28_g_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_s_light"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_s_light"] or false 
	self:Toggle({ name = "T_eae98b8fa0bf0508", text = "Loc_41f9ad1d21a1e108", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_s_light"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_s_light"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_s_light"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]["wpn_fps_lmg_dp28_s_light"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"]) do if i ~= "wpn_fps_lmg_dp28_s_light" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_standard"][i] = false end end end }) 
end 
T_12d88ad2a1998db6 = T_12d88ad2a1998db6 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_12d88ad2a1998db6__FMenu", name_id = "Loc_0c213107b50bfcc8", inject_menu = "T_23206bc19e54f957__Menu", class = T_12d88ad2a1998db6}) 
function T_12d88ad2a1998db6:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]["Invisible"] or false 
	self:Toggle({ name = "T_5bfd384205eaf06e", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]["Forced"] or false 
	self:Toggle({ name = "T_79c53441463c6493", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_trigger"][i] = false end end end }) 
end 
T_afbe9fd1e95f7d2f = T_afbe9fd1e95f7d2f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_afbe9fd1e95f7d2f__FMenu", name_id = "Loc_64c51a697fe412b6", inject_menu = "T_23206bc19e54f957__Menu", class = T_afbe9fd1e95f7d2f}) 
function T_afbe9fd1e95f7d2f:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["Invisible"] or false 
	self:Toggle({ name = "T_fa6671d16b1bf112", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["Forced"] or false 
	self:Toggle({ name = "T_611d6ce4b1a6eb0f", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["wpn_fps_lmg_dp28_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["wpn_fps_lmg_dp28_b_standard"] or false 
	self:Toggle({ name = "T_d18fb350a798b823", text = "Loc_8f114cef244f19a5", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["wpn_fps_lmg_dp28_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["wpn_fps_lmg_dp28_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["wpn_fps_lmg_dp28_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]["wpn_fps_lmg_dp28_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"]) do if i ~= "wpn_fps_lmg_dp28_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_b_coned"][i] = false end end end }) 
end 
T_5b5556cd52e0ec21 = T_5b5556cd52e0ec21 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_5b5556cd52e0ec21__FMenu", name_id = "Loc_756caa4996a950ac", inject_menu = "T_23206bc19e54f957__Menu", class = T_5b5556cd52e0ec21}) 
function T_5b5556cd52e0ec21:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]["Invisible"] or false 
	self:Toggle({ name = "T_132968f62aaf195a", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]["Forced"] or false 
	self:Toggle({ name = "T_b6a0763e9b8ce9a7", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_bipod"][i] = false end end end }) 
end 
T_acfae12d246a7e42 = T_acfae12d246a7e42 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_acfae12d246a7e42__FMenu", name_id = "Loc_653fe185f6a7de32", inject_menu = "T_23206bc19e54f957__Menu", class = T_acfae12d246a7e42}) 
function T_acfae12d246a7e42:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_1475b70266533c57", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["Forced"] or false 
	self:Toggle({ name = "T_ed608f0463d9a9ac", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_body_standard"] or false 
	self:Toggle({ name = "T_574f786dd153c521", text = "Loc_03bc4b5116aa2834", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]) do if i ~= "wpn_fps_lmg_dp28_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_s_standard"] or false 
	self:Toggle({ name = "T_0e2cae6ba2ca2345", text = "Loc_ea600ab696336f81", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]) do if i ~= "wpn_fps_lmg_dp28_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_s_light"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_s_light"] or false 
	self:Toggle({ name = "T_5e173dbeba5b102d", text = "Loc_41f9ad1d21a1e108", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_s_light"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_s_light"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_s_light"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]["wpn_fps_lmg_dp28_s_light"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"]) do if i ~= "wpn_fps_lmg_dp28_s_light" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_g_standard"][i] = false end end end }) 
end 
T_77b401bccec573b4 = T_77b401bccec573b4 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_77b401bccec573b4__FMenu", name_id = "Loc_d93a9f2b6b821b5a", inject_menu = "T_23206bc19e54f957__Menu", class = T_77b401bccec573b4}) 
function T_77b401bccec573b4:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["Invisible"] or false 
	self:Toggle({ name = "T_53a900e08f604437", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["Forced"] or false 
	self:Toggle({ name = "T_67beed8dad07f15e", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_casing"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_casing"] or false 
	self:Toggle({ name = "T_1dcf9ba6cc79ca55", text = "Loc_295a51285b3ee0a6", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_casing"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_casing"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_casing"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_casing"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]) do if i ~= "wpn_fps_lmg_dp28_m_casing" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_standard"] or false 
	self:Toggle({ name = "T_65e0a8cb0fe99b1c", text = "Loc_e9183e468a457978", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]) do if i ~= "wpn_fps_lmg_dp28_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_extended"] or false 
	self:Toggle({ name = "T_e84d79a0e5361699", text = "Loc_c2a2b41d0fcc6d3e", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]["wpn_fps_lmg_dp28_m_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"]) do if i ~= "wpn_fps_lmg_dp28_m_extended" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_casing_ext"][i] = false end end end }) 
end 
T_e725d2823662cbdb = T_e725d2823662cbdb or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_e725d2823662cbdb__FMenu", name_id = "Loc_c2a2b41d0fcc6d3e", inject_menu = "T_23206bc19e54f957__Menu", class = T_e725d2823662cbdb}) 
function T_e725d2823662cbdb:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["Invisible"] or false 
	self:Toggle({ name = "T_af242a11ed2d322c", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["Forced"] or false 
	self:Toggle({ name = "T_d4e1f6119879b01c", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_casing"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_casing"] or false 
	self:Toggle({ name = "T_c2e0f6d9d4bde024", text = "Loc_295a51285b3ee0a6", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_casing"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_casing"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_casing"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_casing"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]) do if i ~= "wpn_fps_lmg_dp28_m_casing" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_standard"] or false 
	self:Toggle({ name = "T_6880ffe00a60e978", text = "Loc_e9183e468a457978", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]) do if i ~= "wpn_fps_lmg_dp28_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_casing_ext"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_casing_ext"] or false 
	self:Toggle({ name = "T_6d249971de32b2ca", text = "Loc_d93a9f2b6b821b5a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_casing_ext"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_casing_ext"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_casing_ext"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]["wpn_fps_lmg_dp28_m_casing_ext"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"]) do if i ~= "wpn_fps_lmg_dp28_m_casing_ext" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_m_extended"][i] = false end end end }) 
end 
T_0b4cb7544a679d50 = T_0b4cb7544a679d50 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_0b4cb7544a679d50__FMenu", name_id = "Loc_36ce916e71883f82", inject_menu = "T_23206bc19e54f957__Menu", class = T_0b4cb7544a679d50}) 
function T_0b4cb7544a679d50:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["Invisible"] or false 
	self:Toggle({ name = "T_96f643f4f66e6581", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["Forced"] or false 
	self:Toggle({ name = "T_edb265dc3a2b46ed", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["wpn_fps_lmg_dp28_o_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["wpn_fps_lmg_dp28_o_standard"] or false 
	self:Toggle({ name = "T_3f0d81366945bd6f", text = "Loc_93a03df6b6026764", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["wpn_fps_lmg_dp28_o_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["wpn_fps_lmg_dp28_o_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["wpn_fps_lmg_dp28_o_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]["wpn_fps_lmg_dp28_o_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"]) do if i ~= "wpn_fps_lmg_dp28_o_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_o_extended"][i] = false end end end }) 
end 
T_e2aaaff34eb7474c = T_e2aaaff34eb7474c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_e2aaaff34eb7474c__FMenu", name_id = "Loc_41f9ad1d21a1e108", inject_menu = "T_23206bc19e54f957__Menu", class = T_e2aaaff34eb7474c}) 
function T_e2aaaff34eb7474c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["Invisible"] or false 
	self:Toggle({ name = "T_860331ad2a340acf", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["Forced"] or false 
	self:Toggle({ name = "T_0671041f9c27e8c3", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_body_standard"] or false 
	self:Toggle({ name = "T_3337add0da5ce13e", text = "Loc_03bc4b5116aa2834", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]) do if i ~= "wpn_fps_lmg_dp28_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_s_standard"] or false 
	self:Toggle({ name = "T_abbaa9c9cb538f7f", text = "Loc_ea600ab696336f81", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]) do if i ~= "wpn_fps_lmg_dp28_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_g_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_g_standard"] or false 
	self:Toggle({ name = "T_f9b5e6de4045519f", text = "Loc_653fe185f6a7de32", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_g_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_g_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_g_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]["wpn_fps_lmg_dp28_g_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"]) do if i ~= "wpn_fps_lmg_dp28_g_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_dp28_s_light"][i] = false end end end }) 
end 
