WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_5cce89297effe6fb = T_5cce89297effe6fb or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_5cce89297effe6fb__Menu", name_id = "bm_w_garand", inject_menu = "WACApplyMyMenuMenu", class = T_5cce89297effe6fb}) 
T_fcc078f1f1a0aa1e = T_fcc078f1f1a0aa1e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_fcc078f1f1a0aa1e__FMenu", name_id = "Loc_6f119576974627ad", inject_menu = "T_5cce89297effe6fb__Menu", class = T_fcc078f1f1a0aa1e}) 
function T_fcc078f1f1a0aa1e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_0ca33eea96afaeea", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_7385b949d5da55df", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["wpn_fps_ass_garand_m_bar_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["wpn_fps_ass_garand_m_bar_standard"] or false 
	self:Toggle({ name = "T_96d03adca10f9e14", text = "Loc_983c95a3c66b1142", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["wpn_fps_ass_garand_m_bar_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["wpn_fps_ass_garand_m_bar_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["wpn_fps_ass_garand_m_bar_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["wpn_fps_ass_garand_m_bar_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]) do if i ~= "wpn_fps_ass_garand_m_bar_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["wpn_fps_ass_garand_m_bar_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["wpn_fps_ass_garand_m_bar_extended"] or false 
	self:Toggle({ name = "T_a85b493f887e9287", text = "Loc_ae62929a4c788fe0", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["wpn_fps_ass_garand_m_bar_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["wpn_fps_ass_garand_m_bar_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["wpn_fps_ass_garand_m_bar_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]["wpn_fps_ass_garand_m_bar_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"]) do if i ~= "wpn_fps_ass_garand_m_bar_extended" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_body_standard"][i] = false end end end }) 
end 
T_491a1144033d7688 = T_491a1144033d7688 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_491a1144033d7688__FMenu", name_id = "Loc_97c6d8217cb932a1", inject_menu = "T_5cce89297effe6fb__Menu", class = T_491a1144033d7688}) 
function T_491a1144033d7688:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_560e2aa6d62d9d6b", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_cd41d7f91c2660bf", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["wpn_fps_ass_garand_b_tanker"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["wpn_fps_ass_garand_b_tanker"] or false 
	self:Toggle({ name = "T_235de48915c4e281", text = "Loc_9b8e140ca9269277", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["wpn_fps_ass_garand_b_tanker"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["wpn_fps_ass_garand_b_tanker"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["wpn_fps_ass_garand_b_tanker"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]["wpn_fps_ass_garand_b_tanker"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"]) do if i ~= "wpn_fps_ass_garand_b_tanker" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_standard"][i] = false end end end }) 
end 
T_16f48bde79652da1 = T_16f48bde79652da1 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_16f48bde79652da1__FMenu", name_id = "Loc_1ed57ed230f488cf", inject_menu = "T_5cce89297effe6fb__Menu", class = T_16f48bde79652da1}) 
function T_16f48bde79652da1:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_be12a0ed23fbba2a", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_44615ff5c34d5b01", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"][i] = false end end end }) 
end 
T_eb55ba23d829be4b = T_eb55ba23d829be4b or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_eb55ba23d829be4b__FMenu", name_id = "Loc_9392415ded831f5e", inject_menu = "T_5cce89297effe6fb__Menu", class = T_eb55ba23d829be4b}) 
function T_eb55ba23d829be4b:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_46c865a6b7ee93e0", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]["Forced"] or false 
	self:Toggle({ name = "T_b7f3a7bdadb851d7", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_bolt_standard"][i] = false end end end }) 
end 
T_6c531d3ff4db9e92 = T_6c531d3ff4db9e92 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_6c531d3ff4db9e92__FMenu", name_id = "Loc_c7cb80da00c3edc2", inject_menu = "T_5cce89297effe6fb__Menu", class = T_6c531d3ff4db9e92}) 
function T_6c531d3ff4db9e92:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_327ecd14c6d0fbe0", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_000f337bdb7e5e0a", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_dh_standard"][i] = false end end end }) 
end 
T_4e39ece29672435c = T_4e39ece29672435c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_4e39ece29672435c__FMenu", name_id = "Loc_dcf69101ee860d6b", inject_menu = "T_5cce89297effe6fb__Menu", class = T_4e39ece29672435c}) 
function T_4e39ece29672435c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]["Invisible"] or false 
	self:Toggle({ name = "T_ed35d10bbc9299b0", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]["Forced"] or false 
	self:Toggle({ name = "T_63e836034d543ea7", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra_swiwel"][i] = false end end end }) 
end 
T_2abf2c2b9a29b6f4 = T_2abf2c2b9a29b6f4 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_2abf2c2b9a29b6f4__FMenu", name_id = "Loc_94d95aa1e67b6103", inject_menu = "T_5cce89297effe6fb__Menu", class = T_2abf2c2b9a29b6f4}) 
function T_2abf2c2b9a29b6f4:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]["Invisible"] or false 
	self:Toggle({ name = "T_ba4df4edaeb266f7", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]["Forced"] or false 
	self:Toggle({ name = "T_e169a43a3eeae7ab", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_extra1_swiwel"][i] = false end end end }) 
end 
T_fa1af23664666e07 = T_fa1af23664666e07 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_fa1af23664666e07__FMenu", name_id = "Loc_4bfd0472ca2008e6", inject_menu = "T_5cce89297effe6fb__Menu", class = T_fa1af23664666e07}) 
function T_fa1af23664666e07:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_46b74aaea77be00d", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["Forced"] or false 
	self:Toggle({ name = "T_a192c3c6312e39fb", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["wpn_fps_ass_garand_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["wpn_fps_ass_garand_s_cheek_rest"] or false 
	self:Toggle({ name = "T_f07b598d9012bcd5", text = "Loc_44b1640ed3315118", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["wpn_fps_ass_garand_s_cheek_rest"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["wpn_fps_ass_garand_s_cheek_rest"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["wpn_fps_ass_garand_s_cheek_rest"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["wpn_fps_ass_garand_s_cheek_rest"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]) do if i ~= "wpn_fps_ass_garand_s_cheek_rest" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["wpn_fps_ass_garand_s_folding"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["wpn_fps_ass_garand_s_folding"] or false 
	self:Toggle({ name = "T_a72b54e9b943f3b2", text = "Loc_ea210559ae5f2a8b", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["wpn_fps_ass_garand_s_folding"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["wpn_fps_ass_garand_s_folding"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["wpn_fps_ass_garand_s_folding"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]["wpn_fps_ass_garand_s_folding"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"]) do if i ~= "wpn_fps_ass_garand_s_folding" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_standard"][i] = false end end end }) 
end 
T_a590a9dfe3c74766 = T_a590a9dfe3c74766 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_a590a9dfe3c74766__FMenu", name_id = "Loc_5106ec00c9df9b67", inject_menu = "T_5cce89297effe6fb__Menu", class = T_a590a9dfe3c74766}) 
function T_a590a9dfe3c74766:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_cdd333656a841a14", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]["Forced"] or false 
	self:Toggle({ name = "T_ce8d28e6624332d4", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_strip_standard"][i] = false end end end }) 
end 
T_6c4f7b17f642ee6a = T_6c4f7b17f642ee6a or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_6c4f7b17f642ee6a__FMenu", name_id = "Loc_9caab45cb9755af0", inject_menu = "T_5cce89297effe6fb__Menu", class = T_6c4f7b17f642ee6a}) 
function T_6c4f7b17f642ee6a:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]["Invisible"] or false 
	self:Toggle({ name = "T_c3606b30f0cb8675", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]["Forced"] or false 
	self:Toggle({ name = "T_21f5bf1d8e8a1b93", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_ns_conical"][i] = false end end end }) 
end 
T_c527b7aca59f440e = T_c527b7aca59f440e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_c527b7aca59f440e__FMenu", name_id = "Loc_9b8e140ca9269277", inject_menu = "T_5cce89297effe6fb__Menu", class = T_c527b7aca59f440e}) 
function T_c527b7aca59f440e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["Invisible"] or false 
	self:Toggle({ name = "T_bede0743b88a639e", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["Forced"] or false 
	self:Toggle({ name = "T_73ce376b39674635", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["wpn_fps_ass_garand_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["wpn_fps_ass_garand_b_standard"] or false 
	self:Toggle({ name = "T_81a7ee9e1a5f0201", text = "Loc_97c6d8217cb932a1", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["wpn_fps_ass_garand_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["wpn_fps_ass_garand_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["wpn_fps_ass_garand_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]["wpn_fps_ass_garand_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"]) do if i ~= "wpn_fps_ass_garand_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_b_tanker"][i] = false end end end }) 
end 
T_d0b228303bf194c1 = T_d0b228303bf194c1 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_d0b228303bf194c1__FMenu", name_id = "Loc_44b1640ed3315118", inject_menu = "T_5cce89297effe6fb__Menu", class = T_d0b228303bf194c1}) 
function T_d0b228303bf194c1:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Invisible"] or false 
	self:Toggle({ name = "T_7962d4c200b21461", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Forced"] or false 
	self:Toggle({ name = "T_34175e74fea80801", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_s_standard"] or false 
	self:Toggle({ name = "T_445556f7dc8494aa", text = "Loc_4bfd0472ca2008e6", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]) do if i ~= "wpn_fps_ass_garand_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_s_folding"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_s_folding"] or false 
	self:Toggle({ name = "T_60da264d26047b8b", text = "Loc_ea210559ae5f2a8b", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_s_folding"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_s_folding"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_s_folding"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_s_folding"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]) do if i ~= "wpn_fps_ass_garand_s_folding" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"][i] = false end end end }) 
end 
T_43d8a6f74b526dd1 = T_43d8a6f74b526dd1 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_43d8a6f74b526dd1__FMenu", name_id = "Loc_ea210559ae5f2a8b", inject_menu = "T_5cce89297effe6fb__Menu", class = T_43d8a6f74b526dd1}) 
function T_43d8a6f74b526dd1:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["Invisible"] or false 
	self:Toggle({ name = "T_56e127a6a5ad1434", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["Forced"] or false 
	self:Toggle({ name = "T_1f46c0da59bd05ec", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["wpn_fps_ass_garand_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["wpn_fps_ass_garand_s_standard"] or false 
	self:Toggle({ name = "T_aceb9be12f1874ca", text = "Loc_4bfd0472ca2008e6", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["wpn_fps_ass_garand_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["wpn_fps_ass_garand_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["wpn_fps_ass_garand_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["wpn_fps_ass_garand_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]) do if i ~= "wpn_fps_ass_garand_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["wpn_fps_ass_garand_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["wpn_fps_ass_garand_s_cheek_rest"] or false 
	self:Toggle({ name = "T_a994f25097045dfd", text = "Loc_44b1640ed3315118", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["wpn_fps_ass_garand_s_cheek_rest"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["wpn_fps_ass_garand_s_cheek_rest"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["wpn_fps_ass_garand_s_cheek_rest"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]["wpn_fps_ass_garand_s_cheek_rest"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"]) do if i ~= "wpn_fps_ass_garand_s_cheek_rest" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_folding"][i] = false end end end }) 
end 
T_71d5544a6db49ad9 = T_71d5544a6db49ad9 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_71d5544a6db49ad9__FMenu", name_id = "Loc_983c95a3c66b1142", inject_menu = "T_5cce89297effe6fb__Menu", class = T_71d5544a6db49ad9}) 
function T_71d5544a6db49ad9:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_4f562c7b82b0cd18", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["Forced"] or false 
	self:Toggle({ name = "T_f776df9a79926e61", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["wpn_fps_ass_garand_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["wpn_fps_ass_garand_body_standard"] or false 
	self:Toggle({ name = "T_aa7205b00284d82d", text = "Loc_6f119576974627ad", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["wpn_fps_ass_garand_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["wpn_fps_ass_garand_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["wpn_fps_ass_garand_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["wpn_fps_ass_garand_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]) do if i ~= "wpn_fps_ass_garand_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["wpn_fps_ass_garand_m_bar_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["wpn_fps_ass_garand_m_bar_extended"] or false 
	self:Toggle({ name = "T_8d89c228a8654cf5", text = "Loc_ae62929a4c788fe0", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["wpn_fps_ass_garand_m_bar_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["wpn_fps_ass_garand_m_bar_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["wpn_fps_ass_garand_m_bar_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]["wpn_fps_ass_garand_m_bar_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"]) do if i ~= "wpn_fps_ass_garand_m_bar_extended" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_standard"][i] = false end end end }) 
end 
T_235d03087a6ed75e = T_235d03087a6ed75e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_235d03087a6ed75e__FMenu", name_id = "Loc_ae62929a4c788fe0", inject_menu = "T_5cce89297effe6fb__Menu", class = T_235d03087a6ed75e}) 
function T_235d03087a6ed75e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["Invisible"] or false 
	self:Toggle({ name = "T_c856fdbe24ed2807", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["Forced"] or false 
	self:Toggle({ name = "T_3766ed936ed7488d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["wpn_fps_ass_garand_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["wpn_fps_ass_garand_body_standard"] or false 
	self:Toggle({ name = "T_b15353c97759268b", text = "Loc_6f119576974627ad", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["wpn_fps_ass_garand_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["wpn_fps_ass_garand_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["wpn_fps_ass_garand_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["wpn_fps_ass_garand_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]) do if i ~= "wpn_fps_ass_garand_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["wpn_fps_ass_garand_m_bar_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["wpn_fps_ass_garand_m_bar_standard"] or false 
	self:Toggle({ name = "T_15aba96a0d36d8e5", text = "Loc_983c95a3c66b1142", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["wpn_fps_ass_garand_m_bar_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["wpn_fps_ass_garand_m_bar_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["wpn_fps_ass_garand_m_bar_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]["wpn_fps_ass_garand_m_bar_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"]) do if i ~= "wpn_fps_ass_garand_m_bar_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_bar_extended"][i] = false end end end }) 
end 
