WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_c93a2c785995e967 = T_c93a2c785995e967 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_c93a2c785995e967__Menu", name_id = "bm_w_garand_golden", inject_menu = "WACApplyMyMenuMenu", class = T_c93a2c785995e967}) 
T_5dbce0db357772a8 = T_5dbce0db357772a8 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_5dbce0db357772a8__FMenu", name_id = "Loc_680167cbff961230", inject_menu = "T_c93a2c785995e967__Menu", class = T_5dbce0db357772a8}) 
function T_5dbce0db357772a8:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_cd8fe748530243c7", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_1b835bab6a8dc6d9", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["wpn_fps_ass_garand_golden_m_bar_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["wpn_fps_ass_garand_golden_m_bar_standard"] or false 
	self:Toggle({ name = "T_6bd9861cf648dca4", text = "Loc_eeb342f2a9be926a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["wpn_fps_ass_garand_golden_m_bar_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["wpn_fps_ass_garand_golden_m_bar_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["wpn_fps_ass_garand_golden_m_bar_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["wpn_fps_ass_garand_golden_m_bar_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]) do if i ~= "wpn_fps_ass_garand_golden_m_bar_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["wpn_fps_ass_garand_golden_m_bar_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["wpn_fps_ass_garand_golden_m_bar_extended"] or false 
	self:Toggle({ name = "T_cc97705970e8e4eb", text = "Loc_6f840107d150398a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["wpn_fps_ass_garand_golden_m_bar_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["wpn_fps_ass_garand_golden_m_bar_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["wpn_fps_ass_garand_golden_m_bar_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]["wpn_fps_ass_garand_golden_m_bar_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"]) do if i ~= "wpn_fps_ass_garand_golden_m_bar_extended" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_body_standard"][i] = false end end end }) 
end 
T_00062f8f2434c500 = T_00062f8f2434c500 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_00062f8f2434c500__FMenu", name_id = "Loc_f8df87b31cc00391", inject_menu = "T_c93a2c785995e967__Menu", class = T_00062f8f2434c500}) 
function T_00062f8f2434c500:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_b30798e7bd7f9875", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_5519e36601b14d28", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["wpn_fps_ass_garand_golden_b_tanker"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["wpn_fps_ass_garand_golden_b_tanker"] or false 
	self:Toggle({ name = "T_c276ad8185c1d1e0", text = "Loc_4ad0f8440e1c388e", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["wpn_fps_ass_garand_golden_b_tanker"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["wpn_fps_ass_garand_golden_b_tanker"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["wpn_fps_ass_garand_golden_b_tanker"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]["wpn_fps_ass_garand_golden_b_tanker"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"]) do if i ~= "wpn_fps_ass_garand_golden_b_tanker" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_standard"][i] = false end end end }) 
end 
T_16f48bde79652da1 = T_16f48bde79652da1 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_16f48bde79652da1__FMenu", name_id = "Loc_1ed57ed230f488cf", inject_menu = "T_c93a2c785995e967__Menu", class = T_16f48bde79652da1}) 
function T_16f48bde79652da1:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_be12a0ed23fbba2a", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_44615ff5c34d5b01", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_m_standard"][i] = false end end end }) 
end 
T_d691e44c9b917b58 = T_d691e44c9b917b58 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_d691e44c9b917b58__FMenu", name_id = "Loc_2ac06bb94b8885fc", inject_menu = "T_c93a2c785995e967__Menu", class = T_d691e44c9b917b58}) 
function T_d691e44c9b917b58:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_b7afeb11ba61916a", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]["Forced"] or false 
	self:Toggle({ name = "T_f2cda8330fc1df2d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_bolt_standard"][i] = false end end end }) 
end 
T_8c7a479db3fc0d0f = T_8c7a479db3fc0d0f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_8c7a479db3fc0d0f__FMenu", name_id = "Loc_79a3947f1a898e12", inject_menu = "T_c93a2c785995e967__Menu", class = T_8c7a479db3fc0d0f}) 
function T_8c7a479db3fc0d0f:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_8cb9798c6922c239", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_c8d6f0933f6abaf8", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_dh_standard"][i] = false end end end }) 
end 
T_8af17f2ed421e83f = T_8af17f2ed421e83f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_8af17f2ed421e83f__FMenu", name_id = "Loc_23eb15e6f14e7304", inject_menu = "T_c93a2c785995e967__Menu", class = T_8af17f2ed421e83f}) 
function T_8af17f2ed421e83f:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]["Invisible"] or false 
	self:Toggle({ name = "T_4aff34e9f9f8886a", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]["Forced"] or false 
	self:Toggle({ name = "T_4add789fe1f5ce9c", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra_swiwel"][i] = false end end end }) 
end 
T_dad6bffc55f24ebf = T_dad6bffc55f24ebf or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_dad6bffc55f24ebf__FMenu", name_id = "Loc_0b0d5d71f99a4d3a", inject_menu = "T_c93a2c785995e967__Menu", class = T_dad6bffc55f24ebf}) 
function T_dad6bffc55f24ebf:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]["Invisible"] or false 
	self:Toggle({ name = "T_22a807cd284b279e", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]["Forced"] or false 
	self:Toggle({ name = "T_f6831e933d2d6295", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_extra1_swiwel"][i] = false end end end }) 
end 
T_583c1ed0bcf8311e = T_583c1ed0bcf8311e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_583c1ed0bcf8311e__FMenu", name_id = "Loc_b232038a19f31bd0", inject_menu = "T_c93a2c785995e967__Menu", class = T_583c1ed0bcf8311e}) 
function T_583c1ed0bcf8311e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_541380e3a93ad239", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["Forced"] or false 
	self:Toggle({ name = "T_ae0ea7514a7eff4e", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["wpn_fps_ass_garand_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["wpn_fps_ass_garand_s_cheek_rest"] or false 
	self:Toggle({ name = "T_09e90ed937bb5eff", text = "Loc_44b1640ed3315118", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["wpn_fps_ass_garand_s_cheek_rest"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["wpn_fps_ass_garand_s_cheek_rest"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["wpn_fps_ass_garand_s_cheek_rest"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["wpn_fps_ass_garand_s_cheek_rest"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]) do if i ~= "wpn_fps_ass_garand_s_cheek_rest" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["wpn_fps_ass_garand_golden_s_folding"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["wpn_fps_ass_garand_golden_s_folding"] or false 
	self:Toggle({ name = "T_26cd91eb6ee4ee73", text = "Loc_cf708ed550dfe294", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["wpn_fps_ass_garand_golden_s_folding"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["wpn_fps_ass_garand_golden_s_folding"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["wpn_fps_ass_garand_golden_s_folding"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]["wpn_fps_ass_garand_golden_s_folding"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"]) do if i ~= "wpn_fps_ass_garand_golden_s_folding" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_standard"][i] = false end end end }) 
end 
T_af925a6b05db6912 = T_af925a6b05db6912 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_af925a6b05db6912__FMenu", name_id = "Loc_6c8857883bf9bd56", inject_menu = "T_c93a2c785995e967__Menu", class = T_af925a6b05db6912}) 
function T_af925a6b05db6912:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_582000afc3012d91", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]["Forced"] or false 
	self:Toggle({ name = "T_7532519ff22602d2", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_strip_standard"][i] = false end end end }) 
end 
T_7444d80e394b5d36 = T_7444d80e394b5d36 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_7444d80e394b5d36__FMenu", name_id = "Loc_d12c3aa0430014ed", inject_menu = "T_c93a2c785995e967__Menu", class = T_7444d80e394b5d36}) 
function T_7444d80e394b5d36:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]["Invisible"] or false 
	self:Toggle({ name = "T_7393f149fef4cbe9", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]["Forced"] or false 
	self:Toggle({ name = "T_6e78c74b13754270", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_ns_conical"][i] = false end end end }) 
end 
T_a944c91e2759e826 = T_a944c91e2759e826 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_a944c91e2759e826__FMenu", name_id = "Loc_4ad0f8440e1c388e", inject_menu = "T_c93a2c785995e967__Menu", class = T_a944c91e2759e826}) 
function T_a944c91e2759e826:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["Invisible"] or false 
	self:Toggle({ name = "T_5dcb9f77b378145c", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["Forced"] or false 
	self:Toggle({ name = "T_521435ad6ec5e5f9", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["wpn_fps_ass_garand_golden_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["wpn_fps_ass_garand_golden_b_standard"] or false 
	self:Toggle({ name = "T_52a063eacafa32f3", text = "Loc_f8df87b31cc00391", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["wpn_fps_ass_garand_golden_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["wpn_fps_ass_garand_golden_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["wpn_fps_ass_garand_golden_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]["wpn_fps_ass_garand_golden_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"]) do if i ~= "wpn_fps_ass_garand_golden_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_b_tanker"][i] = false end end end }) 
end 
T_d0b228303bf194c1 = T_d0b228303bf194c1 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_d0b228303bf194c1__FMenu", name_id = "Loc_44b1640ed3315118", inject_menu = "T_c93a2c785995e967__Menu", class = T_d0b228303bf194c1}) 
function T_d0b228303bf194c1:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Invisible"] or false 
	self:Toggle({ name = "T_7962d4c200b21461", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Forced"] or false 
	self:Toggle({ name = "T_34175e74fea80801", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_golden_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_golden_s_standard"] or false 
	self:Toggle({ name = "T_f551b9cb964dfe0f", text = "Loc_b232038a19f31bd0", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_golden_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_golden_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_golden_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_golden_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]) do if i ~= "wpn_fps_ass_garand_golden_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_golden_s_folding"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_golden_s_folding"] or false 
	self:Toggle({ name = "T_e962979304b7d16e", text = "Loc_cf708ed550dfe294", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_golden_s_folding"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_golden_s_folding"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_golden_s_folding"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]["wpn_fps_ass_garand_golden_s_folding"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"]) do if i ~= "wpn_fps_ass_garand_golden_s_folding" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_s_cheek_rest"][i] = false end end end }) 
end 
T_d9881c2cbc5491f3 = T_d9881c2cbc5491f3 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_d9881c2cbc5491f3__FMenu", name_id = "Loc_cf708ed550dfe294", inject_menu = "T_c93a2c785995e967__Menu", class = T_d9881c2cbc5491f3}) 
function T_d9881c2cbc5491f3:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["Invisible"] or false 
	self:Toggle({ name = "T_d501a490f56f6a2e", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["Forced"] or false 
	self:Toggle({ name = "T_f30ef435ad0b3de0", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["wpn_fps_ass_garand_golden_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["wpn_fps_ass_garand_golden_s_standard"] or false 
	self:Toggle({ name = "T_918c7f35f09a7e3c", text = "Loc_b232038a19f31bd0", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["wpn_fps_ass_garand_golden_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["wpn_fps_ass_garand_golden_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["wpn_fps_ass_garand_golden_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["wpn_fps_ass_garand_golden_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]) do if i ~= "wpn_fps_ass_garand_golden_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["wpn_fps_ass_garand_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["wpn_fps_ass_garand_s_cheek_rest"] or false 
	self:Toggle({ name = "T_4e625f9797a26ced", text = "Loc_44b1640ed3315118", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["wpn_fps_ass_garand_s_cheek_rest"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["wpn_fps_ass_garand_s_cheek_rest"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["wpn_fps_ass_garand_s_cheek_rest"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]["wpn_fps_ass_garand_s_cheek_rest"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"]) do if i ~= "wpn_fps_ass_garand_s_cheek_rest" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_s_folding"][i] = false end end end }) 
end 
T_4902cba0198cf455 = T_4902cba0198cf455 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_4902cba0198cf455__FMenu", name_id = "Loc_eeb342f2a9be926a", inject_menu = "T_c93a2c785995e967__Menu", class = T_4902cba0198cf455}) 
function T_4902cba0198cf455:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_25f24abc91af475e", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["Forced"] or false 
	self:Toggle({ name = "T_a0ea37f68e8eb2a9", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["wpn_fps_ass_garand_golden_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["wpn_fps_ass_garand_golden_body_standard"] or false 
	self:Toggle({ name = "T_96bd8ad3715b8343", text = "Loc_680167cbff961230", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["wpn_fps_ass_garand_golden_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["wpn_fps_ass_garand_golden_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["wpn_fps_ass_garand_golden_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["wpn_fps_ass_garand_golden_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]) do if i ~= "wpn_fps_ass_garand_golden_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["wpn_fps_ass_garand_golden_m_bar_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["wpn_fps_ass_garand_golden_m_bar_extended"] or false 
	self:Toggle({ name = "T_1c3e2ae7da025168", text = "Loc_6f840107d150398a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["wpn_fps_ass_garand_golden_m_bar_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["wpn_fps_ass_garand_golden_m_bar_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["wpn_fps_ass_garand_golden_m_bar_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]["wpn_fps_ass_garand_golden_m_bar_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"]) do if i ~= "wpn_fps_ass_garand_golden_m_bar_extended" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_standard"][i] = false end end end }) 
end 
T_80beca888ec23a85 = T_80beca888ec23a85 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_80beca888ec23a85__FMenu", name_id = "Loc_6f840107d150398a", inject_menu = "T_c93a2c785995e967__Menu", class = T_80beca888ec23a85}) 
function T_80beca888ec23a85:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["Invisible"] or false 
	self:Toggle({ name = "T_aa6fffa411b63643", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["Forced"] or false 
	self:Toggle({ name = "T_6e0ec545ef03973d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["wpn_fps_ass_garand_golden_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["wpn_fps_ass_garand_golden_body_standard"] or false 
	self:Toggle({ name = "T_42b5563c5482799c", text = "Loc_680167cbff961230", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["wpn_fps_ass_garand_golden_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["wpn_fps_ass_garand_golden_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["wpn_fps_ass_garand_golden_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["wpn_fps_ass_garand_golden_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]) do if i ~= "wpn_fps_ass_garand_golden_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["wpn_fps_ass_garand_golden_m_bar_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["wpn_fps_ass_garand_golden_m_bar_standard"] or false 
	self:Toggle({ name = "T_1f75129c29eae483", text = "Loc_eeb342f2a9be926a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["wpn_fps_ass_garand_golden_m_bar_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["wpn_fps_ass_garand_golden_m_bar_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["wpn_fps_ass_garand_golden_m_bar_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]["wpn_fps_ass_garand_golden_m_bar_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"]) do if i ~= "wpn_fps_ass_garand_golden_m_bar_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_garand_golden_m_bar_extended"][i] = false end end end }) 
end 
