WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_0636cd3c43c4a393 = T_0636cd3c43c4a393 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_0636cd3c43c4a393__Menu", name_id = "bm_w_ithaca", inject_menu = "WACApplyMyMenuMenu", class = T_0636cd3c43c4a393}) 
T_3d16f0c74739f61e = T_3d16f0c74739f61e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_3d16f0c74739f61e__FMenu", name_id = "Loc_f163d12af392ff07", inject_menu = "T_0636cd3c43c4a393__Menu", class = T_3d16f0c74739f61e}) 
function T_3d16f0c74739f61e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_dabc1840015ef343", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_a894808ba135d0c7", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_m_standard"][i] = false end end end }) 
end 
T_225779f9740bba44 = T_225779f9740bba44 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_225779f9740bba44__FMenu", name_id = "Loc_bd26eed053aa1c3a", inject_menu = "T_0636cd3c43c4a393__Menu", class = T_225779f9740bba44}) 
function T_225779f9740bba44:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_1eae725cf9cdbf00", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_b6d48235e0435c15", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["wpn_fps_sho_ithaca_b_reinforced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["wpn_fps_sho_ithaca_b_reinforced"] or false 
	self:Toggle({ name = "T_18575c1bb68150b6", text = "Loc_30c362f90435d0f2", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["wpn_fps_sho_ithaca_b_reinforced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["wpn_fps_sho_ithaca_b_reinforced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["wpn_fps_sho_ithaca_b_reinforced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["wpn_fps_sho_ithaca_b_reinforced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]) do if i ~= "wpn_fps_sho_ithaca_b_reinforced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["wpn_fps_sho_ithaca_b_heat_shield"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["wpn_fps_sho_ithaca_b_heat_shield"] or false 
	self:Toggle({ name = "T_52b1335f8fa74617", text = "Loc_a4717654555dbd73", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["wpn_fps_sho_ithaca_b_heat_shield"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["wpn_fps_sho_ithaca_b_heat_shield"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["wpn_fps_sho_ithaca_b_heat_shield"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]["wpn_fps_sho_ithaca_b_heat_shield"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"]) do if i ~= "wpn_fps_sho_ithaca_b_heat_shield" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_standard"][i] = false end end end }) 
end 
T_d2e75cd0ef14698c = T_d2e75cd0ef14698c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_d2e75cd0ef14698c__FMenu", name_id = "Loc_3a8e9aae3ef9a831", inject_menu = "T_0636cd3c43c4a393__Menu", class = T_d2e75cd0ef14698c}) 
function T_d2e75cd0ef14698c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_f54663fe92261b1b", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_3d9ae70a046e3568", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_body_standard"][i] = false end end end }) 
end 
T_9e0c0bbdf7f5833e = T_9e0c0bbdf7f5833e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_9e0c0bbdf7f5833e__FMenu", name_id = "Loc_42ab30e4b79bc234", inject_menu = "T_0636cd3c43c4a393__Menu", class = T_9e0c0bbdf7f5833e}) 
function T_9e0c0bbdf7f5833e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]["Invisible"] or false 
	self:Toggle({ name = "T_cd9d3a6e650ee844", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]["Forced"] or false 
	self:Toggle({ name = "T_3da5421ef725ac6b", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_lifter"][i] = false end end end }) 
end 
T_09f5609dec4322e9 = T_09f5609dec4322e9 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_09f5609dec4322e9__FMenu", name_id = "Loc_021ff00b8faf4465", inject_menu = "T_0636cd3c43c4a393__Menu", class = T_09f5609dec4322e9}) 
function T_09f5609dec4322e9:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]["Invisible"] or false 
	self:Toggle({ name = "T_b011c27d24cde190", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]["Forced"] or false 
	self:Toggle({ name = "T_de1de7545190f7fb", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_trigger"][i] = false end end end }) 
end 
T_5c5582209e9d6ca9 = T_5c5582209e9d6ca9 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_5c5582209e9d6ca9__FMenu", name_id = "Loc_3213d170834e3f89", inject_menu = "T_0636cd3c43c4a393__Menu", class = T_5c5582209e9d6ca9}) 
function T_5c5582209e9d6ca9:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_9e6c66f926ab7210", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]["Forced"] or false 
	self:Toggle({ name = "T_c3c423647d2246d5", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_sl_standard"][i] = false end end end }) 
end 
T_e3c4fa5e84055142 = T_e3c4fa5e84055142 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_e3c4fa5e84055142__FMenu", name_id = "Loc_2f6a79359100db68", inject_menu = "T_0636cd3c43c4a393__Menu", class = T_e3c4fa5e84055142}) 
function T_e3c4fa5e84055142:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_1f3f34c2a1c6b636", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["Forced"] or false 
	self:Toggle({ name = "T_f49f68cd8c179dc8", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["wpn_fps_sho_ithaca_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["wpn_fps_sho_ithaca_s_cheek_rest"] or false 
	self:Toggle({ name = "T_9890092f78845e9b", text = "Loc_5e3325b3e28778a8", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["wpn_fps_sho_ithaca_s_cheek_rest"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["wpn_fps_sho_ithaca_s_cheek_rest"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["wpn_fps_sho_ithaca_s_cheek_rest"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["wpn_fps_sho_ithaca_s_cheek_rest"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]) do if i ~= "wpn_fps_sho_ithaca_s_cheek_rest" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["wpn_fps_sho_ithaca_s_pistol_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["wpn_fps_sho_ithaca_s_pistol_grip"] or false 
	self:Toggle({ name = "T_d80311f2a5bba098", text = "Loc_533c48dae18e7377", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["wpn_fps_sho_ithaca_s_pistol_grip"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["wpn_fps_sho_ithaca_s_pistol_grip"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["wpn_fps_sho_ithaca_s_pistol_grip"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]["wpn_fps_sho_ithaca_s_pistol_grip"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"]) do if i ~= "wpn_fps_sho_ithaca_s_pistol_grip" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_standard"][i] = false end end end }) 
end 
T_c124e3fb1b1589fe = T_c124e3fb1b1589fe or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_c124e3fb1b1589fe__FMenu", name_id = "Loc_30c362f90435d0f2", inject_menu = "T_0636cd3c43c4a393__Menu", class = T_c124e3fb1b1589fe}) 
function T_c124e3fb1b1589fe:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["Invisible"] or false 
	self:Toggle({ name = "T_19a4a4aa0eac68bc", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["Forced"] or false 
	self:Toggle({ name = "T_0e73317e3bf9e743", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["wpn_fps_sho_ithaca_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["wpn_fps_sho_ithaca_b_standard"] or false 
	self:Toggle({ name = "T_9a2ea2f02fae8886", text = "Loc_bd26eed053aa1c3a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["wpn_fps_sho_ithaca_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["wpn_fps_sho_ithaca_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["wpn_fps_sho_ithaca_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["wpn_fps_sho_ithaca_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]) do if i ~= "wpn_fps_sho_ithaca_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["wpn_fps_sho_ithaca_b_heat_shield"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["wpn_fps_sho_ithaca_b_heat_shield"] or false 
	self:Toggle({ name = "T_379ed609b846f1cc", text = "Loc_a4717654555dbd73", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["wpn_fps_sho_ithaca_b_heat_shield"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["wpn_fps_sho_ithaca_b_heat_shield"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["wpn_fps_sho_ithaca_b_heat_shield"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]["wpn_fps_sho_ithaca_b_heat_shield"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"]) do if i ~= "wpn_fps_sho_ithaca_b_heat_shield" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_reinforced"][i] = false end end end }) 
end 
T_ddd126059f35a1ab = T_ddd126059f35a1ab or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_ddd126059f35a1ab__FMenu", name_id = "Loc_a4717654555dbd73", inject_menu = "T_0636cd3c43c4a393__Menu", class = T_ddd126059f35a1ab}) 
function T_ddd126059f35a1ab:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["Invisible"] or false 
	self:Toggle({ name = "T_0461de1e95146c75", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["Forced"] or false 
	self:Toggle({ name = "T_3446b73da1640fdb", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["wpn_fps_sho_ithaca_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["wpn_fps_sho_ithaca_b_standard"] or false 
	self:Toggle({ name = "T_79c27816142a22ec", text = "Loc_bd26eed053aa1c3a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["wpn_fps_sho_ithaca_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["wpn_fps_sho_ithaca_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["wpn_fps_sho_ithaca_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["wpn_fps_sho_ithaca_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]) do if i ~= "wpn_fps_sho_ithaca_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["wpn_fps_sho_ithaca_b_reinforced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["wpn_fps_sho_ithaca_b_reinforced"] or false 
	self:Toggle({ name = "T_8c777b89af28962e", text = "Loc_30c362f90435d0f2", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["wpn_fps_sho_ithaca_b_reinforced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["wpn_fps_sho_ithaca_b_reinforced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["wpn_fps_sho_ithaca_b_reinforced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]["wpn_fps_sho_ithaca_b_reinforced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"]) do if i ~= "wpn_fps_sho_ithaca_b_reinforced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_b_heat_shield"][i] = false end end end }) 
end 
T_fd69d5b7f65300da = T_fd69d5b7f65300da or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_fd69d5b7f65300da__FMenu", name_id = "Loc_a88acc99571c2e8f", inject_menu = "T_0636cd3c43c4a393__Menu", class = T_fd69d5b7f65300da}) 
function T_fd69d5b7f65300da:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]["Invisible"] or false 
	self:Toggle({ name = "T_741a49e6abcf0054", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]["Forced"] or false 
	self:Toggle({ name = "T_33517665ca2afaac", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_ns_brake"][i] = false end end end }) 
end 
T_910a9c0fcadcc7ce = T_910a9c0fcadcc7ce or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_910a9c0fcadcc7ce__FMenu", name_id = "Loc_5e3325b3e28778a8", inject_menu = "T_0636cd3c43c4a393__Menu", class = T_910a9c0fcadcc7ce}) 
function T_910a9c0fcadcc7ce:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["Invisible"] or false 
	self:Toggle({ name = "T_e8ac7996ec3ff44d", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["Forced"] or false 
	self:Toggle({ name = "T_f9030768cf183f5a", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["wpn_fps_sho_ithaca_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["wpn_fps_sho_ithaca_s_standard"] or false 
	self:Toggle({ name = "T_09ecf0c655872544", text = "Loc_2f6a79359100db68", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["wpn_fps_sho_ithaca_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["wpn_fps_sho_ithaca_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["wpn_fps_sho_ithaca_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["wpn_fps_sho_ithaca_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]) do if i ~= "wpn_fps_sho_ithaca_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["wpn_fps_sho_ithaca_s_pistol_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["wpn_fps_sho_ithaca_s_pistol_grip"] or false 
	self:Toggle({ name = "T_b3e15ebebc88e9e4", text = "Loc_533c48dae18e7377", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["wpn_fps_sho_ithaca_s_pistol_grip"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["wpn_fps_sho_ithaca_s_pistol_grip"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["wpn_fps_sho_ithaca_s_pistol_grip"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]["wpn_fps_sho_ithaca_s_pistol_grip"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"]) do if i ~= "wpn_fps_sho_ithaca_s_pistol_grip" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_cheek_rest"][i] = false end end end }) 
end 
T_1489b5659230424b = T_1489b5659230424b or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_1489b5659230424b__FMenu", name_id = "Loc_533c48dae18e7377", inject_menu = "T_0636cd3c43c4a393__Menu", class = T_1489b5659230424b}) 
function T_1489b5659230424b:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["Invisible"] or false 
	self:Toggle({ name = "T_7262795468e716b9", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["Forced"] or false 
	self:Toggle({ name = "T_b0d2588c44601276", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["wpn_fps_sho_ithaca_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["wpn_fps_sho_ithaca_s_standard"] or false 
	self:Toggle({ name = "T_7efe753b2508d90b", text = "Loc_2f6a79359100db68", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["wpn_fps_sho_ithaca_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["wpn_fps_sho_ithaca_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["wpn_fps_sho_ithaca_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["wpn_fps_sho_ithaca_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]) do if i ~= "wpn_fps_sho_ithaca_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["wpn_fps_sho_ithaca_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["wpn_fps_sho_ithaca_s_cheek_rest"] or false 
	self:Toggle({ name = "T_bd6536a46f602e2e", text = "Loc_5e3325b3e28778a8", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["wpn_fps_sho_ithaca_s_cheek_rest"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["wpn_fps_sho_ithaca_s_cheek_rest"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["wpn_fps_sho_ithaca_s_cheek_rest"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]["wpn_fps_sho_ithaca_s_cheek_rest"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"]) do if i ~= "wpn_fps_sho_ithaca_s_cheek_rest" then WACApplyMyMenu._settings._apply["wpn_fps_sho_ithaca_s_pistol_grip"][i] = false end end end }) 
end 
