WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_74948b197fb517de = T_74948b197fb517de or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_74948b197fb517de__Menu", name_id = "bm_w_kar_98k", inject_menu = "WACApplyMyMenuMenu", class = T_74948b197fb517de}) 
T_d851595903be6efd = T_d851595903be6efd or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_d851595903be6efd__FMenu", name_id = "Loc_497c5b50f9cddf5b", inject_menu = "T_74948b197fb517de__Menu", class = T_d851595903be6efd}) 
function T_d851595903be6efd:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]["Invisible"] or false 
	self:Toggle({ name = "T_7977899b7ae999f8", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]["Forced"] or false 
	self:Toggle({ name = "T_b1749586743a363e", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_strip"][i] = false end end end }) 
end 
T_3372976defa26b4b = T_3372976defa26b4b or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_3372976defa26b4b__FMenu", name_id = "Loc_413f6c351e963d9f", inject_menu = "T_74948b197fb517de__Menu", class = T_3372976defa26b4b}) 
function T_3372976defa26b4b:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_4f71600ec5bc3e88", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_80edc87e842e67fe", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_dh_standard"][i] = false end end end }) 
end 
T_94358262b6a71524 = T_94358262b6a71524 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_94358262b6a71524__FMenu", name_id = "Loc_c05352d853ad0a71", inject_menu = "T_74948b197fb517de__Menu", class = T_94358262b6a71524}) 
function T_94358262b6a71524:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_cf361d3750e18d98", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["Forced"] or false 
	self:Toggle({ name = "T_dd0b66afc6ed1c3e", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["wpn_fps_snp_kar_98k_firepin"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["wpn_fps_snp_kar_98k_firepin"] or false 
	self:Toggle({ name = "T_20fb5e73bee14d32", text = "Loc_55e6ecc64624bbb0", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["wpn_fps_snp_kar_98k_firepin"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["wpn_fps_snp_kar_98k_firepin"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["wpn_fps_snp_kar_98k_firepin"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]["wpn_fps_snp_kar_98k_firepin"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"]) do if i ~= "wpn_fps_snp_kar_98k_firepin" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bolt_standard"][i] = false end end end }) 
end 
T_e1ec0866d200a2be = T_e1ec0866d200a2be or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_e1ec0866d200a2be__FMenu", name_id = "Loc_e979ea88ab6d4935", inject_menu = "T_74948b197fb517de__Menu", class = T_e1ec0866d200a2be}) 
function T_e1ec0866d200a2be:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_3b7f9b9c7207e555", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_22996fa6a9ff670b", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["wpn_fps_snp_kar_98k_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["wpn_fps_snp_kar_98k_b_long"] or false 
	self:Toggle({ name = "T_774424ee1cbd1e5e", text = "Loc_849fc81f24b84ea3", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["wpn_fps_snp_kar_98k_b_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["wpn_fps_snp_kar_98k_b_long"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["wpn_fps_snp_kar_98k_b_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]["wpn_fps_snp_kar_98k_b_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"]) do if i ~= "wpn_fps_snp_kar_98k_b_long" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_standard"][i] = false end end end }) 
end 
T_d804fc4def4c617e = T_d804fc4def4c617e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_d804fc4def4c617e__FMenu", name_id = "Loc_42b09bb7a205f326", inject_menu = "T_74948b197fb517de__Menu", class = T_d804fc4def4c617e}) 
function T_d804fc4def4c617e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_44399e7bd5f8910e", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_5c6782db02348ee4", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["wpn_fps_snp_kar_98k_body_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["wpn_fps_snp_kar_98k_body_grip"] or false 
	self:Toggle({ name = "T_77babcfb28fac239", text = "Loc_7f92d529e52e5c34", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["wpn_fps_snp_kar_98k_body_grip"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["wpn_fps_snp_kar_98k_body_grip"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["wpn_fps_snp_kar_98k_body_grip"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]["wpn_fps_snp_kar_98k_body_grip"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"]) do if i ~= "wpn_fps_snp_kar_98k_body_grip" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_standard"][i] = false end end end }) 
end 
T_8ad46c16bb36a10f = T_8ad46c16bb36a10f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_8ad46c16bb36a10f__FMenu", name_id = "Loc_55e6ecc64624bbb0", inject_menu = "T_74948b197fb517de__Menu", class = T_8ad46c16bb36a10f}) 
function T_8ad46c16bb36a10f:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["Invisible"] or false 
	self:Toggle({ name = "T_2b2c5db1c563a846", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["Forced"] or false 
	self:Toggle({ name = "T_a5cf6bf085149e41", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["wpn_fps_snp_kar_98k_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["wpn_fps_snp_kar_98k_bolt_standard"] or false 
	self:Toggle({ name = "T_68e93a2509b1d73b", text = "Loc_c05352d853ad0a71", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["wpn_fps_snp_kar_98k_bolt_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["wpn_fps_snp_kar_98k_bolt_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["wpn_fps_snp_kar_98k_bolt_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]["wpn_fps_snp_kar_98k_bolt_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"]) do if i ~= "wpn_fps_snp_kar_98k_bolt_standard" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_firepin"][i] = false end end end }) 
end 
T_9e477e0080584e3e = T_9e477e0080584e3e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_9e477e0080584e3e__FMenu", name_id = "Loc_aab794369ebf80b1", inject_menu = "T_74948b197fb517de__Menu", class = T_9e477e0080584e3e}) 
function T_9e477e0080584e3e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["Invisible"] or false 
	self:Toggle({ name = "T_9d47457551cf90f8", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["Forced"] or false 
	self:Toggle({ name = "T_ead17e27c220c391", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["wpn_fps_snp_kar_98k_bullets"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["wpn_fps_snp_kar_98k_bullets"] or false 
	self:Toggle({ name = "T_9fe26d4023919b62", text = "Loc_2377f229e4773b3e", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["wpn_fps_snp_kar_98k_bullets"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["wpn_fps_snp_kar_98k_bullets"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["wpn_fps_snp_kar_98k_bullets"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]["wpn_fps_snp_kar_98k_bullets"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"]) do if i ~= "wpn_fps_snp_kar_98k_bullets" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullet"][i] = false end end end }) 
end 
T_b532fbcbe35323ee = T_b532fbcbe35323ee or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b532fbcbe35323ee__FMenu", name_id = "Loc_2377f229e4773b3e", inject_menu = "T_74948b197fb517de__Menu", class = T_b532fbcbe35323ee}) 
function T_b532fbcbe35323ee:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["Invisible"] or false 
	self:Toggle({ name = "T_3f68524f62c20701", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["Forced"] or false 
	self:Toggle({ name = "T_190c3ece4a6b066b", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["wpn_fps_snp_kar_98k_bullet"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["wpn_fps_snp_kar_98k_bullet"] or false 
	self:Toggle({ name = "T_efb66d9cfb32e267", text = "Loc_aab794369ebf80b1", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["wpn_fps_snp_kar_98k_bullet"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["wpn_fps_snp_kar_98k_bullet"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["wpn_fps_snp_kar_98k_bullet"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]["wpn_fps_snp_kar_98k_bullet"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"]) do if i ~= "wpn_fps_snp_kar_98k_bullet" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_bullets"][i] = false end end end }) 
end 
T_ab39f41d9164481c = T_ab39f41d9164481c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_ab39f41d9164481c__FMenu", name_id = "Loc_787652fd368fa1a1", inject_menu = "T_74948b197fb517de__Menu", class = T_ab39f41d9164481c}) 
function T_ab39f41d9164481c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]["Invisible"] or false 
	self:Toggle({ name = "T_6418fd49b4f492c8", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]["Forced"] or false 
	self:Toggle({ name = "T_7775334e8a2c9a54", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_trigger"][i] = false end end end }) 
end 
T_5cf11768487cd659 = T_5cf11768487cd659 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_5cf11768487cd659__FMenu", name_id = "Loc_2fdb339ea91c813f", inject_menu = "T_74948b197fb517de__Menu", class = T_5cf11768487cd659}) 
function T_5cf11768487cd659:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_a6b9a4cc78b6107f", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["Forced"] or false 
	self:Toggle({ name = "T_23843a077168d43b", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["wpn_fps_snp_kar_98k_pad_big"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["wpn_fps_snp_kar_98k_pad_big"] or false 
	self:Toggle({ name = "T_2fc07e508b12ab26", text = "Loc_eab1c7e674ca516e", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["wpn_fps_snp_kar_98k_pad_big"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["wpn_fps_snp_kar_98k_pad_big"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["wpn_fps_snp_kar_98k_pad_big"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]["wpn_fps_snp_kar_98k_pad_big"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"]) do if i ~= "wpn_fps_snp_kar_98k_pad_big" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_standard"][i] = false end end end }) 
end 
T_62aa57ca0af84b7e = T_62aa57ca0af84b7e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_62aa57ca0af84b7e__FMenu", name_id = "Loc_849fc81f24b84ea3", inject_menu = "T_74948b197fb517de__Menu", class = T_62aa57ca0af84b7e}) 
function T_62aa57ca0af84b7e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["Invisible"] or false 
	self:Toggle({ name = "T_9a5a2c71d21f4154", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["Forced"] or false 
	self:Toggle({ name = "T_19ec325bf143b255", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["wpn_fps_snp_kar_98k_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["wpn_fps_snp_kar_98k_b_standard"] or false 
	self:Toggle({ name = "T_bea778fce8ff55e1", text = "Loc_e979ea88ab6d4935", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["wpn_fps_snp_kar_98k_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["wpn_fps_snp_kar_98k_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["wpn_fps_snp_kar_98k_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]["wpn_fps_snp_kar_98k_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"]) do if i ~= "wpn_fps_snp_kar_98k_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_b_long"][i] = false end end end }) 
end 
T_b2f11af56d355872 = T_b2f11af56d355872 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b2f11af56d355872__FMenu", name_id = "Loc_7f92d529e52e5c34", inject_menu = "T_74948b197fb517de__Menu", class = T_b2f11af56d355872}) 
function T_b2f11af56d355872:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["Invisible"] or false 
	self:Toggle({ name = "T_4d39cc814550c203", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["Forced"] or false 
	self:Toggle({ name = "T_3c01e072ec33985e", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["wpn_fps_snp_kar_98k_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["wpn_fps_snp_kar_98k_body_standard"] or false 
	self:Toggle({ name = "T_0581b27a440081a9", text = "Loc_42b09bb7a205f326", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["wpn_fps_snp_kar_98k_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["wpn_fps_snp_kar_98k_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["wpn_fps_snp_kar_98k_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]["wpn_fps_snp_kar_98k_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"]) do if i ~= "wpn_fps_snp_kar_98k_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_body_grip"][i] = false end end end }) 
end 
T_b407c9dd1027d63a = T_b407c9dd1027d63a or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b407c9dd1027d63a__FMenu", name_id = "Loc_eab1c7e674ca516e", inject_menu = "T_74948b197fb517de__Menu", class = T_b407c9dd1027d63a}) 
function T_b407c9dd1027d63a:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["Invisible"] or false 
	self:Toggle({ name = "T_41ed3248c3042bc1", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["Forced"] or false 
	self:Toggle({ name = "T_2556c99d3b376267", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["wpn_fps_snp_kar_98k_pad_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["wpn_fps_snp_kar_98k_pad_standard"] or false 
	self:Toggle({ name = "T_e9e66732029522bf", text = "Loc_2fdb339ea91c813f", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["wpn_fps_snp_kar_98k_pad_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["wpn_fps_snp_kar_98k_pad_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["wpn_fps_snp_kar_98k_pad_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]["wpn_fps_snp_kar_98k_pad_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"]) do if i ~= "wpn_fps_snp_kar_98k_pad_standard" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_pad_big"][i] = false end end end }) 
end 
T_4918f0125751609a = T_4918f0125751609a or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_4918f0125751609a__FMenu", name_id = "Loc_2548e8d4d3fd0781", inject_menu = "T_74948b197fb517de__Menu", class = T_4918f0125751609a}) 
function T_4918f0125751609a:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["Invisible"] or false 
	self:Toggle({ name = "T_b981e984af7e2544", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["Forced"] or false 
	self:Toggle({ name = "T_ef4d140469421c84", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["wpn_fps_snp_kar_98k_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["wpn_fps_snp_kar_98k_m_long"] or false 
	self:Toggle({ name = "T_5ab3fe29d6706771", text = "Loc_d515334afa022c99", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["wpn_fps_snp_kar_98k_m_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["wpn_fps_snp_kar_98k_m_long"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["wpn_fps_snp_kar_98k_m_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]["wpn_fps_snp_kar_98k_m_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"]) do if i ~= "wpn_fps_snp_kar_98k_m_long" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_extended"][i] = false end end end }) 
end 
T_b72b072647a93db0 = T_b72b072647a93db0 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b72b072647a93db0__FMenu", name_id = "Loc_d515334afa022c99", inject_menu = "T_74948b197fb517de__Menu", class = T_b72b072647a93db0}) 
function T_b72b072647a93db0:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["Invisible"] or false 
	self:Toggle({ name = "T_8a0dd7bb0f9b79b7", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["Forced"] or false 
	self:Toggle({ name = "T_9d511e136f74d4cf", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["wpn_fps_snp_kar_98k_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["wpn_fps_snp_kar_98k_m_extended"] or false 
	self:Toggle({ name = "T_fdfcbd5636442196", text = "Loc_2548e8d4d3fd0781", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["wpn_fps_snp_kar_98k_m_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["wpn_fps_snp_kar_98k_m_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["wpn_fps_snp_kar_98k_m_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]["wpn_fps_snp_kar_98k_m_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"]) do if i ~= "wpn_fps_snp_kar_98k_m_extended" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_m_long"][i] = false end end end }) 
end 
T_03d4bb57ea6cf4ea = T_03d4bb57ea6cf4ea or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_03d4bb57ea6cf4ea__FMenu", name_id = "Loc_fb6dc69b6790ab8a", inject_menu = "T_74948b197fb517de__Menu", class = T_03d4bb57ea6cf4ea}) 
function T_03d4bb57ea6cf4ea:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]["Invisible"] or false 
	self:Toggle({ name = "T_d4ddbb0329336f49", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]["Forced"] or false 
	self:Toggle({ name = "T_3303af5bbb4e3cd0", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_kar_98k_o_scope"][i] = false end end end }) 
end 
