WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_4d12a9edf95bf417 = T_4d12a9edf95bf417 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_4d12a9edf95bf417__Menu", name_id = "bm_w_m1903", inject_menu = "WACApplyMyMenuMenu", class = T_4d12a9edf95bf417}) 
T_b8a2624a9fd4ce07 = T_b8a2624a9fd4ce07 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b8a2624a9fd4ce07__FMenu", name_id = "Loc_ad45fb14c9151ef7", inject_menu = "T_4d12a9edf95bf417__Menu", class = T_b8a2624a9fd4ce07}) 
function T_b8a2624a9fd4ce07:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["Invisible"] or false 
	self:Toggle({ name = "T_5211e8a48d270050", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["Forced"] or false 
	self:Toggle({ name = "T_014d9d3a54a6197a", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["wpn_fps_snp_m1903_body_type_c"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["wpn_fps_snp_m1903_body_type_c"] or false 
	self:Toggle({ name = "T_8dafd942bfcde06d", text = "Loc_2885ed15477b490b", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["wpn_fps_snp_m1903_body_type_c"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["wpn_fps_snp_m1903_body_type_c"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["wpn_fps_snp_m1903_body_type_c"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["wpn_fps_snp_m1903_body_type_c"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]) do if i ~= "wpn_fps_snp_m1903_body_type_c" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["wpn_fps_snp_m1903_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["wpn_fps_snp_m1903_s_cheek_rest"] or false 
	self:Toggle({ name = "T_49412ae844588dec", text = "Loc_b040cf1920393b56", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["wpn_fps_snp_m1903_s_cheek_rest"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["wpn_fps_snp_m1903_s_cheek_rest"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["wpn_fps_snp_m1903_s_cheek_rest"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]["wpn_fps_snp_m1903_s_cheek_rest"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"]) do if i ~= "wpn_fps_snp_m1903_s_cheek_rest" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_s"][i] = false end end end }) 
end 
T_ed1db702f3bd6903 = T_ed1db702f3bd6903 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_ed1db702f3bd6903__FMenu", name_id = "Loc_14b38a2e47c720fb", inject_menu = "T_4d12a9edf95bf417__Menu", class = T_ed1db702f3bd6903}) 
function T_ed1db702f3bd6903:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_d0f1f06957fa7bc6", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_32ea2d870870094c", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_b_standard"][i] = false end end end }) 
end 
T_02fb3783dfdeb9ad = T_02fb3783dfdeb9ad or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_02fb3783dfdeb9ad__FMenu", name_id = "Loc_e2e461b5077df8a5", inject_menu = "T_4d12a9edf95bf417__Menu", class = T_02fb3783dfdeb9ad}) 
function T_02fb3783dfdeb9ad:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]["Invisible"] or false 
	self:Toggle({ name = "T_4f5b892c8c22a989", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]["Forced"] or false 
	self:Toggle({ name = "T_8eed5fc6f0f805b2", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_firepin"][i] = false end end end }) 
end 
T_3c03ca9e37b1d661 = T_3c03ca9e37b1d661 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_3c03ca9e37b1d661__FMenu", name_id = "Loc_3ddf975e469868f5", inject_menu = "T_4d12a9edf95bf417__Menu", class = T_3c03ca9e37b1d661}) 
function T_3c03ca9e37b1d661:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_7dfd0379710e24d0", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]["Forced"] or false 
	self:Toggle({ name = "T_a5975547b6a91a06", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_bolt_standard"][i] = false end end end }) 
end 
T_61d85eade55c787f = T_61d85eade55c787f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_61d85eade55c787f__FMenu", name_id = "Loc_1f89a4d866f1a843", inject_menu = "T_4d12a9edf95bf417__Menu", class = T_61d85eade55c787f}) 
function T_61d85eade55c787f:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_d06ea4ec575f7fd2", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_1b21731111eb0a07", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_dh_standard"][i] = false end end end }) 
end 
T_7dff2fea4622dbde = T_7dff2fea4622dbde or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_7dff2fea4622dbde__FMenu", name_id = "Loc_464b49027fa30bdb", inject_menu = "T_4d12a9edf95bf417__Menu", class = T_7dff2fea4622dbde}) 
function T_7dff2fea4622dbde:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]["Invisible"] or false 
	self:Toggle({ name = "T_66c54dfe82408ff7", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]["Forced"] or false 
	self:Toggle({ name = "T_2682db14de505150", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_extra_follower"][i] = false end end end }) 
end 
T_6dbbe8083c162fe2 = T_6dbbe8083c162fe2 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_6dbbe8083c162fe2__FMenu", name_id = "Loc_f4982db27dfc4c2f", inject_menu = "T_4d12a9edf95bf417__Menu", class = T_6dbbe8083c162fe2}) 
function T_6dbbe8083c162fe2:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_3eb2df61432231ba", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_96c4760eca0765f8", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["wpn_fps_snp_m1903_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["wpn_fps_snp_m1903_m_extended"] or false 
	self:Toggle({ name = "T_65618890a95b3fc1", text = "Loc_752c777f4a1b1923", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["wpn_fps_snp_m1903_m_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["wpn_fps_snp_m1903_m_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["wpn_fps_snp_m1903_m_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]["wpn_fps_snp_m1903_m_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"]) do if i ~= "wpn_fps_snp_m1903_m_extended" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_standard"][i] = false end end end }) 
end 
T_53181c774e4bc245 = T_53181c774e4bc245 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_53181c774e4bc245__FMenu", name_id = "Loc_2885ed15477b490b", inject_menu = "T_4d12a9edf95bf417__Menu", class = T_53181c774e4bc245}) 
function T_53181c774e4bc245:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["Invisible"] or false 
	self:Toggle({ name = "T_c26814d0119c48aa", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["Forced"] or false 
	self:Toggle({ name = "T_aebf6515d89be652", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["wpn_fps_snp_m1903_body_type_s"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["wpn_fps_snp_m1903_body_type_s"] or false 
	self:Toggle({ name = "T_e161754a7a196c4f", text = "Loc_ad45fb14c9151ef7", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["wpn_fps_snp_m1903_body_type_s"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["wpn_fps_snp_m1903_body_type_s"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["wpn_fps_snp_m1903_body_type_s"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["wpn_fps_snp_m1903_body_type_s"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]) do if i ~= "wpn_fps_snp_m1903_body_type_s" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["wpn_fps_snp_m1903_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["wpn_fps_snp_m1903_s_cheek_rest"] or false 
	self:Toggle({ name = "T_583f66f6d573add9", text = "Loc_b040cf1920393b56", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["wpn_fps_snp_m1903_s_cheek_rest"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["wpn_fps_snp_m1903_s_cheek_rest"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["wpn_fps_snp_m1903_s_cheek_rest"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]["wpn_fps_snp_m1903_s_cheek_rest"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"]) do if i ~= "wpn_fps_snp_m1903_s_cheek_rest" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_body_type_c"][i] = false end end end }) 
end 
T_200d4fd5cea8b1db = T_200d4fd5cea8b1db or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_200d4fd5cea8b1db__FMenu", name_id = "Loc_b040cf1920393b56", inject_menu = "T_4d12a9edf95bf417__Menu", class = T_200d4fd5cea8b1db}) 
function T_200d4fd5cea8b1db:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["Invisible"] or false 
	self:Toggle({ name = "T_492a5926173c05e9", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["Forced"] or false 
	self:Toggle({ name = "T_42732ceb1d5a9141", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["wpn_fps_snp_m1903_body_type_s"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["wpn_fps_snp_m1903_body_type_s"] or false 
	self:Toggle({ name = "T_39780c717b44d174", text = "Loc_ad45fb14c9151ef7", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["wpn_fps_snp_m1903_body_type_s"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["wpn_fps_snp_m1903_body_type_s"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["wpn_fps_snp_m1903_body_type_s"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["wpn_fps_snp_m1903_body_type_s"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]) do if i ~= "wpn_fps_snp_m1903_body_type_s" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["wpn_fps_snp_m1903_body_type_c"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["wpn_fps_snp_m1903_body_type_c"] or false 
	self:Toggle({ name = "T_51aa170cac03dadc", text = "Loc_2885ed15477b490b", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["wpn_fps_snp_m1903_body_type_c"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["wpn_fps_snp_m1903_body_type_c"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["wpn_fps_snp_m1903_body_type_c"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]["wpn_fps_snp_m1903_body_type_c"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"]) do if i ~= "wpn_fps_snp_m1903_body_type_c" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_s_cheek_rest"][i] = false end end end }) 
end 
T_2f82e06f20c0ce7b = T_2f82e06f20c0ce7b or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_2f82e06f20c0ce7b__FMenu", name_id = "Loc_e1992db17aa7b63e", inject_menu = "T_4d12a9edf95bf417__Menu", class = T_2f82e06f20c0ce7b}) 
function T_2f82e06f20c0ce7b:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]["Invisible"] or false 
	self:Toggle({ name = "T_2507f4db7238717c", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]["Forced"] or false 
	self:Toggle({ name = "T_a17879d8ab2948eb", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_ns_mclean"][i] = false end end end }) 
end 
T_fb5365dce9a99f62 = T_fb5365dce9a99f62 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_fb5365dce9a99f62__FMenu", name_id = "Loc_97e97ef13f2c8d0b", inject_menu = "T_4d12a9edf95bf417__Menu", class = T_fb5365dce9a99f62}) 
function T_fb5365dce9a99f62:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]["Invisible"] or false 
	self:Toggle({ name = "T_ca77ff06de12cfb8", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]["Forced"] or false 
	self:Toggle({ name = "T_1f13b4e211dbfa9d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_o_scope"][i] = false end end end }) 
end 
T_ed2df3ce6033126e = T_ed2df3ce6033126e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_ed2df3ce6033126e__FMenu", name_id = "Loc_752c777f4a1b1923", inject_menu = "T_4d12a9edf95bf417__Menu", class = T_ed2df3ce6033126e}) 
function T_ed2df3ce6033126e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["Invisible"] or false 
	self:Toggle({ name = "T_3a3c2e51ae692415", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["Forced"] or false 
	self:Toggle({ name = "T_96aae124d43110f8", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["wpn_fps_snp_m1903_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["wpn_fps_snp_m1903_m_standard"] or false 
	self:Toggle({ name = "T_bad24d81fa6b4ebc", text = "Loc_f4982db27dfc4c2f", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["wpn_fps_snp_m1903_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["wpn_fps_snp_m1903_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["wpn_fps_snp_m1903_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]["wpn_fps_snp_m1903_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"]) do if i ~= "wpn_fps_snp_m1903_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_snp_m1903_m_extended"][i] = false end end end }) 
end 
