WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_71dfa5e8403cb30c = T_71dfa5e8403cb30c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_71dfa5e8403cb30c__Menu", name_id = "bm_w_mosin", inject_menu = "WACApplyMyMenuMenu", class = T_71dfa5e8403cb30c}) 
T_595780777bca6734 = T_595780777bca6734 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_595780777bca6734__FMenu", name_id = "Loc_14ca0bfec46880ad", inject_menu = "T_71dfa5e8403cb30c__Menu", class = T_595780777bca6734}) 
function T_595780777bca6734:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_516f7082dcbd938e", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_6155481dd2ce49cf", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["wpn_fps_snp_mosin_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["wpn_fps_snp_mosin_b_long"] or false 
	self:Toggle({ name = "T_40f3bbdb43edf03a", text = "Loc_b54b2c5a51628964", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["wpn_fps_snp_mosin_b_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["wpn_fps_snp_mosin_b_long"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["wpn_fps_snp_mosin_b_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]["wpn_fps_snp_mosin_b_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"]) do if i ~= "wpn_fps_snp_mosin_b_long" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_standard"][i] = false end end end }) 
end 
T_edab715fb81c189e = T_edab715fb81c189e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_edab715fb81c189e__FMenu", name_id = "Loc_eb6f17a3527b4b46", inject_menu = "T_71dfa5e8403cb30c__Menu", class = T_edab715fb81c189e}) 
function T_edab715fb81c189e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_2f645747f2e988f1", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_39dc77a1f695d7bf", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["wpn_fps_snp_mosin_body_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["wpn_fps_snp_mosin_body_grip"] or false 
	self:Toggle({ name = "T_b821d5fd11656d1d", text = "Loc_acc29d701bcc9310", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["wpn_fps_snp_mosin_body_grip"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["wpn_fps_snp_mosin_body_grip"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["wpn_fps_snp_mosin_body_grip"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["wpn_fps_snp_mosin_body_grip"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]) do if i ~= "wpn_fps_snp_mosin_body_grip" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["wpn_fps_snp_mosin_body_target"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["wpn_fps_snp_mosin_body_target"] or false 
	self:Toggle({ name = "T_cd41a4628c248f2a", text = "Loc_e3ba5a3da4f3afa2", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["wpn_fps_snp_mosin_body_target"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["wpn_fps_snp_mosin_body_target"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["wpn_fps_snp_mosin_body_target"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]["wpn_fps_snp_mosin_body_target"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"]) do if i ~= "wpn_fps_snp_mosin_body_target" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_standard"][i] = false end end end }) 
end 
T_557ed276d46f93f0 = T_557ed276d46f93f0 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_557ed276d46f93f0__FMenu", name_id = "Loc_e4bedd6e3bc2fb3f", inject_menu = "T_71dfa5e8403cb30c__Menu", class = T_557ed276d46f93f0}) 
function T_557ed276d46f93f0:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_2767ccc2b0dd3954", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]["Forced"] or false 
	self:Toggle({ name = "T_a3a836b656765269", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bolt_standard"][i] = false end end end }) 
end 
T_9cf259481c177a97 = T_9cf259481c177a97 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_9cf259481c177a97__FMenu", name_id = "Loc_bf204d97b8b83d47", inject_menu = "T_71dfa5e8403cb30c__Menu", class = T_9cf259481c177a97}) 
function T_9cf259481c177a97:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_2a6eaf775c1e76f1", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_df51979540aff347", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_dh_standard"][i] = false end end end }) 
end 
T_0b2ae1a9a1a60ade = T_0b2ae1a9a1a60ade or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_0b2ae1a9a1a60ade__FMenu", name_id = "Loc_a87408ce3d4fcf9c", inject_menu = "T_71dfa5e8403cb30c__Menu", class = T_0b2ae1a9a1a60ade}) 
function T_0b2ae1a9a1a60ade:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_6c77cdb4aa958516", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_dc8ee047bcc7876d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_m_standard"][i] = false end end end }) 
end 
T_35bcaecdf293970e = T_35bcaecdf293970e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_35bcaecdf293970e__FMenu", name_id = "Loc_64c8b0f73ca25e54", inject_menu = "T_71dfa5e8403cb30c__Menu", class = T_35bcaecdf293970e}) 
function T_35bcaecdf293970e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_8b1aff9dce018476", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]["Forced"] or false 
	self:Toggle({ name = "T_39945254f42eceb2", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_clip_standard"][i] = false end end end }) 
end 
T_621f08ec4d4514c8 = T_621f08ec4d4514c8 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_621f08ec4d4514c8__FMenu", name_id = "Loc_f45f4525032cd77f", inject_menu = "T_71dfa5e8403cb30c__Menu", class = T_621f08ec4d4514c8}) 
function T_621f08ec4d4514c8:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]["Invisible"] or false 
	self:Toggle({ name = "T_12bcef1f865d0ab6", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]["Forced"] or false 
	self:Toggle({ name = "T_f2ace69c70df497b", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_bullet"][i] = false end end end }) 
end 
T_de7aa3a17a9a9f35 = T_de7aa3a17a9a9f35 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_de7aa3a17a9a9f35__FMenu", name_id = "Loc_b54b2c5a51628964", inject_menu = "T_71dfa5e8403cb30c__Menu", class = T_de7aa3a17a9a9f35}) 
function T_de7aa3a17a9a9f35:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["Invisible"] or false 
	self:Toggle({ name = "T_36a68c308bf10a5e", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["Forced"] or false 
	self:Toggle({ name = "T_dafe347b0a2ad1bf", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["wpn_fps_snp_mosin_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["wpn_fps_snp_mosin_b_standard"] or false 
	self:Toggle({ name = "T_2091097382855f22", text = "Loc_14ca0bfec46880ad", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["wpn_fps_snp_mosin_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["wpn_fps_snp_mosin_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["wpn_fps_snp_mosin_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]["wpn_fps_snp_mosin_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"]) do if i ~= "wpn_fps_snp_mosin_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_b_long"][i] = false end end end }) 
end 
T_2c1a25988dc42bde = T_2c1a25988dc42bde or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_2c1a25988dc42bde__FMenu", name_id = "Loc_acc29d701bcc9310", inject_menu = "T_71dfa5e8403cb30c__Menu", class = T_2c1a25988dc42bde}) 
function T_2c1a25988dc42bde:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["Invisible"] or false 
	self:Toggle({ name = "T_c4f9ff1bcb76920f", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["Forced"] or false 
	self:Toggle({ name = "T_6ab8b477b7634a5a", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["wpn_fps_snp_mosin_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["wpn_fps_snp_mosin_body_standard"] or false 
	self:Toggle({ name = "T_2ea2efca15ee0be3", text = "Loc_eb6f17a3527b4b46", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["wpn_fps_snp_mosin_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["wpn_fps_snp_mosin_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["wpn_fps_snp_mosin_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["wpn_fps_snp_mosin_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]) do if i ~= "wpn_fps_snp_mosin_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["wpn_fps_snp_mosin_body_target"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["wpn_fps_snp_mosin_body_target"] or false 
	self:Toggle({ name = "T_d57435e66ec632fe", text = "Loc_e3ba5a3da4f3afa2", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["wpn_fps_snp_mosin_body_target"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["wpn_fps_snp_mosin_body_target"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["wpn_fps_snp_mosin_body_target"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]["wpn_fps_snp_mosin_body_target"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"]) do if i ~= "wpn_fps_snp_mosin_body_target" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_grip"][i] = false end end end }) 
end 
T_f301f6a6211645fa = T_f301f6a6211645fa or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_f301f6a6211645fa__FMenu", name_id = "Loc_e3ba5a3da4f3afa2", inject_menu = "T_71dfa5e8403cb30c__Menu", class = T_f301f6a6211645fa}) 
function T_f301f6a6211645fa:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["Invisible"] or false 
	self:Toggle({ name = "T_f0f678070fa879fb", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["Forced"] or false 
	self:Toggle({ name = "T_aae0cd39a0b4da72", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["wpn_fps_snp_mosin_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["wpn_fps_snp_mosin_body_standard"] or false 
	self:Toggle({ name = "T_2e253a35d7896757", text = "Loc_eb6f17a3527b4b46", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["wpn_fps_snp_mosin_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["wpn_fps_snp_mosin_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["wpn_fps_snp_mosin_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["wpn_fps_snp_mosin_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]) do if i ~= "wpn_fps_snp_mosin_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["wpn_fps_snp_mosin_body_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["wpn_fps_snp_mosin_body_grip"] or false 
	self:Toggle({ name = "T_df7a5f38e82ca984", text = "Loc_acc29d701bcc9310", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["wpn_fps_snp_mosin_body_grip"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["wpn_fps_snp_mosin_body_grip"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["wpn_fps_snp_mosin_body_grip"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]["wpn_fps_snp_mosin_body_grip"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"]) do if i ~= "wpn_fps_snp_mosin_body_grip" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_body_target"][i] = false end end end }) 
end 
T_1d7b3436f300b434 = T_1d7b3436f300b434 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_1d7b3436f300b434__FMenu", name_id = "Loc_4866dbd72f09f37a", inject_menu = "T_71dfa5e8403cb30c__Menu", class = T_1d7b3436f300b434}) 
function T_1d7b3436f300b434:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]["Invisible"] or false 
	self:Toggle({ name = "T_9dda6fe3b176f404", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]["Forced"] or false 
	self:Toggle({ name = "T_f03fc438a5044ced", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_snp_mosin_o_scope"][i] = false end end end }) 
end 
