WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_0a222a80f3ee080f = T_0a222a80f3ee080f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_0a222a80f3ee080f__Menu", name_id = "bm_w_m1918", inject_menu = "WACApplyMyMenuMenu", class = T_0a222a80f3ee080f}) 
T_b7daa127d4e808d3 = T_b7daa127d4e808d3 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b7daa127d4e808d3__FMenu", name_id = "Loc_8bc0c9c3dcdefefb", inject_menu = "T_0a222a80f3ee080f__Menu", class = T_b7daa127d4e808d3}) 
function T_b7daa127d4e808d3:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_0f0ec5e8328a7641", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_13bdd51cc5c78572", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["wpn_fps_lmg_m1918_g_monitor"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["wpn_fps_lmg_m1918_g_monitor"] or false 
	self:Toggle({ name = "T_5525ce24b3cc8b65", text = "Loc_65a92562b545ca1a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["wpn_fps_lmg_m1918_g_monitor"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["wpn_fps_lmg_m1918_g_monitor"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["wpn_fps_lmg_m1918_g_monitor"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["wpn_fps_lmg_m1918_g_monitor"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]) do if i ~= "wpn_fps_lmg_m1918_g_monitor" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["wpn_fps_lmg_m1918_carry_handle"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["wpn_fps_lmg_m1918_carry_handle"] or false 
	self:Toggle({ name = "T_e5d667da7c20e666", text = "Loc_2d8d69cee973182a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["wpn_fps_lmg_m1918_carry_handle"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["wpn_fps_lmg_m1918_carry_handle"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["wpn_fps_lmg_m1918_carry_handle"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]["wpn_fps_lmg_m1918_carry_handle"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"]) do if i ~= "wpn_fps_lmg_m1918_carry_handle" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_body_standard"][i] = false end end end }) 
end 
T_41d4328ef2d86f9f = T_41d4328ef2d86f9f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_41d4328ef2d86f9f__FMenu", name_id = "Loc_cb868d045ba7a682", inject_menu = "T_0a222a80f3ee080f__Menu", class = T_41d4328ef2d86f9f}) 
function T_41d4328ef2d86f9f:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_56a6f68575645f02", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_e390b2ae631e402d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_b_standard"][i] = false end end end }) 
end 
T_20c6b1abb124f1b1 = T_20c6b1abb124f1b1 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_20c6b1abb124f1b1__FMenu", name_id = "Loc_e26ab86506592564", inject_menu = "T_0a222a80f3ee080f__Menu", class = T_20c6b1abb124f1b1}) 
function T_20c6b1abb124f1b1:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_ba7270e798ac4c70", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["Forced"] or false 
	self:Toggle({ name = "T_63fea0a4acf15183", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["wpn_fps_lmg_m1918_ns_cutts"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["wpn_fps_lmg_m1918_ns_cutts"] or false 
	self:Toggle({ name = "T_66c5da8854505ce7", text = "Loc_08bc408f28da00ab", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["wpn_fps_lmg_m1918_ns_cutts"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["wpn_fps_lmg_m1918_ns_cutts"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["wpn_fps_lmg_m1918_ns_cutts"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]["wpn_fps_lmg_m1918_ns_cutts"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"]) do if i ~= "wpn_fps_lmg_m1918_ns_cutts" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_standard"][i] = false end end end }) 
end 
T_90d705e2ac4578ab = T_90d705e2ac4578ab or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_90d705e2ac4578ab__FMenu", name_id = "Loc_3934aa9c7f46e5cb", inject_menu = "T_0a222a80f3ee080f__Menu", class = T_90d705e2ac4578ab}) 
function T_90d705e2ac4578ab:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_d8e1e947d6dcd9cc", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_73a083eb80be77b4", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["wpn_fps_lmg_m1918_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["wpn_fps_lmg_m1918_m_extended"] or false 
	self:Toggle({ name = "T_c311ac33ab73bd9e", text = "Loc_9b0872d85c16cb6e", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["wpn_fps_lmg_m1918_m_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["wpn_fps_lmg_m1918_m_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["wpn_fps_lmg_m1918_m_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]["wpn_fps_lmg_m1918_m_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"]) do if i ~= "wpn_fps_lmg_m1918_m_extended" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_standard"][i] = false end end end }) 
end 
T_fd6b9db3145e38a7 = T_fd6b9db3145e38a7 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_fd6b9db3145e38a7__FMenu", name_id = "Loc_05af92b773ed3a23", inject_menu = "T_0a222a80f3ee080f__Menu", class = T_fd6b9db3145e38a7}) 
function T_fd6b9db3145e38a7:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_26d61956da2f188a", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_68c1499ca36bc559", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_dh_standard"][i] = false end end end }) 
end 
T_2214761ff659c4fa = T_2214761ff659c4fa or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_2214761ff659c4fa__FMenu", name_id = "Loc_08bc408f28da00ab", inject_menu = "T_0a222a80f3ee080f__Menu", class = T_2214761ff659c4fa}) 
function T_2214761ff659c4fa:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["Invisible"] or false 
	self:Toggle({ name = "T_410687aa9a25ab04", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["Forced"] or false 
	self:Toggle({ name = "T_5262d3dccaca1c5d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["wpn_fps_lmg_m1918_ns_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["wpn_fps_lmg_m1918_ns_standard"] or false 
	self:Toggle({ name = "T_2fd6bc6e1156a4de", text = "Loc_e26ab86506592564", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["wpn_fps_lmg_m1918_ns_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["wpn_fps_lmg_m1918_ns_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["wpn_fps_lmg_m1918_ns_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]["wpn_fps_lmg_m1918_ns_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"]) do if i ~= "wpn_fps_lmg_m1918_ns_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_ns_cutts"][i] = false end end end }) 
end 
T_56865063014a1ea6 = T_56865063014a1ea6 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_56865063014a1ea6__FMenu", name_id = "Loc_65a92562b545ca1a", inject_menu = "T_0a222a80f3ee080f__Menu", class = T_56865063014a1ea6}) 
function T_56865063014a1ea6:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["Invisible"] or false 
	self:Toggle({ name = "T_36682c78b0cc61f5", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["Forced"] or false 
	self:Toggle({ name = "T_cef22d2509742e7e", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["wpn_fps_lmg_m1918_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["wpn_fps_lmg_m1918_body_standard"] or false 
	self:Toggle({ name = "T_5ac906652ab558fd", text = "Loc_8bc0c9c3dcdefefb", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["wpn_fps_lmg_m1918_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["wpn_fps_lmg_m1918_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["wpn_fps_lmg_m1918_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["wpn_fps_lmg_m1918_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]) do if i ~= "wpn_fps_lmg_m1918_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["wpn_fps_lmg_m1918_carry_handle"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["wpn_fps_lmg_m1918_carry_handle"] or false 
	self:Toggle({ name = "T_0d4c62b10a43f89c", text = "Loc_2d8d69cee973182a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["wpn_fps_lmg_m1918_carry_handle"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["wpn_fps_lmg_m1918_carry_handle"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["wpn_fps_lmg_m1918_carry_handle"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]["wpn_fps_lmg_m1918_carry_handle"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"]) do if i ~= "wpn_fps_lmg_m1918_carry_handle" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_g_monitor"][i] = false end end end }) 
end 
T_a82e1f516c64345a = T_a82e1f516c64345a or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_a82e1f516c64345a__FMenu", name_id = "Loc_9b0872d85c16cb6e", inject_menu = "T_0a222a80f3ee080f__Menu", class = T_a82e1f516c64345a}) 
function T_a82e1f516c64345a:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["Invisible"] or false 
	self:Toggle({ name = "T_2e2fbb78e6109b4c", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["Forced"] or false 
	self:Toggle({ name = "T_66a6620f3182b921", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["wpn_fps_lmg_m1918_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["wpn_fps_lmg_m1918_m_standard"] or false 
	self:Toggle({ name = "T_f700e3e29c381cf2", text = "Loc_3934aa9c7f46e5cb", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["wpn_fps_lmg_m1918_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["wpn_fps_lmg_m1918_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["wpn_fps_lmg_m1918_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]["wpn_fps_lmg_m1918_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"]) do if i ~= "wpn_fps_lmg_m1918_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_m_extended"][i] = false end end end }) 
end 
T_1a55c15fb24ed72f = T_1a55c15fb24ed72f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_1a55c15fb24ed72f__FMenu", name_id = "Loc_2d8d69cee973182a", inject_menu = "T_0a222a80f3ee080f__Menu", class = T_1a55c15fb24ed72f}) 
function T_1a55c15fb24ed72f:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["Invisible"] or false 
	self:Toggle({ name = "T_d33221a67ebf8430", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["Forced"] or false 
	self:Toggle({ name = "T_018a76ab98b460eb", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["wpn_fps_lmg_m1918_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["wpn_fps_lmg_m1918_body_standard"] or false 
	self:Toggle({ name = "T_a8a7004ef47b5e57", text = "Loc_8bc0c9c3dcdefefb", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["wpn_fps_lmg_m1918_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["wpn_fps_lmg_m1918_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["wpn_fps_lmg_m1918_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["wpn_fps_lmg_m1918_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]) do if i ~= "wpn_fps_lmg_m1918_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["wpn_fps_lmg_m1918_g_monitor"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["wpn_fps_lmg_m1918_g_monitor"] or false 
	self:Toggle({ name = "T_c7ad1d3918654192", text = "Loc_65a92562b545ca1a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["wpn_fps_lmg_m1918_g_monitor"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["wpn_fps_lmg_m1918_g_monitor"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["wpn_fps_lmg_m1918_g_monitor"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]["wpn_fps_lmg_m1918_g_monitor"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"]) do if i ~= "wpn_fps_lmg_m1918_g_monitor" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_carry_handle"][i] = false end end end }) 
end 
T_14ad4715498b0010 = T_14ad4715498b0010 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_14ad4715498b0010__FMenu", name_id = "Loc_f17cd377e841658d", inject_menu = "T_0a222a80f3ee080f__Menu", class = T_14ad4715498b0010}) 
function T_14ad4715498b0010:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]["Invisible"] or false 
	self:Toggle({ name = "T_57e39dab680e71e5", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]["Forced"] or false 
	self:Toggle({ name = "T_c629a05163588907", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_m1918_bipod"][i] = false end end end }) 
end 
