WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_4383fb44cb36f593 = T_4383fb44cb36f593 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_4383fb44cb36f593__Menu", name_id = "bm_w_m1912", inject_menu = "WACApplyMyMenuMenu", class = T_4383fb44cb36f593}) 
T_43feabd6e44416ed = T_43feabd6e44416ed or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_43feabd6e44416ed__FMenu", name_id = "Loc_2293e9554c384efb", inject_menu = "T_4383fb44cb36f593__Menu", class = T_43feabd6e44416ed}) 
function T_43feabd6e44416ed:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_ad01601b4cf288b5", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_7094c6f1a38bda5a", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_long"] or false 
	self:Toggle({ name = "T_29800a0e55e924be", text = "Loc_882f87d4aff22dfc", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_long"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]) do if i ~= "wpn_fps_sho_m1912_b_long" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_short"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_short"] or false 
	self:Toggle({ name = "T_7e784af4140163ba", text = "Loc_dc22c402d778eae9", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_short"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]) do if i ~= "wpn_fps_sho_m1912_b_short" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_heat_shield"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_heat_shield"] or false 
	self:Toggle({ name = "T_baee13763bdaca1c", text = "Loc_1c94d12f07795cf7", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_heat_shield"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_heat_shield"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_heat_shield"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]["wpn_fps_sho_m1912_b_heat_shield"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"]) do if i ~= "wpn_fps_sho_m1912_b_heat_shield" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_standard"][i] = false end end end }) 
end 
T_0f338b35c24192b3 = T_0f338b35c24192b3 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_0f338b35c24192b3__FMenu", name_id = "Loc_13c6f2631025b223", inject_menu = "T_4383fb44cb36f593__Menu", class = T_0f338b35c24192b3}) 
function T_0f338b35c24192b3:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_58e9eefa0f406356", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_3f3e362bce704658", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_body_standard"][i] = false end end end }) 
end 
T_d7e20052d167b9a7 = T_d7e20052d167b9a7 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_d7e20052d167b9a7__FMenu", name_id = "Loc_4c4a533da0670cf4", inject_menu = "T_4383fb44cb36f593__Menu", class = T_d7e20052d167b9a7}) 
function T_d7e20052d167b9a7:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_2da99d2fa9a6345d", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]["Forced"] or false 
	self:Toggle({ name = "T_b5a2b017bb63a1af", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_bolt_standard"][i] = false end end end }) 
end 
T_4d91c04e03f6eda7 = T_4d91c04e03f6eda7 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_4d91c04e03f6eda7__FMenu", name_id = "Loc_bd384e602a109525", inject_menu = "T_4383fb44cb36f593__Menu", class = T_4d91c04e03f6eda7}) 
function T_4d91c04e03f6eda7:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_df1a3c9d8b380246", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["Forced"] or false 
	self:Toggle({ name = "T_762af90e0d5d4255", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["wpn_fps_sho_m1912_fg_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["wpn_fps_sho_m1912_fg_long"] or false 
	self:Toggle({ name = "T_62931394e8e9fe1b", text = "Loc_f93feabc8e0e4cf1", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["wpn_fps_sho_m1912_fg_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["wpn_fps_sho_m1912_fg_long"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["wpn_fps_sho_m1912_fg_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]["wpn_fps_sho_m1912_fg_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"]) do if i ~= "wpn_fps_sho_m1912_fg_long" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_standard"][i] = false end end end }) 
end 
T_82a877090b45d1bc = T_82a877090b45d1bc or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_82a877090b45d1bc__FMenu", name_id = "Loc_23b9c2622ffc5c8d", inject_menu = "T_4383fb44cb36f593__Menu", class = T_82a877090b45d1bc}) 
function T_82a877090b45d1bc:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_fab208ab53ebdb00", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_ef0568e6947ce938", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_m_standard"][i] = false end end end }) 
end 
T_0c98a0dc6946cf92 = T_0c98a0dc6946cf92 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_0c98a0dc6946cf92__FMenu", name_id = "Loc_b4a0edac27a1273b", inject_menu = "T_4383fb44cb36f593__Menu", class = T_0c98a0dc6946cf92}) 
function T_0c98a0dc6946cf92:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_6c1bff8cdd66947d", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["Forced"] or false 
	self:Toggle({ name = "T_d4aa98a37471b418", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["wpn_fps_sho_m1912_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["wpn_fps_sho_m1912_s_cheek_rest"] or false 
	self:Toggle({ name = "T_2fde535c218ed323", text = "Loc_c87e9c31b12523e2", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["wpn_fps_sho_m1912_s_cheek_rest"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["wpn_fps_sho_m1912_s_cheek_rest"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["wpn_fps_sho_m1912_s_cheek_rest"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["wpn_fps_sho_m1912_s_cheek_rest"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]) do if i ~= "wpn_fps_sho_m1912_s_cheek_rest" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["wpn_fps_sho_m1912_s_pistol_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["wpn_fps_sho_m1912_s_pistol_grip"] or false 
	self:Toggle({ name = "T_00c70730b930e2f6", text = "Loc_838310cb2a38985c", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["wpn_fps_sho_m1912_s_pistol_grip"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["wpn_fps_sho_m1912_s_pistol_grip"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["wpn_fps_sho_m1912_s_pistol_grip"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]["wpn_fps_sho_m1912_s_pistol_grip"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"]) do if i ~= "wpn_fps_sho_m1912_s_pistol_grip" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_standard"][i] = false end end end }) 
end 
T_de160c65ed810c3d = T_de160c65ed810c3d or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_de160c65ed810c3d__FMenu", name_id = "Loc_882f87d4aff22dfc", inject_menu = "T_4383fb44cb36f593__Menu", class = T_de160c65ed810c3d}) 
function T_de160c65ed810c3d:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["Invisible"] or false 
	self:Toggle({ name = "T_81aa8120318bbd23", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["Forced"] or false 
	self:Toggle({ name = "T_3b4e2eba701e3494", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_standard"] or false 
	self:Toggle({ name = "T_67617af93e9368b1", text = "Loc_2293e9554c384efb", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]) do if i ~= "wpn_fps_sho_m1912_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_short"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_short"] or false 
	self:Toggle({ name = "T_b2478f52f9de2562", text = "Loc_dc22c402d778eae9", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_short"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]) do if i ~= "wpn_fps_sho_m1912_b_short" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_heat_shield"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_heat_shield"] or false 
	self:Toggle({ name = "T_c8abab6388346428", text = "Loc_1c94d12f07795cf7", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_heat_shield"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_heat_shield"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_heat_shield"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]["wpn_fps_sho_m1912_b_heat_shield"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"]) do if i ~= "wpn_fps_sho_m1912_b_heat_shield" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_long"][i] = false end end end }) 
end 
T_93e3718b87527250 = T_93e3718b87527250 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_93e3718b87527250__FMenu", name_id = "Loc_dc22c402d778eae9", inject_menu = "T_4383fb44cb36f593__Menu", class = T_93e3718b87527250}) 
function T_93e3718b87527250:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["Invisible"] or false 
	self:Toggle({ name = "T_022cd1b8d372af40", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["Forced"] or false 
	self:Toggle({ name = "T_bb6d1cd9a8d645b2", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_standard"] or false 
	self:Toggle({ name = "T_9c3094ed8fe1a294", text = "Loc_2293e9554c384efb", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]) do if i ~= "wpn_fps_sho_m1912_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_long"] or false 
	self:Toggle({ name = "T_b2582df585c480a9", text = "Loc_882f87d4aff22dfc", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_long"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]) do if i ~= "wpn_fps_sho_m1912_b_long" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_heat_shield"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_heat_shield"] or false 
	self:Toggle({ name = "T_ddfecd24e696278c", text = "Loc_1c94d12f07795cf7", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_heat_shield"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_heat_shield"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_heat_shield"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]["wpn_fps_sho_m1912_b_heat_shield"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"]) do if i ~= "wpn_fps_sho_m1912_b_heat_shield" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_short"][i] = false end end end }) 
end 
T_5d69e385e7cf54a5 = T_5d69e385e7cf54a5 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_5d69e385e7cf54a5__FMenu", name_id = "Loc_70b8dda332708fce", inject_menu = "T_4383fb44cb36f593__Menu", class = T_5d69e385e7cf54a5}) 
function T_5d69e385e7cf54a5:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]["Invisible"] or false 
	self:Toggle({ name = "T_12aaaa48c3931d99", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]["Forced"] or false 
	self:Toggle({ name = "T_a57a89a4d4cc1d40", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_ns_cutts"][i] = false end end end }) 
end 
T_f7276751acd41a83 = T_f7276751acd41a83 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_f7276751acd41a83__FMenu", name_id = "Loc_c87e9c31b12523e2", inject_menu = "T_4383fb44cb36f593__Menu", class = T_f7276751acd41a83}) 
function T_f7276751acd41a83:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["Invisible"] or false 
	self:Toggle({ name = "T_495ac01e3f667f43", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["Forced"] or false 
	self:Toggle({ name = "T_7e83669357f4e0b4", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["wpn_fps_sho_m1912_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["wpn_fps_sho_m1912_s_standard"] or false 
	self:Toggle({ name = "T_16604ae3755325d4", text = "Loc_b4a0edac27a1273b", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["wpn_fps_sho_m1912_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["wpn_fps_sho_m1912_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["wpn_fps_sho_m1912_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["wpn_fps_sho_m1912_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]) do if i ~= "wpn_fps_sho_m1912_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["wpn_fps_sho_m1912_s_pistol_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["wpn_fps_sho_m1912_s_pistol_grip"] or false 
	self:Toggle({ name = "T_8c24ea65e497c96e", text = "Loc_838310cb2a38985c", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["wpn_fps_sho_m1912_s_pistol_grip"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["wpn_fps_sho_m1912_s_pistol_grip"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["wpn_fps_sho_m1912_s_pistol_grip"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]["wpn_fps_sho_m1912_s_pistol_grip"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"]) do if i ~= "wpn_fps_sho_m1912_s_pistol_grip" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_cheek_rest"][i] = false end end end }) 
end 
T_f8d15247235b2dd1 = T_f8d15247235b2dd1 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_f8d15247235b2dd1__FMenu", name_id = "Loc_b3ab1ea6d0aa77b3", inject_menu = "T_4383fb44cb36f593__Menu", class = T_f8d15247235b2dd1}) 
function T_f8d15247235b2dd1:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]["Invisible"] or false 
	self:Toggle({ name = "T_bf34ee74673175f5", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]["Forced"] or false 
	self:Toggle({ name = "T_7134e9f651f69392", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pad"][i] = false end end end }) 
end 
T_b3a06f67ac54575b = T_b3a06f67ac54575b or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b3a06f67ac54575b__FMenu", name_id = "Loc_838310cb2a38985c", inject_menu = "T_4383fb44cb36f593__Menu", class = T_b3a06f67ac54575b}) 
function T_b3a06f67ac54575b:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["Invisible"] or false 
	self:Toggle({ name = "T_97a37fc8e5ec4c89", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["Forced"] or false 
	self:Toggle({ name = "T_106df6818319d114", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["wpn_fps_sho_m1912_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["wpn_fps_sho_m1912_s_standard"] or false 
	self:Toggle({ name = "T_d96ef35227910389", text = "Loc_b4a0edac27a1273b", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["wpn_fps_sho_m1912_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["wpn_fps_sho_m1912_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["wpn_fps_sho_m1912_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["wpn_fps_sho_m1912_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]) do if i ~= "wpn_fps_sho_m1912_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["wpn_fps_sho_m1912_s_cheek_rest"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["wpn_fps_sho_m1912_s_cheek_rest"] or false 
	self:Toggle({ name = "T_f880508eba74e3f6", text = "Loc_c87e9c31b12523e2", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["wpn_fps_sho_m1912_s_cheek_rest"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["wpn_fps_sho_m1912_s_cheek_rest"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["wpn_fps_sho_m1912_s_cheek_rest"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]["wpn_fps_sho_m1912_s_cheek_rest"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"]) do if i ~= "wpn_fps_sho_m1912_s_cheek_rest" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_s_pistol_grip"][i] = false end end end }) 
end 
T_b3eeeb14e6e73987 = T_b3eeeb14e6e73987 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b3eeeb14e6e73987__FMenu", name_id = "Loc_1c94d12f07795cf7", inject_menu = "T_4383fb44cb36f593__Menu", class = T_b3eeeb14e6e73987}) 
function T_b3eeeb14e6e73987:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["Invisible"] or false 
	self:Toggle({ name = "T_0616b871c86765a2", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["Forced"] or false 
	self:Toggle({ name = "T_040261ac9167bd5d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_standard"] or false 
	self:Toggle({ name = "T_c652c21cf94d74ec", text = "Loc_2293e9554c384efb", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]) do if i ~= "wpn_fps_sho_m1912_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_long"] or false 
	self:Toggle({ name = "T_8faef4aef886c0d5", text = "Loc_882f87d4aff22dfc", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_long"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]) do if i ~= "wpn_fps_sho_m1912_b_long" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_short"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_short"] or false 
	self:Toggle({ name = "T_b416bed92cf859a9", text = "Loc_dc22c402d778eae9", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_short"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]["wpn_fps_sho_m1912_b_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"]) do if i ~= "wpn_fps_sho_m1912_b_short" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_b_heat_shield"][i] = false end end end }) 
end 
T_0fd45e977d3ebc27 = T_0fd45e977d3ebc27 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_0fd45e977d3ebc27__FMenu", name_id = "Loc_f93feabc8e0e4cf1", inject_menu = "T_4383fb44cb36f593__Menu", class = T_0fd45e977d3ebc27}) 
function T_0fd45e977d3ebc27:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["Invisible"] or false 
	self:Toggle({ name = "T_cc85eee63299353a", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["Forced"] or false 
	self:Toggle({ name = "T_26a151b5e59516c0", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["wpn_fps_sho_m1912_fg_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["wpn_fps_sho_m1912_fg_standard"] or false 
	self:Toggle({ name = "T_3459bf65346286e1", text = "Loc_bd384e602a109525", value = WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["wpn_fps_sho_m1912_fg_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["wpn_fps_sho_m1912_fg_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["wpn_fps_sho_m1912_fg_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]["wpn_fps_sho_m1912_fg_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"]) do if i ~= "wpn_fps_sho_m1912_fg_standard" then WACApplyMyMenu._settings._apply["wpn_fps_sho_m1912_fg_long"][i] = false end end end }) 
end 
