WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_2e072d8e07ce3acb = T_2e072d8e07ce3acb or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_2e072d8e07ce3acb__Menu", name_id = "bm_w_m1911", inject_menu = "WACApplyMyMenuMenu", class = T_2e072d8e07ce3acb}) 
T_b877656f1349868b = T_b877656f1349868b or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b877656f1349868b__FMenu", name_id = "Loc_0f189d42e6249118", inject_menu = "T_2e072d8e07ce3acb__Menu", class = T_b877656f1349868b}) 
function T_b877656f1349868b:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_b12987fd746a24ae", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_176ab4f3fedfe868", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["wpn_fps_pis_m1911_fg_tommy"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["wpn_fps_pis_m1911_fg_tommy"] or false 
	self:Toggle({ name = "T_446ad253257dbb96", text = "Loc_0ad04b240e520445", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["wpn_fps_pis_m1911_fg_tommy"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["wpn_fps_pis_m1911_fg_tommy"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["wpn_fps_pis_m1911_fg_tommy"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["wpn_fps_pis_m1911_fg_tommy"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]) do if i ~= "wpn_fps_pis_m1911_fg_tommy" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["wpn_fps_pis_m1911_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["wpn_fps_pis_m1911_s_wooden"] or false 
	self:Toggle({ name = "T_ef1615a12956a54e", text = "Loc_80b72cb6d2609c58", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["wpn_fps_pis_m1911_s_wooden"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["wpn_fps_pis_m1911_s_wooden"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["wpn_fps_pis_m1911_s_wooden"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]["wpn_fps_pis_m1911_s_wooden"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"]) do if i ~= "wpn_fps_pis_m1911_s_wooden" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_body_standard"][i] = false end end end }) 
end 
T_9e4ccf88da97c1be = T_9e4ccf88da97c1be or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_9e4ccf88da97c1be__FMenu", name_id = "Loc_3634196e1cbdf072", inject_menu = "T_2e072d8e07ce3acb__Menu", class = T_9e4ccf88da97c1be}) 
function T_9e4ccf88da97c1be:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_aead4a791547d256", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_ee2e8ea1eeba4b33", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_b_standard"][i] = false end end end }) 
end 
T_84e890e8a319a35d = T_84e890e8a319a35d or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_84e890e8a319a35d__FMenu", name_id = "Loc_b42030e04118ea09", inject_menu = "T_2e072d8e07ce3acb__Menu", class = T_84e890e8a319a35d}) 
function T_84e890e8a319a35d:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_6eddd427f994c0bb", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]["Forced"] or false 
	self:Toggle({ name = "T_44d86aa64e141bfe", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_sl_standard"][i] = false end end end }) 
end 
T_cfd9e208e5d7effc = T_cfd9e208e5d7effc or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_cfd9e208e5d7effc__FMenu", name_id = "Loc_2b0e17562f4fbbbe", inject_menu = "T_2e072d8e07ce3acb__Menu", class = T_cfd9e208e5d7effc}) 
function T_cfd9e208e5d7effc:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_68920d65c5bbfcb2", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_0d8d8b1043003ce4", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["wpn_fps_pis_m1911_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["wpn_fps_pis_m1911_m_extended"] or false 
	self:Toggle({ name = "T_f01c6744cb63fb7e", text = "Loc_adaf3365eeaa7a9f", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["wpn_fps_pis_m1911_m_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["wpn_fps_pis_m1911_m_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["wpn_fps_pis_m1911_m_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["wpn_fps_pis_m1911_m_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]) do if i ~= "wpn_fps_pis_m1911_m_extended" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["wpn_fps_pis_m1911_m_banana"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["wpn_fps_pis_m1911_m_banana"] or false 
	self:Toggle({ name = "T_bc922e39e57adb23", text = "Loc_78a1d2ed20bc80fe", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["wpn_fps_pis_m1911_m_banana"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["wpn_fps_pis_m1911_m_banana"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["wpn_fps_pis_m1911_m_banana"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]["wpn_fps_pis_m1911_m_banana"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"]) do if i ~= "wpn_fps_pis_m1911_m_banana" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_standard"][i] = false end end end }) 
end 
T_dc839e07024479db = T_dc839e07024479db or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_dc839e07024479db__FMenu", name_id = "Loc_da8170caf2cae75f", inject_menu = "T_2e072d8e07ce3acb__Menu", class = T_dc839e07024479db}) 
function T_dc839e07024479db:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]["Invisible"] or false 
	self:Toggle({ name = "T_90c7bde116e694e3", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]["Forced"] or false 
	self:Toggle({ name = "T_65a374a47db46e62", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_dh_hammer"][i] = false end end end }) 
end 
T_d9ea6f1d2c72b253 = T_d9ea6f1d2c72b253 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_d9ea6f1d2c72b253__FMenu", name_id = "Loc_adaf3365eeaa7a9f", inject_menu = "T_2e072d8e07ce3acb__Menu", class = T_d9ea6f1d2c72b253}) 
function T_d9ea6f1d2c72b253:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["Invisible"] or false 
	self:Toggle({ name = "T_4dbbbc9e56ac8c73", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["Forced"] or false 
	self:Toggle({ name = "T_856acfbcfc9f50bf", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["wpn_fps_pis_m1911_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["wpn_fps_pis_m1911_m_standard"] or false 
	self:Toggle({ name = "T_a2efc6788a69146c", text = "Loc_2b0e17562f4fbbbe", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["wpn_fps_pis_m1911_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["wpn_fps_pis_m1911_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["wpn_fps_pis_m1911_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["wpn_fps_pis_m1911_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]) do if i ~= "wpn_fps_pis_m1911_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["wpn_fps_pis_m1911_m_banana"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["wpn_fps_pis_m1911_m_banana"] or false 
	self:Toggle({ name = "T_fbd4f115e163b82c", text = "Loc_78a1d2ed20bc80fe", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["wpn_fps_pis_m1911_m_banana"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["wpn_fps_pis_m1911_m_banana"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["wpn_fps_pis_m1911_m_banana"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]["wpn_fps_pis_m1911_m_banana"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"]) do if i ~= "wpn_fps_pis_m1911_m_banana" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_extended"][i] = false end end end }) 
end 
T_c93d6c035bd29b7c = T_c93d6c035bd29b7c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_c93d6c035bd29b7c__FMenu", name_id = "Loc_78a1d2ed20bc80fe", inject_menu = "T_2e072d8e07ce3acb__Menu", class = T_c93d6c035bd29b7c}) 
function T_c93d6c035bd29b7c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["Invisible"] or false 
	self:Toggle({ name = "T_64a27ce3e6ee5f58", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["Forced"] or false 
	self:Toggle({ name = "T_a5dba90a251e42bf", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["wpn_fps_pis_m1911_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["wpn_fps_pis_m1911_m_standard"] or false 
	self:Toggle({ name = "T_d9f02d84395fa3b3", text = "Loc_2b0e17562f4fbbbe", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["wpn_fps_pis_m1911_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["wpn_fps_pis_m1911_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["wpn_fps_pis_m1911_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["wpn_fps_pis_m1911_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]) do if i ~= "wpn_fps_pis_m1911_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["wpn_fps_pis_m1911_m_extended"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["wpn_fps_pis_m1911_m_extended"] or false 
	self:Toggle({ name = "T_f48c036917dc7d96", text = "Loc_adaf3365eeaa7a9f", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["wpn_fps_pis_m1911_m_extended"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["wpn_fps_pis_m1911_m_extended"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["wpn_fps_pis_m1911_m_extended"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]["wpn_fps_pis_m1911_m_extended"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"]) do if i ~= "wpn_fps_pis_m1911_m_extended" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_m_banana"][i] = false end end end }) 
end 
T_3cb817f73bc02793 = T_3cb817f73bc02793 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_3cb817f73bc02793__FMenu", name_id = "Loc_16d88a335fb91594", inject_menu = "T_2e072d8e07ce3acb__Menu", class = T_3cb817f73bc02793}) 
function T_3cb817f73bc02793:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]["Invisible"] or false 
	self:Toggle({ name = "T_d03dfd4b28333fb8", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]["Forced"] or false 
	self:Toggle({ name = "T_a1067d13cc110fdb", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_ns_cutts"][i] = false end end end }) 
end 
T_cccede39a38efd4f = T_cccede39a38efd4f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_cccede39a38efd4f__FMenu", name_id = "Loc_0ad04b240e520445", inject_menu = "T_2e072d8e07ce3acb__Menu", class = T_cccede39a38efd4f}) 
function T_cccede39a38efd4f:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["Invisible"] or false 
	self:Toggle({ name = "T_86c345e00e4171fb", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["Forced"] or false 
	self:Toggle({ name = "T_86b264e67ddc92dd", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["wpn_fps_pis_m1911_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["wpn_fps_pis_m1911_body_standard"] or false 
	self:Toggle({ name = "T_242e5530a14b32f1", text = "Loc_0f189d42e6249118", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["wpn_fps_pis_m1911_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["wpn_fps_pis_m1911_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["wpn_fps_pis_m1911_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["wpn_fps_pis_m1911_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]) do if i ~= "wpn_fps_pis_m1911_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["wpn_fps_pis_m1911_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["wpn_fps_pis_m1911_s_wooden"] or false 
	self:Toggle({ name = "T_e1c297954d2c8567", text = "Loc_80b72cb6d2609c58", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["wpn_fps_pis_m1911_s_wooden"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["wpn_fps_pis_m1911_s_wooden"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["wpn_fps_pis_m1911_s_wooden"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]["wpn_fps_pis_m1911_s_wooden"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"]) do if i ~= "wpn_fps_pis_m1911_s_wooden" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_fg_tommy"][i] = false end end end }) 
end 
T_0434e16acd07e381 = T_0434e16acd07e381 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_0434e16acd07e381__FMenu", name_id = "Loc_80b72cb6d2609c58", inject_menu = "T_2e072d8e07ce3acb__Menu", class = T_0434e16acd07e381}) 
function T_0434e16acd07e381:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["Invisible"] or false 
	self:Toggle({ name = "T_e4edd06e3322b610", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["Forced"] or false 
	self:Toggle({ name = "T_cd4b8d54da4af57b", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["wpn_fps_pis_m1911_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["wpn_fps_pis_m1911_body_standard"] or false 
	self:Toggle({ name = "T_14a5fe51cf03dda4", text = "Loc_0f189d42e6249118", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["wpn_fps_pis_m1911_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["wpn_fps_pis_m1911_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["wpn_fps_pis_m1911_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["wpn_fps_pis_m1911_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]) do if i ~= "wpn_fps_pis_m1911_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["wpn_fps_pis_m1911_fg_tommy"] = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["wpn_fps_pis_m1911_fg_tommy"] or false 
	self:Toggle({ name = "T_75a8d07609042286", text = "Loc_0ad04b240e520445", value = WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["wpn_fps_pis_m1911_fg_tommy"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["wpn_fps_pis_m1911_fg_tommy"] then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["wpn_fps_pis_m1911_fg_tommy"] = false else WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]["wpn_fps_pis_m1911_fg_tommy"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"]) do if i ~= "wpn_fps_pis_m1911_fg_tommy" then WACApplyMyMenu._settings._apply["wpn_fps_pis_m1911_s_wooden"][i] = false end end end }) 
end 
