WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_88f339ecefad6311 = T_88f339ecefad6311 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_88f339ecefad6311__Menu", name_id = "bm_w_mp38", inject_menu = "WACApplyMyMenuMenu", class = T_88f339ecefad6311}) 
T_44c0b03109cff53c = T_44c0b03109cff53c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_44c0b03109cff53c__FMenu", name_id = "Loc_1dfc6319ff6460d4", inject_menu = "T_88f339ecefad6311__Menu", class = T_44c0b03109cff53c}) 
function T_44c0b03109cff53c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_1278f95729ac6417", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_255724060525dc98", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["wpn_fps_smg_mp38_b_compensated"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["wpn_fps_smg_mp38_b_compensated"] or false 
	self:Toggle({ name = "T_25159c226e7d8e37", text = "Loc_f1ea813870d737f8", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["wpn_fps_smg_mp38_b_compensated"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["wpn_fps_smg_mp38_b_compensated"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["wpn_fps_smg_mp38_b_compensated"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["wpn_fps_smg_mp38_b_compensated"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]) do if i ~= "wpn_fps_smg_mp38_b_compensated" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["wpn_fps_smg_mp38_b_fluted"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["wpn_fps_smg_mp38_b_fluted"] or false 
	self:Toggle({ name = "T_3dfed2fc4f23da68", text = "Loc_8498ed850c75932c", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["wpn_fps_smg_mp38_b_fluted"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["wpn_fps_smg_mp38_b_fluted"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["wpn_fps_smg_mp38_b_fluted"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]["wpn_fps_smg_mp38_b_fluted"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"]) do if i ~= "wpn_fps_smg_mp38_b_fluted" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_standard"][i] = false end end end }) 
end 
T_1bb49048270d4d2d = T_1bb49048270d4d2d or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_1bb49048270d4d2d__FMenu", name_id = "Loc_581d792850941222", inject_menu = "T_88f339ecefad6311__Menu", class = T_1bb49048270d4d2d}) 
function T_1bb49048270d4d2d:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_83d988c546319cf2", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_41252170c6f738f3", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_body_standard"][i] = false end end end }) 
end 
T_8d9f7615959e0952 = T_8d9f7615959e0952 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_8d9f7615959e0952__FMenu", name_id = "Loc_e81721ee0561d6db", inject_menu = "T_88f339ecefad6311__Menu", class = T_8d9f7615959e0952}) 
function T_8d9f7615959e0952:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_aeee2a7daf9b70b7", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_b0c14cdbc83c860b", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["wpn_fps_smg_mp38_dh_curved"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["wpn_fps_smg_mp38_dh_curved"] or false 
	self:Toggle({ name = "T_e54a68d837a45918", text = "Loc_23d4f41957e31418", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["wpn_fps_smg_mp38_dh_curved"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["wpn_fps_smg_mp38_dh_curved"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["wpn_fps_smg_mp38_dh_curved"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]["wpn_fps_smg_mp38_dh_curved"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"]) do if i ~= "wpn_fps_smg_mp38_dh_curved" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_standard"][i] = false end end end }) 
end 
T_03920249ecea2453 = T_03920249ecea2453 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_03920249ecea2453__FMenu", name_id = "Loc_7094cc69b9646197", inject_menu = "T_88f339ecefad6311__Menu", class = T_03920249ecea2453}) 
function T_03920249ecea2453:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_893c415846916fbb", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_f0c4d1427993db9e", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["wpn_fps_smg_mp38_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["wpn_fps_smg_mp38_m_standard_double"] or false 
	self:Toggle({ name = "T_3c9090e6c81c9bc1", text = "Loc_a9e7d4bb11809086", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["wpn_fps_smg_mp38_m_standard_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["wpn_fps_smg_mp38_m_standard_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["wpn_fps_smg_mp38_m_standard_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]["wpn_fps_smg_mp38_m_standard_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"]) do if i ~= "wpn_fps_smg_mp38_m_standard_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard"][i] = false end end end }) 
end 
T_0bee92be054704f9 = T_0bee92be054704f9 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_0bee92be054704f9__FMenu", name_id = "Loc_9ee192d16f3d39ee", inject_menu = "T_88f339ecefad6311__Menu", class = T_0bee92be054704f9}) 
function T_0bee92be054704f9:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_d44b1ca1bebdd3d9", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["Forced"] or false 
	self:Toggle({ name = "T_00a88e6694fa5bc3", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["wpn_fps_smg_mp38_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["wpn_fps_smg_mp38_s_wooden"] or false 
	self:Toggle({ name = "T_3b693b4b487479ee", text = "Loc_5e1df0054adc0bc1", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["wpn_fps_smg_mp38_s_wooden"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["wpn_fps_smg_mp38_s_wooden"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["wpn_fps_smg_mp38_s_wooden"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]["wpn_fps_smg_mp38_s_wooden"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"]) do if i ~= "wpn_fps_smg_mp38_s_wooden" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_standard"][i] = false end end end }) 
end 
T_d22e544d0fc8e061 = T_d22e544d0fc8e061 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_d22e544d0fc8e061__FMenu", name_id = "Loc_a9e7d4bb11809086", inject_menu = "T_88f339ecefad6311__Menu", class = T_d22e544d0fc8e061}) 
function T_d22e544d0fc8e061:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["Invisible"] or false 
	self:Toggle({ name = "T_4681da9b27ea7743", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["Forced"] or false 
	self:Toggle({ name = "T_c537c96a02ff5da9", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["wpn_fps_smg_mp38_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["wpn_fps_smg_mp38_m_standard"] or false 
	self:Toggle({ name = "T_c25fba8d57fd4f40", text = "Loc_7094cc69b9646197", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["wpn_fps_smg_mp38_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["wpn_fps_smg_mp38_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["wpn_fps_smg_mp38_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]["wpn_fps_smg_mp38_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"]) do if i ~= "wpn_fps_smg_mp38_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_m_standard_double"][i] = false end end end }) 
end 
T_1a2f8d8eb6a8bfae = T_1a2f8d8eb6a8bfae or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_1a2f8d8eb6a8bfae__FMenu", name_id = "Loc_23d4f41957e31418", inject_menu = "T_88f339ecefad6311__Menu", class = T_1a2f8d8eb6a8bfae}) 
function T_1a2f8d8eb6a8bfae:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["Invisible"] or false 
	self:Toggle({ name = "T_5bf5e474e77e5e6b", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["Forced"] or false 
	self:Toggle({ name = "T_28f90784ab82912e", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["wpn_fps_smg_mp38_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["wpn_fps_smg_mp38_dh_standard"] or false 
	self:Toggle({ name = "T_c695906d107a7f38", text = "Loc_e81721ee0561d6db", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["wpn_fps_smg_mp38_dh_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["wpn_fps_smg_mp38_dh_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["wpn_fps_smg_mp38_dh_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]["wpn_fps_smg_mp38_dh_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"]) do if i ~= "wpn_fps_smg_mp38_dh_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_dh_curved"][i] = false end end end }) 
end 
T_ee94c0514ffc1d81 = T_ee94c0514ffc1d81 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_ee94c0514ffc1d81__FMenu", name_id = "Loc_f1ea813870d737f8", inject_menu = "T_88f339ecefad6311__Menu", class = T_ee94c0514ffc1d81}) 
function T_ee94c0514ffc1d81:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["Invisible"] or false 
	self:Toggle({ name = "T_c6ca8d9bda4d8c38", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["Forced"] or false 
	self:Toggle({ name = "T_c59b3c92cb1593ac", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["wpn_fps_smg_mp38_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["wpn_fps_smg_mp38_b_standard"] or false 
	self:Toggle({ name = "T_1d6ef183ffb65ef7", text = "Loc_1dfc6319ff6460d4", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["wpn_fps_smg_mp38_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["wpn_fps_smg_mp38_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["wpn_fps_smg_mp38_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["wpn_fps_smg_mp38_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]) do if i ~= "wpn_fps_smg_mp38_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["wpn_fps_smg_mp38_b_fluted"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["wpn_fps_smg_mp38_b_fluted"] or false 
	self:Toggle({ name = "T_1b944f09870f9b4d", text = "Loc_8498ed850c75932c", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["wpn_fps_smg_mp38_b_fluted"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["wpn_fps_smg_mp38_b_fluted"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["wpn_fps_smg_mp38_b_fluted"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]["wpn_fps_smg_mp38_b_fluted"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"]) do if i ~= "wpn_fps_smg_mp38_b_fluted" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_compensated"][i] = false end end end }) 
end 
T_59d16604f199d07a = T_59d16604f199d07a or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_59d16604f199d07a__FMenu", name_id = "Loc_8498ed850c75932c", inject_menu = "T_88f339ecefad6311__Menu", class = T_59d16604f199d07a}) 
function T_59d16604f199d07a:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["Invisible"] or false 
	self:Toggle({ name = "T_5a27953fbd4c1b3c", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["Forced"] or false 
	self:Toggle({ name = "T_3d738829f6f66b6a", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["wpn_fps_smg_mp38_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["wpn_fps_smg_mp38_b_standard"] or false 
	self:Toggle({ name = "T_a891daf8a2729c3b", text = "Loc_1dfc6319ff6460d4", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["wpn_fps_smg_mp38_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["wpn_fps_smg_mp38_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["wpn_fps_smg_mp38_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["wpn_fps_smg_mp38_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]) do if i ~= "wpn_fps_smg_mp38_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["wpn_fps_smg_mp38_b_compensated"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["wpn_fps_smg_mp38_b_compensated"] or false 
	self:Toggle({ name = "T_0bc7da0cb6da054f", text = "Loc_f1ea813870d737f8", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["wpn_fps_smg_mp38_b_compensated"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["wpn_fps_smg_mp38_b_compensated"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["wpn_fps_smg_mp38_b_compensated"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]["wpn_fps_smg_mp38_b_compensated"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"]) do if i ~= "wpn_fps_smg_mp38_b_compensated" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_b_fluted"][i] = false end end end }) 
end 
T_d0f2959fb6d456cd = T_d0f2959fb6d456cd or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_d0f2959fb6d456cd__FMenu", name_id = "Loc_5e1df0054adc0bc1", inject_menu = "T_88f339ecefad6311__Menu", class = T_d0f2959fb6d456cd}) 
function T_d0f2959fb6d456cd:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["Invisible"] or false 
	self:Toggle({ name = "T_e095bb6f1c285c12", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["Forced"] or false 
	self:Toggle({ name = "T_2297eb04e159810c", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["wpn_fps_smg_mp38_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["wpn_fps_smg_mp38_s_standard"] or false 
	self:Toggle({ name = "T_e6ade96c9516ef25", text = "Loc_9ee192d16f3d39ee", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["wpn_fps_smg_mp38_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["wpn_fps_smg_mp38_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["wpn_fps_smg_mp38_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]["wpn_fps_smg_mp38_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"]) do if i ~= "wpn_fps_smg_mp38_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_mp38_s_wooden"][i] = false end end end }) 
end 
