WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_86e41a2044e60970 = T_86e41a2044e60970 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_86e41a2044e60970__Menu", name_id = "bm_w_mg42", inject_menu = "WACApplyMyMenuMenu", class = T_86e41a2044e60970}) 
T_5a6192953003c106 = T_5a6192953003c106 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_5a6192953003c106__FMenu", name_id = "Loc_d63cd805baad6f76", inject_menu = "T_86e41a2044e60970__Menu", class = T_5a6192953003c106}) 
function T_5a6192953003c106:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["Invisible"] or false 
	self:Toggle({ name = "T_5811ad572b6e55f6", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["Forced"] or false 
	self:Toggle({ name = "T_47117a45f47e45ee", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["wpn_fps_lmg_mg42_b_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["wpn_fps_lmg_mg42_b_mg34"] or false 
	self:Toggle({ name = "T_accbf3ef3283295e", text = "Loc_6e6804823892f5ba", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["wpn_fps_lmg_mg42_b_mg34"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["wpn_fps_lmg_mg42_b_mg34"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["wpn_fps_lmg_mg42_b_mg34"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]["wpn_fps_lmg_mg42_b_mg34"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"]) do if i ~= "wpn_fps_lmg_mg42_b_mg34" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg42"][i] = false end end end }) 
end 
T_04291b1a28872c06 = T_04291b1a28872c06 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_04291b1a28872c06__FMenu", name_id = "Loc_949ff80429a00f02", inject_menu = "T_86e41a2044e60970__Menu", class = T_04291b1a28872c06}) 
function T_04291b1a28872c06:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["Invisible"] or false 
	self:Toggle({ name = "T_eb0f42b5ffad9e6e", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["Forced"] or false 
	self:Toggle({ name = "T_4223d0489c009765", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["wpn_fps_lmg_mg42_n34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["wpn_fps_lmg_mg42_n34"] or false 
	self:Toggle({ name = "T_75e435f201446de7", text = "Loc_adb0b24585ae34f7", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["wpn_fps_lmg_mg42_n34"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["wpn_fps_lmg_mg42_n34"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["wpn_fps_lmg_mg42_n34"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]["wpn_fps_lmg_mg42_n34"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"]) do if i ~= "wpn_fps_lmg_mg42_n34" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n42"][i] = false end end end }) 
end 
T_3ba754cfb98b37e8 = T_3ba754cfb98b37e8 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_3ba754cfb98b37e8__FMenu", name_id = "Loc_d9188963aceef231", inject_menu = "T_86e41a2044e60970__Menu", class = T_3ba754cfb98b37e8}) 
function T_3ba754cfb98b37e8:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["Invisible"] or false 
	self:Toggle({ name = "T_6ce9bfb998cd82e9", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["Forced"] or false 
	self:Toggle({ name = "T_af1155f80240c4a8", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_dh_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_dh_mg34"] or false 
	self:Toggle({ name = "T_971ee208c8f9acc7", text = "Loc_d2aaf56792ce5445", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_dh_mg34"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_dh_mg34"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_dh_mg34"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_dh_mg34"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]) do if i ~= "wpn_fps_lmg_mg42_dh_mg34" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_m_double"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_m_double"] or false 
	self:Toggle({ name = "T_b62abcc5edaccf00", text = "Loc_0f52ad045f7c1f40", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_m_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_m_double"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_m_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_m_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]) do if i ~= "wpn_fps_lmg_mg42_m_double" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_lid_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_lid_mg34"] or false 
	self:Toggle({ name = "T_b6adfd9dc64b737b", text = "Loc_7b28204641649bcf", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_lid_mg34"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_lid_mg34"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_lid_mg34"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]["wpn_fps_lmg_mg42_lid_mg34"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"]) do if i ~= "wpn_fps_lmg_mg42_lid_mg34" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_receiver"][i] = false end end end }) 
end 
T_22f56261621d64af = T_22f56261621d64af or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_22f56261621d64af__FMenu", name_id = "Loc_c1d62d0aa3cfc338", inject_menu = "T_86e41a2044e60970__Menu", class = T_22f56261621d64af}) 
function T_22f56261621d64af:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_60048bc2eef438a4", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]["Forced"] or false 
	self:Toggle({ name = "T_a1fbb126987d3b2f", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_standard"][i] = false end end end }) 
end 
T_c77ecae20ecd1e2d = T_c77ecae20ecd1e2d or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_c77ecae20ecd1e2d__FMenu", name_id = "Loc_50db1f5a68297c6d", inject_menu = "T_86e41a2044e60970__Menu", class = T_c77ecae20ecd1e2d}) 
function T_c77ecae20ecd1e2d:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_646ff9a0c8431bf4", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_bb73d2733e950f67", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_standard"][i] = false end end end }) 
end 
T_1296fdc5b0a84a0f = T_1296fdc5b0a84a0f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_1296fdc5b0a84a0f__FMenu", name_id = "Loc_3473dec3c5c4765b", inject_menu = "T_86e41a2044e60970__Menu", class = T_1296fdc5b0a84a0f}) 
function T_1296fdc5b0a84a0f:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]["Invisible"] or false 
	self:Toggle({ name = "T_1487d609b007dd2d", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]["Forced"] or false 
	self:Toggle({ name = "T_c353a0a41d0b4ff1", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_extra"][i] = false end end end }) 
end 
T_8a52de8c2fd6f9af = T_8a52de8c2fd6f9af or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_8a52de8c2fd6f9af__FMenu", name_id = "Loc_eb7b351a83b1f49d", inject_menu = "T_86e41a2044e60970__Menu", class = T_8a52de8c2fd6f9af}) 
function T_8a52de8c2fd6f9af:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_94a501609837d0fe", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_e266535b32300802", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_standard"][i] = false end end end }) 
end 
T_5281919ab34e9805 = T_5281919ab34e9805 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_5281919ab34e9805__FMenu", name_id = "Loc_3046ec5e70be22d2", inject_menu = "T_86e41a2044e60970__Menu", class = T_5281919ab34e9805}) 
function T_5281919ab34e9805:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]["Invisible"] or false 
	self:Toggle({ name = "T_f23f41a6b02d414a", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]["Forced"] or false 
	self:Toggle({ name = "T_24a9e934c91287cb", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_handle"][i] = false end end end }) 
end 
T_df163a0dccc03dd3 = T_df163a0dccc03dd3 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_df163a0dccc03dd3__FMenu", name_id = "Loc_4f27316ed949c858", inject_menu = "T_86e41a2044e60970__Menu", class = T_df163a0dccc03dd3}) 
function T_df163a0dccc03dd3:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]["Invisible"] or false 
	self:Toggle({ name = "T_735074efdbdaaafb", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]["Forced"] or false 
	self:Toggle({ name = "T_c9ccee6a87f957e5", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_1"][i] = false end end end }) 
end 
T_f6055bdcb81d9af7 = T_f6055bdcb81d9af7 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_f6055bdcb81d9af7__FMenu", name_id = "Loc_7f3b9fd2944d49d8", inject_menu = "T_86e41a2044e60970__Menu", class = T_f6055bdcb81d9af7}) 
function T_f6055bdcb81d9af7:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]["Invisible"] or false 
	self:Toggle({ name = "T_4b9a7f1cb9d5e8f7", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]["Forced"] or false 
	self:Toggle({ name = "T_c52a8f83cb6e23ef", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_2"][i] = false end end end }) 
end 
T_5f720db83a535836 = T_5f720db83a535836 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_5f720db83a535836__FMenu", name_id = "Loc_9d6688f57fdf08fe", inject_menu = "T_86e41a2044e60970__Menu", class = T_5f720db83a535836}) 
function T_5f720db83a535836:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]["Invisible"] or false 
	self:Toggle({ name = "T_7ad0d480cff2f2a4", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]["Forced"] or false 
	self:Toggle({ name = "T_921702e26cc5bee1", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_band_3"][i] = false end end end }) 
end 
T_ea978050f3465401 = T_ea978050f3465401 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_ea978050f3465401__FMenu", name_id = "Loc_6e6804823892f5ba", inject_menu = "T_86e41a2044e60970__Menu", class = T_ea978050f3465401}) 
function T_ea978050f3465401:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["Invisible"] or false 
	self:Toggle({ name = "T_dde883959ef3ff08", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["Forced"] or false 
	self:Toggle({ name = "T_f913cf41e1dbb5f9", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["wpn_fps_lmg_mg42_b_mg42"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["wpn_fps_lmg_mg42_b_mg42"] or false 
	self:Toggle({ name = "T_829b39b4baa6dd09", text = "Loc_d63cd805baad6f76", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["wpn_fps_lmg_mg42_b_mg42"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["wpn_fps_lmg_mg42_b_mg42"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["wpn_fps_lmg_mg42_b_mg42"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]["wpn_fps_lmg_mg42_b_mg42"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"]) do if i ~= "wpn_fps_lmg_mg42_b_mg42" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_b_mg34"][i] = false end end end }) 
end 
T_07dd1ee0e3c64e36 = T_07dd1ee0e3c64e36 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_07dd1ee0e3c64e36__FMenu", name_id = "Loc_adb0b24585ae34f7", inject_menu = "T_86e41a2044e60970__Menu", class = T_07dd1ee0e3c64e36}) 
function T_07dd1ee0e3c64e36:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["Invisible"] or false 
	self:Toggle({ name = "T_7288d53ad45991f3", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["Forced"] or false 
	self:Toggle({ name = "T_6c3521809e370d2f", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["wpn_fps_lmg_mg42_n42"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["wpn_fps_lmg_mg42_n42"] or false 
	self:Toggle({ name = "T_50af5d60d3d6e1c0", text = "Loc_949ff80429a00f02", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["wpn_fps_lmg_mg42_n42"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["wpn_fps_lmg_mg42_n42"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["wpn_fps_lmg_mg42_n42"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]["wpn_fps_lmg_mg42_n42"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"]) do if i ~= "wpn_fps_lmg_mg42_n42" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_n34"][i] = false end end end }) 
end 
T_99ba609ad1e0e55e = T_99ba609ad1e0e55e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_99ba609ad1e0e55e__FMenu", name_id = "Loc_42683f44d949326b", inject_menu = "T_86e41a2044e60970__Menu", class = T_99ba609ad1e0e55e}) 
function T_99ba609ad1e0e55e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]["Invisible"] or false 
	self:Toggle({ name = "T_9191b32627ebf637", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]["Forced"] or false 
	self:Toggle({ name = "T_502201808454aa85", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_bipod"][i] = false end end end }) 
end 
T_97395db49cadaa08 = T_97395db49cadaa08 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_97395db49cadaa08__FMenu", name_id = "Loc_d2aaf56792ce5445", inject_menu = "T_86e41a2044e60970__Menu", class = T_97395db49cadaa08}) 
function T_97395db49cadaa08:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["Invisible"] or false 
	self:Toggle({ name = "T_615cf5e8789aa104", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["Forced"] or false 
	self:Toggle({ name = "T_a723c85c305ce469", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_receiver"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_receiver"] or false 
	self:Toggle({ name = "T_477a5d50799cadab", text = "Loc_d9188963aceef231", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_receiver"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_receiver"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_receiver"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_receiver"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]) do if i ~= "wpn_fps_lmg_mg42_receiver" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_m_double"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_m_double"] or false 
	self:Toggle({ name = "T_6c57318eaa7a9797", text = "Loc_0f52ad045f7c1f40", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_m_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_m_double"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_m_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_m_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]) do if i ~= "wpn_fps_lmg_mg42_m_double" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_lid_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_lid_mg34"] or false 
	self:Toggle({ name = "T_e3c03b9e5d73c25a", text = "Loc_7b28204641649bcf", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_lid_mg34"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_lid_mg34"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_lid_mg34"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]["wpn_fps_lmg_mg42_lid_mg34"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"]) do if i ~= "wpn_fps_lmg_mg42_lid_mg34" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_dh_mg34"][i] = false end end end }) 
end 
T_3bd7fc764a55d087 = T_3bd7fc764a55d087 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_3bd7fc764a55d087__FMenu", name_id = "Loc_0f52ad045f7c1f40", inject_menu = "T_86e41a2044e60970__Menu", class = T_3bd7fc764a55d087}) 
function T_3bd7fc764a55d087:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["Invisible"] or false 
	self:Toggle({ name = "T_9c5deda4f1de683c", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["Forced"] or false 
	self:Toggle({ name = "T_878f12d7fcf86d23", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_receiver"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_receiver"] or false 
	self:Toggle({ name = "T_9c8f52cd271da26c", text = "Loc_d9188963aceef231", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_receiver"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_receiver"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_receiver"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_receiver"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]) do if i ~= "wpn_fps_lmg_mg42_receiver" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_dh_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_dh_mg34"] or false 
	self:Toggle({ name = "T_55ff6eeb0c8712eb", text = "Loc_d2aaf56792ce5445", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_dh_mg34"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_dh_mg34"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_dh_mg34"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_dh_mg34"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]) do if i ~= "wpn_fps_lmg_mg42_dh_mg34" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_lid_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_lid_mg34"] or false 
	self:Toggle({ name = "T_bffb26d107f71509", text = "Loc_7b28204641649bcf", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_lid_mg34"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_lid_mg34"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_lid_mg34"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]["wpn_fps_lmg_mg42_lid_mg34"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"]) do if i ~= "wpn_fps_lmg_mg42_lid_mg34" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_m_double"][i] = false end end end }) 
end 
T_0921022da2859b85 = T_0921022da2859b85 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_0921022da2859b85__FMenu", name_id = "Loc_7b28204641649bcf", inject_menu = "T_86e41a2044e60970__Menu", class = T_0921022da2859b85}) 
function T_0921022da2859b85:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["Invisible"] or false 
	self:Toggle({ name = "T_9cb65d648a1366c6", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["Forced"] or false 
	self:Toggle({ name = "T_cbb9e7c99f727a07", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_receiver"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_receiver"] or false 
	self:Toggle({ name = "T_a951f8d3d1326586", text = "Loc_d9188963aceef231", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_receiver"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_receiver"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_receiver"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_receiver"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]) do if i ~= "wpn_fps_lmg_mg42_receiver" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_dh_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_dh_mg34"] or false 
	self:Toggle({ name = "T_14d0e22d164017a2", text = "Loc_d2aaf56792ce5445", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_dh_mg34"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_dh_mg34"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_dh_mg34"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_dh_mg34"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]) do if i ~= "wpn_fps_lmg_mg42_dh_mg34" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_m_double"] = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_m_double"] or false 
	self:Toggle({ name = "T_9e3db79be06c7f30", text = "Loc_0f52ad045f7c1f40", value = WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_m_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_m_double"] then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_m_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]["wpn_fps_lmg_mg42_m_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"]) do if i ~= "wpn_fps_lmg_mg42_m_double" then WACApplyMyMenu._settings._apply["wpn_fps_lmg_mg42_lid_mg34"][i] = false end end end }) 
end 
