WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_2745aa2ad70dac25 = T_2745aa2ad70dac25 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_2745aa2ad70dac25__Menu", name_id = "bm_w_mp44", inject_menu = "WACApplyMyMenuMenu", class = T_2745aa2ad70dac25}) 
T_b0180bd8c669e8ab = T_b0180bd8c669e8ab or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b0180bd8c669e8ab__FMenu", name_id = "Loc_d9cf925feb2d775e", inject_menu = "T_2745aa2ad70dac25__Menu", class = T_b0180bd8c669e8ab}) 
function T_b0180bd8c669e8ab:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_7e2597fe9af44fd7", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_a4f0686d6f7972be", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_b_standard"][i] = false end end end }) 
end 
T_c3ef1964676d1830 = T_c3ef1964676d1830 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_c3ef1964676d1830__FMenu", name_id = "Loc_de1b97a1f6a990b9", inject_menu = "T_2745aa2ad70dac25__Menu", class = T_c3ef1964676d1830}) 
function T_c3ef1964676d1830:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_84892894bc071326", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_fd287a0c2dd6b6fd", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_body_standard"][i] = false end end end }) 
end 
T_7c813389b5d6a848 = T_7c813389b5d6a848 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_7c813389b5d6a848__FMenu", name_id = "Loc_9e0c1216ae86ad7d", inject_menu = "T_2745aa2ad70dac25__Menu", class = T_7c813389b5d6a848}) 
function T_7c813389b5d6a848:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_25a0394e0fb25774", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_31bcde9e64faa8b4", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_dh_standard"][i] = false end end end }) 
end 
T_7a914fbd092b0c35 = T_7a914fbd092b0c35 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_7a914fbd092b0c35__FMenu", name_id = "Loc_8cd93c01448f7362", inject_menu = "T_2745aa2ad70dac25__Menu", class = T_7a914fbd092b0c35}) 
function T_7a914fbd092b0c35:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["Invisible"] or false 
	self:Toggle({ name = "T_0eec8193a38611ea", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["Forced"] or false 
	self:Toggle({ name = "T_5dd34679f73b7f45", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_short_double"] or false 
	self:Toggle({ name = "T_c57bbb7e525b707d", text = "Loc_b979891f24a54714", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_short_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_short_double"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_short_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_short_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]) do if i ~= "wpn_fps_ass_mp44_m_short_double" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_standard"] or false 
	self:Toggle({ name = "T_b394d75b1e516501", text = "Loc_1ca8fd75e1a3247c", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]) do if i ~= "wpn_fps_ass_mp44_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_standard_double"] or false 
	self:Toggle({ name = "T_ae3e9c55fa781837", text = "Loc_b6c7749197863763", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_standard_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_standard_double"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_standard_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]["wpn_fps_ass_mp44_m_standard_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"]) do if i ~= "wpn_fps_ass_mp44_m_standard_double" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short"][i] = false end end end }) 
end 
T_23c5f3f3e4ba054c = T_23c5f3f3e4ba054c or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_23c5f3f3e4ba054c__FMenu", name_id = "Loc_b558e13229e56462", inject_menu = "T_2745aa2ad70dac25__Menu", class = T_23c5f3f3e4ba054c}) 
function T_23c5f3f3e4ba054c:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_d815f691549b04cc", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]["Forced"] or false 
	self:Toggle({ name = "T_441626a0551f64ce", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_fg_standard"][i] = false end end end }) 
end 
T_2b7a5734caedf3fd = T_2b7a5734caedf3fd or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_2b7a5734caedf3fd__FMenu", name_id = "Loc_f93b6fecb619ff10", inject_menu = "T_2745aa2ad70dac25__Menu", class = T_2b7a5734caedf3fd}) 
function T_2b7a5734caedf3fd:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_23c8fe4f62aa57fd", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]["Forced"] or false 
	self:Toggle({ name = "T_3830d41f48af21b5", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_s_standard"][i] = false end end end }) 
end 
T_94fc78ef72b1d2ab = T_94fc78ef72b1d2ab or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_94fc78ef72b1d2ab__FMenu", name_id = "Loc_b979891f24a54714", inject_menu = "T_2745aa2ad70dac25__Menu", class = T_94fc78ef72b1d2ab}) 
function T_94fc78ef72b1d2ab:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["Invisible"] or false 
	self:Toggle({ name = "T_ecfe5d08180891bf", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["Forced"] or false 
	self:Toggle({ name = "T_4a669447a975048d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_short"] or false 
	self:Toggle({ name = "T_afb6b41a5c9cea13", text = "Loc_8cd93c01448f7362", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_short"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]) do if i ~= "wpn_fps_ass_mp44_m_short" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_standard"] or false 
	self:Toggle({ name = "T_dd51eb6a04d8ddfa", text = "Loc_1ca8fd75e1a3247c", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]) do if i ~= "wpn_fps_ass_mp44_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_standard_double"] or false 
	self:Toggle({ name = "T_122bf7627d736804", text = "Loc_b6c7749197863763", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_standard_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_standard_double"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_standard_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]["wpn_fps_ass_mp44_m_standard_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"]) do if i ~= "wpn_fps_ass_mp44_m_standard_double" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_short_double"][i] = false end end end }) 
end 
T_028aca0491b89d46 = T_028aca0491b89d46 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_028aca0491b89d46__FMenu", name_id = "Loc_1ca8fd75e1a3247c", inject_menu = "T_2745aa2ad70dac25__Menu", class = T_028aca0491b89d46}) 
function T_028aca0491b89d46:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_a7cf80a19de4c4fb", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_68108e93b6833b11", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_short"] or false 
	self:Toggle({ name = "T_e6dea56d05568a3d", text = "Loc_8cd93c01448f7362", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_short"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]) do if i ~= "wpn_fps_ass_mp44_m_short" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_short_double"] or false 
	self:Toggle({ name = "T_9a918919881ba0aa", text = "Loc_b979891f24a54714", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_short_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_short_double"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_short_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_short_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]) do if i ~= "wpn_fps_ass_mp44_m_short_double" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_standard_double"] or false 
	self:Toggle({ name = "T_95974b7b5a706085", text = "Loc_b6c7749197863763", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_standard_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_standard_double"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_standard_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]["wpn_fps_ass_mp44_m_standard_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"]) do if i ~= "wpn_fps_ass_mp44_m_standard_double" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard"][i] = false end end end }) 
end 
T_74682d960ebb466e = T_74682d960ebb466e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_74682d960ebb466e__FMenu", name_id = "Loc_b6c7749197863763", inject_menu = "T_2745aa2ad70dac25__Menu", class = T_74682d960ebb466e}) 
function T_74682d960ebb466e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["Invisible"] or false 
	self:Toggle({ name = "T_fcc8f7caa213fc44", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["Forced"] or false 
	self:Toggle({ name = "T_1c193340d6dce7e6", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_short"] or false 
	self:Toggle({ name = "T_800a0a8242dd7d35", text = "Loc_8cd93c01448f7362", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_short"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]) do if i ~= "wpn_fps_ass_mp44_m_short" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_short_double"] or false 
	self:Toggle({ name = "T_3667f7923bc181eb", text = "Loc_b979891f24a54714", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_short_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_short_double"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_short_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_short_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]) do if i ~= "wpn_fps_ass_mp44_m_short_double" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_standard"] or false 
	self:Toggle({ name = "T_14f81cc5c0f1379f", text = "Loc_1ca8fd75e1a3247c", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]["wpn_fps_ass_mp44_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"]) do if i ~= "wpn_fps_ass_mp44_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_m_standard_double"][i] = false end end end }) 
end 
T_76c1626074669608 = T_76c1626074669608 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_76c1626074669608__FMenu", name_id = "Loc_f5669dc38a6be7a4", inject_menu = "T_2745aa2ad70dac25__Menu", class = T_76c1626074669608}) 
function T_76c1626074669608:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]["Invisible"] or false 
	self:Toggle({ name = "T_8bfec4880778645b", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]["Forced"] or false 
	self:Toggle({ name = "T_905fdb57c9360ef7", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_ass_mp44_o_scope"][i] = false end end end }) 
end 
