WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_b597fe1cd12853bd = T_b597fe1cd12853bd or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b597fe1cd12853bd__Menu", name_id = "bm_w_sterling", inject_menu = "WACApplyMyMenuMenu", class = T_b597fe1cd12853bd}) 
T_b75a797e3f1ed1f2 = T_b75a797e3f1ed1f2 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b75a797e3f1ed1f2__FMenu", name_id = "Loc_46062defb4817bd7", inject_menu = "T_b597fe1cd12853bd__Menu", class = T_b75a797e3f1ed1f2}) 
function T_b75a797e3f1ed1f2:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_d96f5f0f28a937a0", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_6702094521bd3372", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["wpn_fps_smg_sterling_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["wpn_fps_smg_sterling_b_long"] or false 
	self:Toggle({ name = "T_b3b30e7088c6809b", text = "Loc_44ae81793a1994cf", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["wpn_fps_smg_sterling_b_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["wpn_fps_smg_sterling_b_long"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["wpn_fps_smg_sterling_b_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]["wpn_fps_smg_sterling_b_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"]) do if i ~= "wpn_fps_smg_sterling_b_long" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_standard"][i] = false end end end }) 
end 
T_aa417ffed0ed509a = T_aa417ffed0ed509a or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_aa417ffed0ed509a__FMenu", name_id = "Loc_daf08b15d186c048", inject_menu = "T_b597fe1cd12853bd__Menu", class = T_aa417ffed0ed509a}) 
function T_aa417ffed0ed509a:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_ec8b1771e608abdd", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_86d414662816d33d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_body_standard"][i] = false end end end }) 
end 
T_61806623bf023288 = T_61806623bf023288 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_61806623bf023288__FMenu", name_id = "Loc_c86a9a1ce5822701", inject_menu = "T_b597fe1cd12853bd__Menu", class = T_61806623bf023288}) 
function T_61806623bf023288:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_e8e1858b755e5361", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]["Forced"] or false 
	self:Toggle({ name = "T_44c1509fa99a2291", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_bolt_standard"][i] = false end end end }) 
end 
T_f6e2d0ce5fffd3a0 = T_f6e2d0ce5fffd3a0 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_f6e2d0ce5fffd3a0__FMenu", name_id = "Loc_f06ee36a34322c48", inject_menu = "T_b597fe1cd12853bd__Menu", class = T_f6e2d0ce5fffd3a0}) 
function T_f6e2d0ce5fffd3a0:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["Invisible"] or false 
	self:Toggle({ name = "T_ce9e3ae417695754", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["Forced"] or false 
	self:Toggle({ name = "T_bc8383a418a9a9e7", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["wpn_fps_smg_sterling_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["wpn_fps_smg_sterling_m_long"] or false 
	self:Toggle({ name = "T_a5bad3442e34404e", text = "Loc_102f04c601a21c45", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["wpn_fps_smg_sterling_m_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["wpn_fps_smg_sterling_m_long"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["wpn_fps_smg_sterling_m_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["wpn_fps_smg_sterling_m_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]) do if i ~= "wpn_fps_smg_sterling_m_long" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["wpn_fps_smg_sterling_m_long_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["wpn_fps_smg_sterling_m_long_double"] or false 
	self:Toggle({ name = "T_8ffc9c9ee2bcf779", text = "Loc_dea6b7ddb62eeaaa", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["wpn_fps_smg_sterling_m_long_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["wpn_fps_smg_sterling_m_long_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["wpn_fps_smg_sterling_m_long_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]["wpn_fps_smg_sterling_m_long_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"]) do if i ~= "wpn_fps_smg_sterling_m_long_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_medium"][i] = false end end end }) 
end 
T_3aa41cd4afaa502e = T_3aa41cd4afaa502e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_3aa41cd4afaa502e__FMenu", name_id = "Loc_75dfa09b4ec573b1", inject_menu = "T_b597fe1cd12853bd__Menu", class = T_3aa41cd4afaa502e}) 
function T_3aa41cd4afaa502e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_9ff5b6e2f2423fbd", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]["Forced"] or false 
	self:Toggle({ name = "T_6632b6402fb77b49", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_s_standard"][i] = false end end end }) 
end 
T_06f8c77374406095 = T_06f8c77374406095 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_06f8c77374406095__FMenu", name_id = "Loc_44ae81793a1994cf", inject_menu = "T_b597fe1cd12853bd__Menu", class = T_06f8c77374406095}) 
function T_06f8c77374406095:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["Invisible"] or false 
	self:Toggle({ name = "T_7f42110c4c78986b", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["Forced"] or false 
	self:Toggle({ name = "T_9085135f25b50625", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["wpn_fps_smg_sterling_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["wpn_fps_smg_sterling_b_standard"] or false 
	self:Toggle({ name = "T_2571d3539dcf20c8", text = "Loc_46062defb4817bd7", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["wpn_fps_smg_sterling_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["wpn_fps_smg_sterling_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["wpn_fps_smg_sterling_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]["wpn_fps_smg_sterling_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"]) do if i ~= "wpn_fps_smg_sterling_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_b_long"][i] = false end end end }) 
end 
T_4250a227197aaf77 = T_4250a227197aaf77 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_4250a227197aaf77__FMenu", name_id = "Loc_102f04c601a21c45", inject_menu = "T_b597fe1cd12853bd__Menu", class = T_4250a227197aaf77}) 
function T_4250a227197aaf77:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["Invisible"] or false 
	self:Toggle({ name = "T_407d2519a374c1c7", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["Forced"] or false 
	self:Toggle({ name = "T_08c20d87882a3e2e", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["wpn_fps_smg_sterling_m_medium"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["wpn_fps_smg_sterling_m_medium"] or false 
	self:Toggle({ name = "T_e37a64c2ead5a528", text = "Loc_f06ee36a34322c48", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["wpn_fps_smg_sterling_m_medium"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["wpn_fps_smg_sterling_m_medium"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["wpn_fps_smg_sterling_m_medium"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["wpn_fps_smg_sterling_m_medium"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]) do if i ~= "wpn_fps_smg_sterling_m_medium" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["wpn_fps_smg_sterling_m_long_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["wpn_fps_smg_sterling_m_long_double"] or false 
	self:Toggle({ name = "T_9359d3970ed05f78", text = "Loc_dea6b7ddb62eeaaa", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["wpn_fps_smg_sterling_m_long_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["wpn_fps_smg_sterling_m_long_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["wpn_fps_smg_sterling_m_long_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]["wpn_fps_smg_sterling_m_long_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"]) do if i ~= "wpn_fps_smg_sterling_m_long_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long"][i] = false end end end }) 
end 
T_ad1d19482422f5bc = T_ad1d19482422f5bc or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_ad1d19482422f5bc__FMenu", name_id = "Loc_dea6b7ddb62eeaaa", inject_menu = "T_b597fe1cd12853bd__Menu", class = T_ad1d19482422f5bc}) 
function T_ad1d19482422f5bc:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["Invisible"] or false 
	self:Toggle({ name = "T_e8ba47df50bf916b", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["Forced"] or false 
	self:Toggle({ name = "T_35f6b92478bde4e3", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["wpn_fps_smg_sterling_m_medium"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["wpn_fps_smg_sterling_m_medium"] or false 
	self:Toggle({ name = "T_1fe750d986dc4246", text = "Loc_f06ee36a34322c48", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["wpn_fps_smg_sterling_m_medium"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["wpn_fps_smg_sterling_m_medium"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["wpn_fps_smg_sterling_m_medium"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["wpn_fps_smg_sterling_m_medium"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]) do if i ~= "wpn_fps_smg_sterling_m_medium" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["wpn_fps_smg_sterling_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["wpn_fps_smg_sterling_m_long"] or false 
	self:Toggle({ name = "T_cf528675ade24623", text = "Loc_102f04c601a21c45", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["wpn_fps_smg_sterling_m_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["wpn_fps_smg_sterling_m_long"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["wpn_fps_smg_sterling_m_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]["wpn_fps_smg_sterling_m_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"]) do if i ~= "wpn_fps_smg_sterling_m_long" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sterling_m_long_double"][i] = false end end end }) 
end 
