WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_1ced1457c98f0342 = T_1ced1457c98f0342 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_1ced1457c98f0342__Menu", name_id = "bm_w_sten", inject_menu = "WACApplyMyMenuMenu", class = T_1ced1457c98f0342}) 
T_c7ee12bfec3f9862 = T_c7ee12bfec3f9862 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_c7ee12bfec3f9862__FMenu", name_id = "Loc_728d01f5bca7842b", inject_menu = "T_1ced1457c98f0342__Menu", class = T_c7ee12bfec3f9862}) 
function T_c7ee12bfec3f9862:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_8b231203b9c617e7", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_906d886f5e00234b", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_fg_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_fg_wooden"] or false 
	self:Toggle({ name = "T_e2b6c20246a6d7a1", text = "Loc_d7cb9dceced8e1fb", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_fg_wooden"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_fg_wooden"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_fg_wooden"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_fg_wooden"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]) do if i ~= "wpn_fps_smg_sten_fg_wooden" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_g_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_g_wooden"] or false 
	self:Toggle({ name = "T_0642d2ad00f2df90", text = "Loc_5a88416c9abd0166", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_g_wooden"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_g_wooden"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_g_wooden"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_g_wooden"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]) do if i ~= "wpn_fps_smg_sten_g_wooden" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_body_mk3"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_body_mk3"] or false 
	self:Toggle({ name = "T_304bdc7b7e34be75", text = "Loc_aa57e6780efca108", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_body_mk3"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_body_mk3"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_body_mk3"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_body_mk3"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]) do if i ~= "wpn_fps_smg_sten_body_mk3" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_body_mk3_vented"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_body_mk3_vented"] or false 
	self:Toggle({ name = "T_ba00703a2d30d0e7", text = "Loc_a6859529c22dd2f6", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_body_mk3_vented"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_body_mk3_vented"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_body_mk3_vented"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]["wpn_fps_smg_sten_body_mk3_vented"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"]) do if i ~= "wpn_fps_smg_sten_body_mk3_vented" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_standard"][i] = false end end end }) 
end 
T_6085dc9b20f40916 = T_6085dc9b20f40916 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_6085dc9b20f40916__FMenu", name_id = "Loc_8df5c77a6b3f78b5", inject_menu = "T_1ced1457c98f0342__Menu", class = T_6085dc9b20f40916}) 
function T_6085dc9b20f40916:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_01bbdb8e2241f2df", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_4623e6602d347735", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["wpn_fps_smg_sten_o_lee_enfield"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["wpn_fps_smg_sten_o_lee_enfield"] or false 
	self:Toggle({ name = "T_db04ffc0ea878e39", text = "Loc_7e739ae32291e1de", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["wpn_fps_smg_sten_o_lee_enfield"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["wpn_fps_smg_sten_o_lee_enfield"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["wpn_fps_smg_sten_o_lee_enfield"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]["wpn_fps_smg_sten_o_lee_enfield"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"]) do if i ~= "wpn_fps_smg_sten_o_lee_enfield" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_b_standard"][i] = false end end end }) 
end 
T_254172cdf3faa891 = T_254172cdf3faa891 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_254172cdf3faa891__FMenu", name_id = "Loc_a061bbcb630fc6e1", inject_menu = "T_1ced1457c98f0342__Menu", class = T_254172cdf3faa891}) 
function T_254172cdf3faa891:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["Invisible"] or false 
	self:Toggle({ name = "T_3242cf96c25e838a", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["Forced"] or false 
	self:Toggle({ name = "T_1ebb9a38cf710fb9", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_standard"] or false 
	self:Toggle({ name = "T_a8ff39186fa6ab73", text = "Loc_2281e6ad740c8ae9", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]) do if i ~= "wpn_fps_smg_sten_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_standard_double"] or false 
	self:Toggle({ name = "T_cfc3635d8d9adaea", text = "Loc_fc6c232e53c00fef", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_standard_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_standard_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_standard_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_standard_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]) do if i ~= "wpn_fps_smg_sten_m_standard_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_long"] or false 
	self:Toggle({ name = "T_27f7b04af798dcb9", text = "Loc_718072a6ab22fd08", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_long"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]) do if i ~= "wpn_fps_smg_sten_m_long" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_long_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_long_double"] or false 
	self:Toggle({ name = "T_5f2d267567cbd546", text = "Loc_f15b8e00a1f9c6a4", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_long_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_long_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_long_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]["wpn_fps_smg_sten_m_long_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"]) do if i ~= "wpn_fps_smg_sten_m_long_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_short"][i] = false end end end }) 
end 
T_033c38671e78bfa4 = T_033c38671e78bfa4 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_033c38671e78bfa4__FMenu", name_id = "Loc_1632a010eb92c3ed", inject_menu = "T_1ced1457c98f0342__Menu", class = T_033c38671e78bfa4}) 
function T_033c38671e78bfa4:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_0bffdfda5092ca6d", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_893716d830b04cbd", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_dh_standard"][i] = false end end end }) 
end 
T_a983ea91c53b3868 = T_a983ea91c53b3868 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_a983ea91c53b3868__FMenu", name_id = "Loc_1301393374bbf212", inject_menu = "T_1ced1457c98f0342__Menu", class = T_a983ea91c53b3868}) 
function T_a983ea91c53b3868:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_61334e7b7d4296e5", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["Forced"] or false 
	self:Toggle({ name = "T_0a343b800325ee29", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["wpn_fps_smg_sten_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["wpn_fps_smg_sten_s_wooden"] or false 
	self:Toggle({ name = "T_a0c9729ecab0ca5d", text = "Loc_137396fbda2b265b", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["wpn_fps_smg_sten_s_wooden"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["wpn_fps_smg_sten_s_wooden"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["wpn_fps_smg_sten_s_wooden"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]["wpn_fps_smg_sten_s_wooden"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"]) do if i ~= "wpn_fps_smg_sten_s_wooden" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_standard"][i] = false end end end }) 
end 
T_b9fc45016bb097f6 = T_b9fc45016bb097f6 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b9fc45016bb097f6__FMenu", name_id = "Loc_2281e6ad740c8ae9", inject_menu = "T_1ced1457c98f0342__Menu", class = T_b9fc45016bb097f6}) 
function T_b9fc45016bb097f6:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_0e6dfc8ee271c3c2", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_fd045e6c163f2e31", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_short"] or false 
	self:Toggle({ name = "T_0321ebc42e18b1e7", text = "Loc_a061bbcb630fc6e1", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_short"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]) do if i ~= "wpn_fps_smg_sten_m_short" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_standard_double"] or false 
	self:Toggle({ name = "T_1736fc851a4f01fb", text = "Loc_fc6c232e53c00fef", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_standard_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_standard_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_standard_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_standard_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]) do if i ~= "wpn_fps_smg_sten_m_standard_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_long"] or false 
	self:Toggle({ name = "T_95878a8b20918e3f", text = "Loc_718072a6ab22fd08", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_long"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]) do if i ~= "wpn_fps_smg_sten_m_long" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_long_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_long_double"] or false 
	self:Toggle({ name = "T_70d6c1db2793a184", text = "Loc_f15b8e00a1f9c6a4", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_long_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_long_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_long_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]["wpn_fps_smg_sten_m_long_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"]) do if i ~= "wpn_fps_smg_sten_m_long_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard"][i] = false end end end }) 
end 
T_b4ff22325ac4e6a3 = T_b4ff22325ac4e6a3 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_b4ff22325ac4e6a3__FMenu", name_id = "Loc_fc6c232e53c00fef", inject_menu = "T_1ced1457c98f0342__Menu", class = T_b4ff22325ac4e6a3}) 
function T_b4ff22325ac4e6a3:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["Invisible"] or false 
	self:Toggle({ name = "T_abd904901d79281b", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["Forced"] or false 
	self:Toggle({ name = "T_c30a443714a5813b", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_short"] or false 
	self:Toggle({ name = "T_995a7cb795f66deb", text = "Loc_a061bbcb630fc6e1", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_short"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]) do if i ~= "wpn_fps_smg_sten_m_short" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_standard"] or false 
	self:Toggle({ name = "T_99dba68fc217a3af", text = "Loc_2281e6ad740c8ae9", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]) do if i ~= "wpn_fps_smg_sten_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_long"] or false 
	self:Toggle({ name = "T_5654885b07d1255e", text = "Loc_718072a6ab22fd08", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_long"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]) do if i ~= "wpn_fps_smg_sten_m_long" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_long_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_long_double"] or false 
	self:Toggle({ name = "T_f81115338fea295d", text = "Loc_f15b8e00a1f9c6a4", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_long_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_long_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_long_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]["wpn_fps_smg_sten_m_long_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"]) do if i ~= "wpn_fps_smg_sten_m_long_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_standard_double"][i] = false end end end }) 
end 
T_7deefcef36c043ea = T_7deefcef36c043ea or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_7deefcef36c043ea__FMenu", name_id = "Loc_718072a6ab22fd08", inject_menu = "T_1ced1457c98f0342__Menu", class = T_7deefcef36c043ea}) 
function T_7deefcef36c043ea:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["Invisible"] or false 
	self:Toggle({ name = "T_86611a3cad345fb4", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["Forced"] or false 
	self:Toggle({ name = "T_14658de04559d769", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_short"] or false 
	self:Toggle({ name = "T_664b614ce9093f3b", text = "Loc_a061bbcb630fc6e1", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_short"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]) do if i ~= "wpn_fps_smg_sten_m_short" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_standard"] or false 
	self:Toggle({ name = "T_13daad81a169e695", text = "Loc_2281e6ad740c8ae9", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]) do if i ~= "wpn_fps_smg_sten_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_standard_double"] or false 
	self:Toggle({ name = "T_51ca04b8781ca9c1", text = "Loc_fc6c232e53c00fef", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_standard_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_standard_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_standard_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_standard_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]) do if i ~= "wpn_fps_smg_sten_m_standard_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_long_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_long_double"] or false 
	self:Toggle({ name = "T_dee1ae10a13ea85b", text = "Loc_f15b8e00a1f9c6a4", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_long_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_long_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_long_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]["wpn_fps_smg_sten_m_long_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"]) do if i ~= "wpn_fps_smg_sten_m_long_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long"][i] = false end end end }) 
end 
T_4f7f248ef20389fd = T_4f7f248ef20389fd or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_4f7f248ef20389fd__FMenu", name_id = "Loc_f15b8e00a1f9c6a4", inject_menu = "T_1ced1457c98f0342__Menu", class = T_4f7f248ef20389fd}) 
function T_4f7f248ef20389fd:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["Invisible"] or false 
	self:Toggle({ name = "T_31df01325c879f99", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["Forced"] or false 
	self:Toggle({ name = "T_9c18be43bf94be9f", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_short"] or false 
	self:Toggle({ name = "T_df3aea370920d21a", text = "Loc_a061bbcb630fc6e1", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_short"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]) do if i ~= "wpn_fps_smg_sten_m_short" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_standard"] or false 
	self:Toggle({ name = "T_276887c406973319", text = "Loc_2281e6ad740c8ae9", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]) do if i ~= "wpn_fps_smg_sten_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_standard_double"] or false 
	self:Toggle({ name = "T_b2cc9037e075388d", text = "Loc_fc6c232e53c00fef", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_standard_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_standard_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_standard_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_standard_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]) do if i ~= "wpn_fps_smg_sten_m_standard_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_long"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_long"] or false 
	self:Toggle({ name = "T_32b40a29d5befe0d", text = "Loc_718072a6ab22fd08", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_long"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_long"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_long"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]["wpn_fps_smg_sten_m_long"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"]) do if i ~= "wpn_fps_smg_sten_m_long" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_m_long_double"][i] = false end end end }) 
end 
T_3de2ee1f7751a3b5 = T_3de2ee1f7751a3b5 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_3de2ee1f7751a3b5__FMenu", name_id = "Loc_137396fbda2b265b", inject_menu = "T_1ced1457c98f0342__Menu", class = T_3de2ee1f7751a3b5}) 
function T_3de2ee1f7751a3b5:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["Invisible"] or false 
	self:Toggle({ name = "T_4826f9a185db4d6e", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["Forced"] or false 
	self:Toggle({ name = "T_57b90a441cccc63f", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["wpn_fps_smg_sten_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["wpn_fps_smg_sten_s_standard"] or false 
	self:Toggle({ name = "T_f61569d6c0daf99b", text = "Loc_1301393374bbf212", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["wpn_fps_smg_sten_s_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["wpn_fps_smg_sten_s_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["wpn_fps_smg_sten_s_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]["wpn_fps_smg_sten_s_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"]) do if i ~= "wpn_fps_smg_sten_s_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_s_wooden"][i] = false end end end }) 
end 
T_6ae1ffb481fa9192 = T_6ae1ffb481fa9192 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_6ae1ffb481fa9192__FMenu", name_id = "Loc_d7cb9dceced8e1fb", inject_menu = "T_1ced1457c98f0342__Menu", class = T_6ae1ffb481fa9192}) 
function T_6ae1ffb481fa9192:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["Invisible"] or false 
	self:Toggle({ name = "T_daec34f6b062a6e7", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["Forced"] or false 
	self:Toggle({ name = "T_766e8639992747c3", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_standard"] or false 
	self:Toggle({ name = "T_d1150574d38da1f7", text = "Loc_728d01f5bca7842b", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]) do if i ~= "wpn_fps_smg_sten_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_g_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_g_wooden"] or false 
	self:Toggle({ name = "T_a2d2027108ca7426", text = "Loc_5a88416c9abd0166", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_g_wooden"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_g_wooden"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_g_wooden"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_g_wooden"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]) do if i ~= "wpn_fps_smg_sten_g_wooden" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_mk3"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_mk3"] or false 
	self:Toggle({ name = "T_93db6b0980f9d2d7", text = "Loc_aa57e6780efca108", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_mk3"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_mk3"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_mk3"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_mk3"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]) do if i ~= "wpn_fps_smg_sten_body_mk3" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_mk3_vented"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_mk3_vented"] or false 
	self:Toggle({ name = "T_8edb0d245a5b9171", text = "Loc_a6859529c22dd2f6", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_mk3_vented"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_mk3_vented"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_mk3_vented"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]["wpn_fps_smg_sten_body_mk3_vented"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"]) do if i ~= "wpn_fps_smg_sten_body_mk3_vented" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_fg_wooden"][i] = false end end end }) 
end 
T_a31e39d5a7973794 = T_a31e39d5a7973794 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_a31e39d5a7973794__FMenu", name_id = "Loc_5a88416c9abd0166", inject_menu = "T_1ced1457c98f0342__Menu", class = T_a31e39d5a7973794}) 
function T_a31e39d5a7973794:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["Invisible"] or false 
	self:Toggle({ name = "T_d2b7d9df72ec63f9", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["Forced"] or false 
	self:Toggle({ name = "T_1bac93df86934b09", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_standard"] or false 
	self:Toggle({ name = "T_3c1d291ffcecf111", text = "Loc_728d01f5bca7842b", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]) do if i ~= "wpn_fps_smg_sten_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_fg_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_fg_wooden"] or false 
	self:Toggle({ name = "T_63b50ab80dfd7c93", text = "Loc_d7cb9dceced8e1fb", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_fg_wooden"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_fg_wooden"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_fg_wooden"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_fg_wooden"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]) do if i ~= "wpn_fps_smg_sten_fg_wooden" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_mk3"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_mk3"] or false 
	self:Toggle({ name = "T_caed2c86c7972cd3", text = "Loc_aa57e6780efca108", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_mk3"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_mk3"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_mk3"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_mk3"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]) do if i ~= "wpn_fps_smg_sten_body_mk3" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_mk3_vented"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_mk3_vented"] or false 
	self:Toggle({ name = "T_3c02607b4eb0deb2", text = "Loc_a6859529c22dd2f6", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_mk3_vented"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_mk3_vented"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_mk3_vented"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]["wpn_fps_smg_sten_body_mk3_vented"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"]) do if i ~= "wpn_fps_smg_sten_body_mk3_vented" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_g_wooden"][i] = false end end end }) 
end 
T_57c7faff7016fc22 = T_57c7faff7016fc22 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_57c7faff7016fc22__FMenu", name_id = "Loc_189b64351be110a5", inject_menu = "T_1ced1457c98f0342__Menu", class = T_57c7faff7016fc22}) 
function T_57c7faff7016fc22:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]["Invisible"] or false 
	self:Toggle({ name = "T_b7181005bed09b4c", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]["Forced"] or false 
	self:Toggle({ name = "T_aedbcf5715cf43ad", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_ns_slanted"][i] = false end end end }) 
end 
T_c9c6c5988a070a6f = T_c9c6c5988a070a6f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_c9c6c5988a070a6f__FMenu", name_id = "Loc_aa57e6780efca108", inject_menu = "T_1ced1457c98f0342__Menu", class = T_c9c6c5988a070a6f}) 
function T_c9c6c5988a070a6f:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["Invisible"] or false 
	self:Toggle({ name = "T_0a296b6bc630ba64", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["Forced"] or false 
	self:Toggle({ name = "T_d7fc0427c5a8361b", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_body_standard"] or false 
	self:Toggle({ name = "T_d3bd94dc5e1fd287", text = "Loc_728d01f5bca7842b", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]) do if i ~= "wpn_fps_smg_sten_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_fg_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_fg_wooden"] or false 
	self:Toggle({ name = "T_2dcee6382f1dcba4", text = "Loc_d7cb9dceced8e1fb", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_fg_wooden"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_fg_wooden"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_fg_wooden"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_fg_wooden"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]) do if i ~= "wpn_fps_smg_sten_fg_wooden" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_g_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_g_wooden"] or false 
	self:Toggle({ name = "T_98dfc07238edae96", text = "Loc_5a88416c9abd0166", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_g_wooden"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_g_wooden"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_g_wooden"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_g_wooden"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]) do if i ~= "wpn_fps_smg_sten_g_wooden" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_body_mk3_vented"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_body_mk3_vented"] or false 
	self:Toggle({ name = "T_37de71f05fc1a32f", text = "Loc_a6859529c22dd2f6", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_body_mk3_vented"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_body_mk3_vented"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_body_mk3_vented"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]["wpn_fps_smg_sten_body_mk3_vented"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"]) do if i ~= "wpn_fps_smg_sten_body_mk3_vented" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3"][i] = false end end end }) 
end 
T_f4b215f76ea24acd = T_f4b215f76ea24acd or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_f4b215f76ea24acd__FMenu", name_id = "Loc_a6859529c22dd2f6", inject_menu = "T_1ced1457c98f0342__Menu", class = T_f4b215f76ea24acd}) 
function T_f4b215f76ea24acd:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["Invisible"] or false 
	self:Toggle({ name = "T_ac18927be84ece5b", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["Forced"] or false 
	self:Toggle({ name = "T_e77816fbe828cb33", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_body_standard"] or false 
	self:Toggle({ name = "T_193085d581904830", text = "Loc_728d01f5bca7842b", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]) do if i ~= "wpn_fps_smg_sten_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_fg_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_fg_wooden"] or false 
	self:Toggle({ name = "T_da02614ea7e3ce19", text = "Loc_d7cb9dceced8e1fb", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_fg_wooden"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_fg_wooden"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_fg_wooden"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_fg_wooden"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]) do if i ~= "wpn_fps_smg_sten_fg_wooden" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_g_wooden"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_g_wooden"] or false 
	self:Toggle({ name = "T_fcb4fee7b1e07dd2", text = "Loc_5a88416c9abd0166", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_g_wooden"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_g_wooden"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_g_wooden"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_g_wooden"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]) do if i ~= "wpn_fps_smg_sten_g_wooden" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_body_mk3"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_body_mk3"] or false 
	self:Toggle({ name = "T_8fa52057a910d933", text = "Loc_aa57e6780efca108", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_body_mk3"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_body_mk3"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_body_mk3"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]["wpn_fps_smg_sten_body_mk3"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"]) do if i ~= "wpn_fps_smg_sten_body_mk3" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_body_mk3_vented"][i] = false end end end }) 
end 
T_ca90ab0b56f5e071 = T_ca90ab0b56f5e071 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_ca90ab0b56f5e071__FMenu", name_id = "Loc_7e739ae32291e1de", inject_menu = "T_1ced1457c98f0342__Menu", class = T_ca90ab0b56f5e071}) 
function T_ca90ab0b56f5e071:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["Invisible"] or false 
	self:Toggle({ name = "T_8639632d5a564f1d", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["Forced"] or false 
	self:Toggle({ name = "T_98ecfc1fbd7bab0a", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["wpn_fps_smg_sten_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["wpn_fps_smg_sten_b_standard"] or false 
	self:Toggle({ name = "T_7b2f1b073a91cdb8", text = "Loc_8df5c77a6b3f78b5", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["wpn_fps_smg_sten_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["wpn_fps_smg_sten_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["wpn_fps_smg_sten_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]["wpn_fps_smg_sten_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"]) do if i ~= "wpn_fps_smg_sten_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_sten_o_lee_enfield"][i] = false end end end }) 
end 
