WACApplyMyMenu = WACApplyMyMenu or nil 
if not WACApplyMyMenu then return end 
T_308b9b2aad7cc191 = T_308b9b2aad7cc191 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_308b9b2aad7cc191__Menu", name_id = "bm_w_thompson", inject_menu = "WACApplyMyMenuMenu", class = T_308b9b2aad7cc191}) 
T_dc18ae539dceec97 = T_dc18ae539dceec97 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_dc18ae539dceec97__FMenu", name_id = "Loc_af6b16d3c79af438", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_dc18ae539dceec97}) 
function T_dc18ae539dceec97:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_e59365b65162c2f2", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["Forced"] or false 
	self:Toggle({ name = "T_f3e2b55803d7019c", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_o_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_o_standard"] or false 
	self:Toggle({ name = "T_67cae22baab81065", text = "Loc_0e3aadc0f1fd06c5", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_o_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_o_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_o_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_o_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]) do if i ~= "wpn_fps_smg_thompson_o_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_body_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_body_m1928"] or false 
	self:Toggle({ name = "T_3addb2f829450ea4", text = "Loc_d75d91ac4f8310f7", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_body_m1928"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_body_m1928"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_body_m1928"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_body_m1928"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]) do if i ~= "wpn_fps_smg_thompson_body_m1928" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_o_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_o_m1928"] or false 
	self:Toggle({ name = "T_ed00835b173467db", text = "Loc_60bdc039a53f2d94", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_o_m1928"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_o_m1928"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_o_m1928"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]["wpn_fps_smg_thompson_o_m1928"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"]) do if i ~= "wpn_fps_smg_thompson_o_m1928" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_standard"][i] = false end end end }) 
end 
T_dd4b23e3c0b09a4b = T_dd4b23e3c0b09a4b or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_dd4b23e3c0b09a4b__FMenu", name_id = "Loc_a3a43c08ee230d09", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_dd4b23e3c0b09a4b}) 
function T_dd4b23e3c0b09a4b:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_a6f1a8e3d6c5e07b", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]["Forced"] or false 
	self:Toggle({ name = "T_6ba5aa5371efe68f", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_s_standard"][i] = false end end end }) 
end 
T_7d52228fa62b1038 = T_7d52228fa62b1038 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_7d52228fa62b1038__FMenu", name_id = "Loc_7430c0cccbefd8f3", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_7d52228fa62b1038}) 
function T_7d52228fa62b1038:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_4673c602443e7015", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["Forced"] or false 
	self:Toggle({ name = "T_acadbf2446d2b576", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["wpn_fps_smg_thompson_b_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["wpn_fps_smg_thompson_b_m1928"] or false 
	self:Toggle({ name = "T_5a1b4e4e1eab1bea", text = "Loc_26a42aac2c0af0be", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["wpn_fps_smg_thompson_b_m1928"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["wpn_fps_smg_thompson_b_m1928"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["wpn_fps_smg_thompson_b_m1928"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]["wpn_fps_smg_thompson_b_m1928"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"]) do if i ~= "wpn_fps_smg_thompson_b_m1928" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_standard"][i] = false end end end }) 
end 
T_402e8ccf5da82837 = T_402e8ccf5da82837 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_402e8ccf5da82837__FMenu", name_id = "Loc_ad71854e217ec2b3", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_402e8ccf5da82837}) 
function T_402e8ccf5da82837:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["Invisible"] or false 
	self:Toggle({ name = "T_a26e47d59b315241", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["Forced"] or false 
	self:Toggle({ name = "T_aa42cc23bb67e331", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_short_double"] or false 
	self:Toggle({ name = "T_9510fbce9f20e38f", text = "Loc_f511c0eed70208c3", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_short_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_short_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_short_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_short_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]) do if i ~= "wpn_fps_smg_thompson_m_short_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_standard"] or false 
	self:Toggle({ name = "T_28059b74538cc6e7", text = "Loc_4d565eb427c2f22f", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]) do if i ~= "wpn_fps_smg_thompson_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_standard_double"] or false 
	self:Toggle({ name = "T_62af8e8ab09cac37", text = "Loc_ae50288a6c1a911d", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_standard_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_standard_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_standard_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_standard_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]) do if i ~= "wpn_fps_smg_thompson_m_standard_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_drum"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_drum"] or false 
	self:Toggle({ name = "T_c496441cad59028b", text = "Loc_48be486499fc9ada", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_drum"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_drum"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_drum"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]["wpn_fps_smg_thompson_m_drum"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"]) do if i ~= "wpn_fps_smg_thompson_m_drum" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short"][i] = false end end end }) 
end 
T_c99e82b2716af641 = T_c99e82b2716af641 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_c99e82b2716af641__FMenu", name_id = "Loc_da476445f9457843", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_c99e82b2716af641}) 
function T_c99e82b2716af641:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_f0c70cc756497501", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["Forced"] or false 
	self:Toggle({ name = "T_d4c00693c27b4176", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["wpn_fps_smg_thompson_dh_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["wpn_fps_smg_thompson_dh_m1928"] or false 
	self:Toggle({ name = "T_7d8412f491aad864", text = "Loc_c4424b6a17375f10", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["wpn_fps_smg_thompson_dh_m1928"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["wpn_fps_smg_thompson_dh_m1928"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["wpn_fps_smg_thompson_dh_m1928"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]["wpn_fps_smg_thompson_dh_m1928"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"]) do if i ~= "wpn_fps_smg_thompson_dh_m1928" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_standard"][i] = false end end end }) 
end 
T_1222d8ae83279aeb = T_1222d8ae83279aeb or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_1222d8ae83279aeb__FMenu", name_id = "Loc_d1bdabdc92e8d44f", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_1222d8ae83279aeb}) 
function T_1222d8ae83279aeb:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]["Invisible"] or false 
	self:Toggle({ name = "T_d864f30a0642ca3d", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]["Forced"] or false 
	self:Toggle({ name = "T_b89672ab59fc470d", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_extra_sling"][i] = false end end end }) 
end 
T_0172e455dceea95a = T_0172e455dceea95a or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_0172e455dceea95a__FMenu", name_id = "Loc_7517788c171dc0c5", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_0172e455dceea95a}) 
function T_0172e455dceea95a:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_68d096076adf75f2", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["Forced"] or false 
	self:Toggle({ name = "T_f88f9f495dc6669c", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["wpn_fps_smg_thompson_fg_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["wpn_fps_smg_thompson_fg_m1928"] or false 
	self:Toggle({ name = "T_4bd7ce6d8b9445ec", text = "Loc_a274a689379a4749", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["wpn_fps_smg_thompson_fg_m1928"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["wpn_fps_smg_thompson_fg_m1928"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["wpn_fps_smg_thompson_fg_m1928"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]["wpn_fps_smg_thompson_fg_m1928"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"]) do if i ~= "wpn_fps_smg_thompson_fg_m1928" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_standard"][i] = false end end end }) 
end 
T_584baa28fd7563ba = T_584baa28fd7563ba or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_584baa28fd7563ba__FMenu", name_id = "Loc_e618c11deae5c4f2", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_584baa28fd7563ba}) 
function T_584baa28fd7563ba:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_2a5ef8be6008402b", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]["Forced"] or false 
	self:Toggle({ name = "T_ce77feda7494d71e", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_release_standard"][i] = false end end end }) 
end 
T_c5b9bb1a3ab5c2b8 = T_c5b9bb1a3ab5c2b8 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_c5b9bb1a3ab5c2b8__FMenu", name_id = "Loc_6c31c0afe5c5d6e6", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_c5b9bb1a3ab5c2b8}) 
function T_c5b9bb1a3ab5c2b8:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_e3050263781cce0f", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]["Forced"] or false 
	self:Toggle({ name = "T_9a979d8d242a8124", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_g_standard"][i] = false end end end }) 
end 
T_30e718f9fb534690 = T_30e718f9fb534690 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_30e718f9fb534690__FMenu", name_id = "Loc_0e3aadc0f1fd06c5", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_30e718f9fb534690}) 
function T_30e718f9fb534690:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_dae003aee1731589", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["Forced"] or false 
	self:Toggle({ name = "T_6710b5e79ddea0e7", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_body_standard"] or false 
	self:Toggle({ name = "T_4a8e8ab82ca44149", text = "Loc_af6b16d3c79af438", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]) do if i ~= "wpn_fps_smg_thompson_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_body_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_body_m1928"] or false 
	self:Toggle({ name = "T_21f95cc60f9fdd7e", text = "Loc_d75d91ac4f8310f7", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_body_m1928"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_body_m1928"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_body_m1928"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_body_m1928"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]) do if i ~= "wpn_fps_smg_thompson_body_m1928" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_o_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_o_m1928"] or false 
	self:Toggle({ name = "T_7e2a7ee369610e2f", text = "Loc_60bdc039a53f2d94", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_o_m1928"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_o_m1928"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_o_m1928"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]["wpn_fps_smg_thompson_o_m1928"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"]) do if i ~= "wpn_fps_smg_thompson_o_m1928" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_standard"][i] = false end end end }) 
end 
T_2bde261981bf7495 = T_2bde261981bf7495 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_2bde261981bf7495__FMenu", name_id = "Loc_26a42aac2c0af0be", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_2bde261981bf7495}) 
function T_2bde261981bf7495:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["Invisible"] or false 
	self:Toggle({ name = "T_2632478b68e5c7e9", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["Forced"] or false 
	self:Toggle({ name = "T_3dc09a2ff5bc353a", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["wpn_fps_smg_thompson_b_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["wpn_fps_smg_thompson_b_standard"] or false 
	self:Toggle({ name = "T_f87b25f9b7071a11", text = "Loc_7430c0cccbefd8f3", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["wpn_fps_smg_thompson_b_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["wpn_fps_smg_thompson_b_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["wpn_fps_smg_thompson_b_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]["wpn_fps_smg_thompson_b_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"]) do if i ~= "wpn_fps_smg_thompson_b_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_b_m1928"][i] = false end end end }) 
end 
T_a13a2b4726bad19f = T_a13a2b4726bad19f or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_a13a2b4726bad19f__FMenu", name_id = "Loc_d75d91ac4f8310f7", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_a13a2b4726bad19f}) 
function T_a13a2b4726bad19f:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["Invisible"] or false 
	self:Toggle({ name = "T_80b91794f0dddc6b", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["Forced"] or false 
	self:Toggle({ name = "T_6fa2cbeb3bb9c899", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_body_standard"] or false 
	self:Toggle({ name = "T_52991476c8e75d46", text = "Loc_af6b16d3c79af438", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]) do if i ~= "wpn_fps_smg_thompson_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_o_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_o_standard"] or false 
	self:Toggle({ name = "T_f6d39f07d8db1785", text = "Loc_0e3aadc0f1fd06c5", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_o_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_o_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_o_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_o_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]) do if i ~= "wpn_fps_smg_thompson_o_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_o_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_o_m1928"] or false 
	self:Toggle({ name = "T_16c5e9d9ccfbb9ff", text = "Loc_60bdc039a53f2d94", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_o_m1928"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_o_m1928"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_o_m1928"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]["wpn_fps_smg_thompson_o_m1928"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"]) do if i ~= "wpn_fps_smg_thompson_o_m1928" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_body_m1928"][i] = false end end end }) 
end 
T_1868661981e1b86d = T_1868661981e1b86d or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_1868661981e1b86d__FMenu", name_id = "Loc_60bdc039a53f2d94", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_1868661981e1b86d}) 
function T_1868661981e1b86d:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["Invisible"] or false 
	self:Toggle({ name = "T_cbfadea9048704ef", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["Forced"] or false 
	self:Toggle({ name = "T_c7b0d78ade6a8d04", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_body_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_body_standard"] or false 
	self:Toggle({ name = "T_994ad0bcc82b2861", text = "Loc_af6b16d3c79af438", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_body_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_body_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_body_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_body_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]) do if i ~= "wpn_fps_smg_thompson_body_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_o_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_o_standard"] or false 
	self:Toggle({ name = "T_24a8ae6fb7dd8993", text = "Loc_0e3aadc0f1fd06c5", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_o_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_o_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_o_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_o_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]) do if i ~= "wpn_fps_smg_thompson_o_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_body_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_body_m1928"] or false 
	self:Toggle({ name = "T_7116ba60753cc9d3", text = "Loc_d75d91ac4f8310f7", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_body_m1928"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_body_m1928"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_body_m1928"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]["wpn_fps_smg_thompson_body_m1928"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"]) do if i ~= "wpn_fps_smg_thompson_body_m1928" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_o_m1928"][i] = false end end end }) 
end 
T_65ddcde6e5546f07 = T_65ddcde6e5546f07 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_65ddcde6e5546f07__FMenu", name_id = "Loc_f511c0eed70208c3", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_65ddcde6e5546f07}) 
function T_65ddcde6e5546f07:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["Invisible"] or false 
	self:Toggle({ name = "T_66bf707e255e168f", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["Forced"] or false 
	self:Toggle({ name = "T_0b8ff8fb93fa04e5", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_short"] or false 
	self:Toggle({ name = "T_b24ea660dfef57d0", text = "Loc_ad71854e217ec2b3", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_short"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]) do if i ~= "wpn_fps_smg_thompson_m_short" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_standard"] or false 
	self:Toggle({ name = "T_dff7ca0d4c4e904f", text = "Loc_4d565eb427c2f22f", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]) do if i ~= "wpn_fps_smg_thompson_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_standard_double"] or false 
	self:Toggle({ name = "T_7558b6c6c883efaa", text = "Loc_ae50288a6c1a911d", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_standard_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_standard_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_standard_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_standard_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]) do if i ~= "wpn_fps_smg_thompson_m_standard_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_drum"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_drum"] or false 
	self:Toggle({ name = "T_82ac213810f2e03f", text = "Loc_48be486499fc9ada", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_drum"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_drum"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_drum"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]["wpn_fps_smg_thompson_m_drum"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"]) do if i ~= "wpn_fps_smg_thompson_m_drum" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_short_double"][i] = false end end end }) 
end 
T_bc1e5a333dc61dec = T_bc1e5a333dc61dec or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_bc1e5a333dc61dec__FMenu", name_id = "Loc_4d565eb427c2f22f", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_bc1e5a333dc61dec}) 
function T_bc1e5a333dc61dec:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["Invisible"] or false 
	self:Toggle({ name = "T_97a0a26e04c4f6d6", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["Forced"] or false 
	self:Toggle({ name = "T_fbfa281b7eb1c1e3", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_short"] or false 
	self:Toggle({ name = "T_6bbc89dc068f9077", text = "Loc_ad71854e217ec2b3", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_short"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]) do if i ~= "wpn_fps_smg_thompson_m_short" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_short_double"] or false 
	self:Toggle({ name = "T_7fab369f9c56ffa0", text = "Loc_f511c0eed70208c3", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_short_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_short_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_short_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_short_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]) do if i ~= "wpn_fps_smg_thompson_m_short_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_standard_double"] or false 
	self:Toggle({ name = "T_efc6d12518093bb1", text = "Loc_ae50288a6c1a911d", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_standard_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_standard_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_standard_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_standard_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]) do if i ~= "wpn_fps_smg_thompson_m_standard_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_drum"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_drum"] or false 
	self:Toggle({ name = "T_c8637c40432ce254", text = "Loc_48be486499fc9ada", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_drum"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_drum"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_drum"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]["wpn_fps_smg_thompson_m_drum"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"]) do if i ~= "wpn_fps_smg_thompson_m_drum" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard"][i] = false end end end }) 
end 
T_388899419f554844 = T_388899419f554844 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_388899419f554844__FMenu", name_id = "Loc_ae50288a6c1a911d", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_388899419f554844}) 
function T_388899419f554844:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["Invisible"] or false 
	self:Toggle({ name = "T_4d3554fe8b2753a9", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["Forced"] or false 
	self:Toggle({ name = "T_9a88134491eee3b7", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_short"] or false 
	self:Toggle({ name = "T_6098aa94bed6c489", text = "Loc_ad71854e217ec2b3", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_short"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]) do if i ~= "wpn_fps_smg_thompson_m_short" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_short_double"] or false 
	self:Toggle({ name = "T_6002ca14476ec303", text = "Loc_f511c0eed70208c3", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_short_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_short_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_short_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_short_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]) do if i ~= "wpn_fps_smg_thompson_m_short_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_standard"] or false 
	self:Toggle({ name = "T_78d3ac7496e06060", text = "Loc_4d565eb427c2f22f", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]) do if i ~= "wpn_fps_smg_thompson_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_drum"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_drum"] or false 
	self:Toggle({ name = "T_ab044bae7bdc3d19", text = "Loc_48be486499fc9ada", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_drum"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_drum"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_drum"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]["wpn_fps_smg_thompson_m_drum"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"]) do if i ~= "wpn_fps_smg_thompson_m_drum" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_standard_double"][i] = false end end end }) 
end 
T_52c6ecae87e84da4 = T_52c6ecae87e84da4 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_52c6ecae87e84da4__FMenu", name_id = "Loc_48be486499fc9ada", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_52c6ecae87e84da4}) 
function T_52c6ecae87e84da4:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["Invisible"] or false 
	self:Toggle({ name = "T_46b66391d73ce8c5", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["Forced"] or false 
	self:Toggle({ name = "T_527e6d14783088c5", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_short"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_short"] or false 
	self:Toggle({ name = "T_e1421ab5b85775e1", text = "Loc_ad71854e217ec2b3", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_short"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_short"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_short"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_short"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]) do if i ~= "wpn_fps_smg_thompson_m_short" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_short_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_short_double"] or false 
	self:Toggle({ name = "T_fef3974bd49b6f3f", text = "Loc_f511c0eed70208c3", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_short_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_short_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_short_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_short_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]) do if i ~= "wpn_fps_smg_thompson_m_short_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_standard"] or false 
	self:Toggle({ name = "T_be3cf30d9e6d6413", text = "Loc_4d565eb427c2f22f", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]) do if i ~= "wpn_fps_smg_thompson_m_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_standard_double"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_standard_double"] or false 
	self:Toggle({ name = "T_80e76e21fceaad89", text = "Loc_ae50288a6c1a911d", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_standard_double"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_standard_double"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_standard_double"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]["wpn_fps_smg_thompson_m_standard_double"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"]) do if i ~= "wpn_fps_smg_thompson_m_standard_double" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_m_drum"][i] = false end end end }) 
end 
T_6658a7a0017e980e = T_6658a7a0017e980e or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_6658a7a0017e980e__FMenu", name_id = "Loc_a274a689379a4749", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_6658a7a0017e980e}) 
function T_6658a7a0017e980e:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["Invisible"] or false 
	self:Toggle({ name = "T_5bedc0922df630fa", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["Forced"] or false 
	self:Toggle({ name = "T_23d1a37a583b463a", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["wpn_fps_smg_thompson_fg_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["wpn_fps_smg_thompson_fg_standard"] or false 
	self:Toggle({ name = "T_8f7996dde6118806", text = "Loc_7517788c171dc0c5", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["wpn_fps_smg_thompson_fg_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["wpn_fps_smg_thompson_fg_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["wpn_fps_smg_thompson_fg_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]["wpn_fps_smg_thompson_fg_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"]) do if i ~= "wpn_fps_smg_thompson_fg_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_fg_m1928"][i] = false end end end }) 
end 
T_18bdb042a3305006 = T_18bdb042a3305006 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_18bdb042a3305006__FMenu", name_id = "Loc_f389bdc5e6c5703e", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_18bdb042a3305006}) 
function T_18bdb042a3305006:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]["Invisible"] or false 
	self:Toggle({ name = "T_0899fbca6c03c4f0", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]["Forced"] or false 
	self:Toggle({ name = "T_5398de0356288375", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_ns_cutts"][i] = false end end end }) 
end 
T_3e3e79fb1abec7e7 = T_3e3e79fb1abec7e7 or class(BLTMenu) 
RaidMenuHelper:CreateMenu({name = "T_3e3e79fb1abec7e7__FMenu", name_id = "Loc_c4424b6a17375f10", inject_menu = "T_308b9b2aad7cc191__Menu", class = T_3e3e79fb1abec7e7}) 
function T_3e3e79fb1abec7e7:Init() 
	WACApplyMyMenu = WACApplyMyMenu or {} 
	WACApplyMyMenu._settings = WACApplyMyMenu._settings or {} 
	WACApplyMyMenu._settings._apply = WACApplyMyMenu._settings._apply or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["Invisible"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["Invisible"] or false 
	self:Toggle({ name = "T_c91aae455fa278dd", text = "Loc_297030c20c18f83a", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["Invisible"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["Invisible"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["Invisible"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["Invisible"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]) do if i ~= "Invisible" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["Forced"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["Forced"] or false 
	self:Toggle({ name = "T_e4b334488beb91d8", text = "Loc_a833f0b610957269", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["Forced"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["Forced"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["Forced"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["Forced"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]) do if i ~= "Forced" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"][i] = false end end end }) 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"] or {} 
	WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["wpn_fps_smg_thompson_dh_standard"] = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["wpn_fps_smg_thompson_dh_standard"] or false 
	self:Toggle({ name = "T_defe1aa81ce24a9f", text = "Loc_da476445f9457843", value = WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["wpn_fps_smg_thompson_dh_standard"] and true or false, callback = function() if WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["wpn_fps_smg_thompson_dh_standard"] then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["wpn_fps_smg_thompson_dh_standard"] = false else WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]["wpn_fps_smg_thompson_dh_standard"] = true end for i, d in pairs(WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"]) do if i ~= "wpn_fps_smg_thompson_dh_standard" then WACApplyMyMenu._settings._apply["wpn_fps_smg_thompson_dh_m1928"][i] = false end end end }) 
end 
